import type { BuildAppModalCtxSourceInput } from './buildAppModalCtxSource';
import type { BuildAppModalCtxInputArgs } from './buildAppModalCtxInput';

export function modalCtxSecurityFields(args: BuildAppModalCtxInputArgs): Pick<BuildAppModalCtxSourceInput, never> {
  return {
    chooseSignCertNative: args.pdfActions.chooseSignCertNative,
    closePasswordModal: args.pdfActions.closePasswordModal,
    decryptPassword: args.security.decryptPassword,
    handleClearPdfMetadata: args.pdfActions.handleClearPdfMetadata,
    handleProtectPdf: args.pdfActions.handleProtectPdf,
    handleRemovePdfPassword: args.pdfActions.handleRemovePdfPassword,
    handleSaveMetadata: args.pdfActions.handleSaveMetadata,
    handleSignPdf: args.pdfActions.handleSignPdf,
    metadataAuthor: args.security.metadataAuthor,
    metadataCreationDate: args.security.metadataCreationDate,
    metadataCreator: args.security.metadataCreator,
    metadataKeywords: args.security.metadataKeywords,
    metadataModDate: args.security.metadataModDate,
    metadataProducer: args.security.metadataProducer,
    metadataSubject: args.security.metadataSubject,
    metadataTitle: args.security.metadataTitle,
    pdfPasswordDraft: args.security.pdfPasswordDraft,
    protectOwnerPassword: args.security.protectOwnerPassword,
    protectUserPassword: args.security.protectUserPassword,
    protectUserPasswordConfirm: args.security.protectUserPasswordConfirm,
    setDecryptPassword: args.security.setDecryptPassword,
    setMetadataAuthor: args.security.setMetadataAuthor,
    setMetadataCreator: args.security.setMetadataCreator,
    setMetadataKeywords: args.security.setMetadataKeywords,
    setMetadataProducer: args.security.setMetadataProducer,
    setMetadataSubject: args.security.setMetadataSubject,
    setMetadataTitle: args.security.setMetadataTitle,
    setPdfPasswordDraft: args.security.setPdfPasswordDraft,
    setProtectOwnerPassword: args.security.setProtectOwnerPassword,
    setProtectUserPassword: args.security.setProtectUserPassword,
    setProtectUserPasswordConfirm: args.security.setProtectUserPasswordConfirm,
    setShowDecryptModal: args.security.setShowDecryptModal,
    setShowMetadataModal: args.security.setShowMetadataModal,
    setShowProtectModal: args.security.setShowProtectModal,
    setShowSignModal: args.security.setShowSignModal,
    setSignCertPassword: args.security.setSignCertPassword,
    setSignCertPath: args.security.setSignCertPath,
    setSignLocation: args.security.setSignLocation,
    setSignReason: args.security.setSignReason,
    showDecryptModal: args.security.showDecryptModal,
    showMetadataModal: args.security.showMetadataModal,
    showPasswordModal: args.security.showPasswordModal,
    showProtectModal: args.security.showProtectModal,
    showSignModal: args.security.showSignModal,
    signCertPassword: args.security.signCertPassword,
    signCertPath: args.security.signCertPath,
    signLocation: args.security.signLocation,
    signReason: args.security.signReason,
  };
}
