import type { BuildAppModalCtxInputArgs } from './buildAppModalCtxArgs';

export function modalCtxAnnotFields(args: BuildAppModalCtxInputArgs) {
  return {
    closePageTextModal: args.pdfActions.closePageTextModal,
    confirmAddFormField: args.pdfActions.confirmAddFormField,
    confirmImageSource: args.pdfActions.confirmImageSource,
    editingTextIndex: args.annotation.editingTextIndex,
    exitNoteMode: args.pdfActions.exitNoteMode,
    imageSourceDraft: args.annotation.imageSourceDraft,
    newFormCheckboxChecked: args.annotation.newFormCheckboxChecked,
    newFormFieldKind: args.annotation.newFormFieldKind,
    newFormFieldName: args.annotation.newFormFieldName,
    newFormFieldOptions: args.annotation.newFormFieldOptions,
    newFormRadioGroup: args.annotation.newFormRadioGroup,
    newFormRadioOption: args.annotation.newFormRadioOption,
    noteDraft: args.annotation.noteDraft,
    pageTextDraft: args.annotation.pageTextDraft,
    pageTextEdits: args.annotation.pageTextEdits,
    pageTextFontSize: args.annotation.pageTextFontSize,
    pageVectorEdits: args.annotation.pageVectorEdits,
    removePageTextEdit: args.pdfActions.removePageTextEdit,
    removePageVectorEdit: args.pdfActions.removePageVectorEdit,
    setImageSourceDraft: args.annotation.setImageSourceDraft,
    setNewFormCheckboxChecked: args.annotation.setNewFormCheckboxChecked,
    setNewFormFieldKind: args.annotation.setNewFormFieldKind,
    setNewFormFieldName: args.annotation.setNewFormFieldName,
    setNewFormFieldOptions: args.annotation.setNewFormFieldOptions,
    setNewFormRadioGroup: args.annotation.setNewFormRadioGroup,
    setNewFormRadioOption: args.annotation.setNewFormRadioOption,
    setNoteDraft: args.annotation.setNoteDraft,
    setPageTextDraft: args.annotation.setPageTextDraft,
    setPageTextFontSize: args.annotation.setPageTextFontSize,
    setShowAddFormFieldModal: args.annotation.setShowAddFormFieldModal,
    setShowImageInsertModal: args.annotation.setShowImageInsertModal,
    setShowPageEditsModal: args.annotation.setShowPageEditsModal,
    showAddFormFieldModal: args.annotation.showAddFormFieldModal,
    showImageInsertModal: args.annotation.showImageInsertModal,
    showNoteModal: args.annotation.showNoteModal,
    showPageEditsModal: args.annotation.showPageEditsModal,
    showPageTextModal: args.annotation.showPageTextModal,
    startEditPageText: args.pdfActions.startEditPageText,
    submitPageText: args.pdfActions.submitPageText,
    submitTextNote: args.pdfActions.submitTextNote,
  };
}
