import type { BuildAppModalCtxSourceInput } from '../modals/buildAppModalCtxSource';
import { buildAppModalCtxSource } from '../modals/buildAppModalCtxSource';
import type { AppPdfActions } from '../app/useAppPdfActions';
import type { useAppModalState } from '../app/useAppModalState';
import type { useSecurityFormState } from '../app/useSecurityFormState';
import type { useAnnotationDraftState } from '../app/useAnnotationDraftState';
import type { useAppDocumentState } from '../app/useAppDocumentState';
import type { useAppPageRanges } from '../app/useAppPageRanges';
import type { useHelpChromeState } from '../app/useHelpChromeState';
import type { PdfBrowserEntry, PdfBrowserListing } from './PdfBrowserModal';
import type { PdfBrowserTarget } from '../app/types';
import { fileNameFromPath } from '../app/utils';

type ModalState = ReturnType<typeof useAppModalState>;
type SecurityState = ReturnType<typeof useSecurityFormState>;
type AnnotationState = ReturnType<typeof useAnnotationDraftState>;
type DocumentState = ReturnType<typeof useAppDocumentState>;
type PageRangesState = ReturnType<typeof useAppPageRanges>;
type HelpState = ReturnType<typeof useHelpChromeState>;

export type BrowserSlice = {
  showBrowserModal: boolean;
  setShowBrowserModal: (show: boolean) => void;
  browserListing: PdfBrowserListing | null;
  browserPathInput: string;
  setBrowserPathInput: (v: string) => void;
  loadPdfBrowser: () => void | Promise<void>;
  openPdfBrowser: (target: PdfBrowserTarget) => void;
  commitBrowserPath: () => void;
  handleBrowserEntryClick: (entry: PdfBrowserEntry) => Promise<void>;
};

export type SearchSlice = {
  showSearchModal: boolean;
  searchQuery: string;
  setSearchQuery: (q: string) => void;
  searchMatchCase: boolean;
  setSearchMatchCase: (v: boolean) => void;
  searchWholeWord: boolean;
  setSearchWholeWord: (v: boolean) => void;
  searchResults: unknown;
  searchResultIndex: number;
  searchInputRef: React.RefObject<HTMLInputElement | null>;
  closeSearchModal: () => void;
  runPdfSearch: () => void | Promise<void>;
  stepSearchMatch: (dir: 1 | -1) => void;
};

export type UnsavedSlice = {
  showUnsavedModal: boolean;
  resolveUnsaved: (choice: import('../modals/UnsavedChangesModal').UnsavedChoice) => void | Promise<void>;
};

export type TesseractSlice = {
  closeTesseractReminderModal: () => void;
};

export type LifecycleSlice = {
  handleOpenPdfPath: (path: string) => void | Promise<void>;
  handleOpenEncryptedPdf: () => void | Promise<void>;
  handleOpenRecentPdf: (path: string) => void | Promise<void>;
  loadPdfBrowser: () => void | Promise<void>;
  openPdfBrowser: (target: PdfBrowserTarget) => void;
};

export type RuntimeSlice = {
  showToast: (message: string, type?: 'success' | 'error') => void;
};

export type BuildAppModalCtxInputArgs = {
  modal: ModalState;
  security: SecurityState;
  annotation: AnnotationState;
  pageRanges: PageRangesState;
  doc: Pick<DocumentState, 'currentPage' | 'pageCount'>;
  browser: BrowserSlice;
  search: SearchSlice;
  unsaved: UnsavedSlice;
  tesseract: TesseractSlice;
  help: HelpState;
  lifecycle: LifecycleSlice;
  runtime: RuntimeSlice;
  pdfActions: AppPdfActions;
};

export function buildAppModalCtxInput(args: BuildAppModalCtxInputArgs) {
  return buildAppModalCtxSource({
    bookmarkAllPrefix: args.modal.bookmarkAllPrefix,
    bookmarkTitle: args.modal.bookmarkTitle,
    browserListing: args.browser.browserListing,
    browserPathInput: args.browser.browserPathInput,
    chooseExportPngOutputNative: args.pdfActions.chooseExportPngOutputNative,
    chooseExtractOutputNative: args.pdfActions.chooseExtractOutputNative,
    chooseInsertPdfNative: args.pdfActions.chooseInsertPdfNative,
    chooseMarkdownSaveAsNative: args.pdfActions.chooseMarkdownSaveAsNative,
    chooseMergePdfNative: args.pdfActions.chooseMergePdfNative,
    chooseOpenPdfNative: args.pdfActions.chooseOpenPdfNative,
    chooseSaveAsNative: args.pdfActions.chooseSaveAsNative,
    chooseSignCertNative: args.pdfActions.chooseSignCertNative,
    closePageTextModal: args.pdfActions.closePageTextModal,
    closePasswordModal: args.pdfActions.closePasswordModal,
    closeSearchModal: args.search.closeSearchModal,
    closeTesseractReminderModal: args.tesseract.closeTesseractReminderModal,
    commitBrowserPath: args.browser.commitBrowserPath,
    confirmAddFormField: args.pdfActions.confirmAddFormField,
    confirmImageSource: args.pdfActions.confirmImageSource,
    cropApplyAll: args.modal.cropApplyAll,
    cropMarginBottom: args.modal.cropMarginBottom,
    cropMarginLeft: args.modal.cropMarginLeft,
    cropMarginRight: args.modal.cropMarginRight,
    cropMarginTop: args.modal.cropMarginTop,
    cropRange: args.pageRanges.cropRange,
    currentPage: args.doc.currentPage,
    decryptPassword: args.security.decryptPassword,
    defaultExtractOutputPath: args.pdfActions.defaultExtractOutputPath,
    expandMarginBottom: args.modal.expandMarginBottom,
    expandMarginLeft: args.modal.expandMarginLeft,
    expandMarginRight: args.modal.expandMarginRight,
    expandMarginTop: args.modal.expandMarginTop,
    defaultImageExportOutput: args.pdfActions.defaultImageExportOutput,
    deleteNthValue: args.modal.deleteNthValue,
    deletePageInput: args.modal.deletePageInput,
    deleteRange: args.pageRanges.deleteRange,
    duplicateRange: args.pageRanges.duplicateRange,
    editingTextIndex: args.annotation.editingTextIndex,
    exitNoteMode: args.pdfActions.exitNoteMode,
    expandMarginsRange: args.pageRanges.expandMarginsRange,
    exportPagePdfPath: args.modal.exportPagePdfPath,
    exportPagesPdfOutputDir: args.modal.exportPagesPdfOutputDir,
    exportPagesPdfRange: args.pageRanges.exportPagesPdfRange,
    extractEvenOutputPath: args.modal.extractEvenOutputPath,
    extractOddOutputPath: args.modal.extractOddOutputPath,
    extractOutputPath: args.modal.extractOutputPath,
    extractRange: args.pageRanges.extractRange,
    fileNameFromPath: fileNameFromPath,
    flattenRange: args.pageRanges.flattenRange,
    handleAddBookmark: args.pdfActions.handleAddBookmark,
    handleAddPageBorder: args.pdfActions.handleAddPageBorder,
    handleAddPageBorderEvenPages: args.pdfActions.handleAddPageBorderEvenPages,
    handleAddPageBorderOddPages: args.pdfActions.handleAddPageBorderOddPages,
    handleAddPageFooter: args.pdfActions.handleAddPageFooter,
    handleAddPageFooterEvenPages: args.pdfActions.handleAddPageFooterEvenPages,
    handleAddPageFooterOddPages: args.pdfActions.handleAddPageFooterOddPages,
    handleAddPageHeader: args.pdfActions.handleAddPageHeader,
    handleAddPageHeaderEvenPages: args.pdfActions.handleAddPageHeaderEvenPages,
    handleAddPageHeaderOddPages: args.pdfActions.handleAddPageHeaderOddPages,
    handleAddPageNumbers: args.pdfActions.handleAddPageNumbers,
    handleAddPageNumbersEvenPages: args.pdfActions.handleAddPageNumbersEvenPages,
    handleAddPageNumbersOddPages: args.pdfActions.handleAddPageNumbersOddPages,
    handleAddWatermark: args.pdfActions.handleAddWatermark,
    handleAddWatermarkEvenPages: args.pdfActions.handleAddWatermarkEvenPages,
    handleAddWatermarkOddPages: args.pdfActions.handleAddWatermarkOddPages,
    handleBookmarkAllPages: args.pdfActions.handleBookmarkAllPages,
    handleBookmarkEvenPages: args.pdfActions.handleBookmarkEvenPages,
    handleBookmarkOddPages: args.pdfActions.handleBookmarkOddPages,
    handleBrowserEntryClick: args.browser.handleBrowserEntryClick,
    handleClearAllCrops: args.pdfActions.handleClearAllCrops,
    handleClearCropEvenPages: args.pdfActions.handleClearCropEvenPages,
    handleClearCropOddPages: args.pdfActions.handleClearCropOddPages,
    handleClearPageCrop: args.pdfActions.handleClearPageCrop,
    handleClearPdfMetadata: args.pdfActions.handleClearPdfMetadata,
    handleCopySummary: args.pdfActions.handleCopySummary,
    handleCropEvenPages: args.pdfActions.handleCropEvenPages,
    handleCropOddPages: args.pdfActions.handleCropOddPages,
    handleCropPage: args.pdfActions.handleCropPage,
    handleCropPageRange: args.pdfActions.handleCropPageRange,
    handleDeleteEveryNthPage: args.pdfActions.handleDeleteEveryNthPage,
    handleDeletePage: args.pdfActions.handleDeletePage,
    handleDeletePageRange: args.pdfActions.handleDeletePageRange,
    handleDuplicatePageRange: args.pdfActions.handleDuplicatePageRange,
    handleDuplicatePageRangeBefore: args.pdfActions.handleDuplicatePageRangeBefore,
    handleDuplicatePageRangeToEnd: args.pdfActions.handleDuplicatePageRangeToEnd,
    handleDuplicatePageRangeToStart: args.pdfActions.handleDuplicatePageRangeToStart,
    handleExpandEvenPages: args.pdfActions.handleExpandEvenPages,
    handleExpandOddPages: args.pdfActions.handleExpandOddPages,
    handleExpandPageMargins: args.pdfActions.handleExpandPageMargins,
    handleExportEvenPagesAsPdf: args.pdfActions.handleExportEvenPagesAsPdf,
    handleExportEvenPagesImage: args.pdfActions.handleExportEvenPagesImage,
    handleExportOddPagesAsPdf: args.pdfActions.handleExportOddPagesAsPdf,
    handleExportOddPagesImage: args.pdfActions.handleExportOddPagesImage,
    handleExportPagePdf: args.pdfActions.handleExportPagePdf,
    handleExportPagesPdf: args.pdfActions.handleExportPagesPdf,
    handleExportPng: args.pdfActions.handleExportPng,
    handleExtractEvenPages: args.pdfActions.handleExtractEvenPages,
    handleExtractOddPages: args.pdfActions.handleExtractOddPages,
    handleExtractPdf: args.pdfActions.handleExtractPdf,
    handleFlattenAnnotations: args.pdfActions.handleFlattenAnnotations,
    handleInsertBlankPages: args.pdfActions.handleInsertBlankPages,
    handleInsertImagePage: args.pdfActions.handleInsertImagePage,
    handleInsertPdf: args.pdfActions.handleInsertPdf,
    handleInterleavePdf: args.pdfActions.handleInterleavePdf,
    handleInterleaveSourcePathChange: args.pdfActions.handleInterleaveSourcePathChange,
    handleKeepPageRange: args.pdfActions.handleKeepPageRange,
    handleMarkdownSaveAs: args.pdfActions.handleMarkdownSaveAs,
    handleMergePdf: args.pdfActions.handleMergePdf,
    handleMovePageRange: args.pdfActions.handleMovePageRange,
    handleMovePageRangeToEnd: args.pdfActions.handleMovePageRangeToEnd,
    handleMovePageRangeToStart: args.pdfActions.handleMovePageRangeToStart,
    handleOpenEncryptedPdf: args.lifecycle.handleOpenEncryptedPdf,
    handleOpenPdfPath: args.lifecycle.handleOpenPdfPath,
    handleOpenRecentPdf: args.lifecycle.handleOpenRecentPdf,
    handleParityRangeAction: args.pdfActions.handleParityRangeAction,
    handlePrependPdf: args.pdfActions.handlePrependPdf,
    handlePrependSourcePathChange: args.pdfActions.handlePrependSourcePathChange,
    handleProtectPdf: args.pdfActions.handleProtectPdf,
    handleRemovePdfPassword: args.pdfActions.handleRemovePdfPassword,
    handleRenameBookmark: args.pdfActions.handleRenameBookmark,
    handleReplacePage: args.pdfActions.handleReplacePage,
    handleReplaceSourcePathChange: args.pdfActions.handleReplaceSourcePathChange,
    handleResetRotationRange: args.pdfActions.handleResetRotationRange,
    handleReversePageRange: args.pdfActions.handleReversePageRange,
    handleRotatePage180Range: args.pdfActions.handleRotatePage180Range,
    handleRotatePageRange: args.pdfActions.handleRotatePageRange,
    handleSaveAs: args.pdfActions.handleSaveAs,
    handleSaveMetadata: args.pdfActions.handleSaveMetadata,
    handleSaveSummary: args.pdfActions.handleSaveSummary,
    handleSetPageSize: args.pdfActions.handleSetPageSize,
    handleSetPageSizeEvenPages: args.pdfActions.handleSetPageSizeEvenPages,
    handleSetPageSizeOddPages: args.pdfActions.handleSetPageSizeOddPages,
    handleShrinkEvenPages: args.pdfActions.handleShrinkEvenPages,
    handleShrinkOddPages: args.pdfActions.handleShrinkOddPages,
    handleShrinkPageMargins: args.pdfActions.handleShrinkPageMargins,
    handleSignPdf: args.pdfActions.handleSignPdf,
    handleSplitEveryN: args.pdfActions.handleSplitEveryN,
    handleSplitPdf: args.pdfActions.handleSplitPdf,
    handleSplitPdfAtPage: args.pdfActions.handleSplitPdfAtPage,
    handleSwapPages: args.pdfActions.handleSwapPages,
    imageExportFormat: args.modal.imageExportFormat,
    imageSourceDraft: args.annotation.imageSourceDraft,
    insertAtPage: args.modal.insertAtPage,
    insertBlankAtIndex: args.modal.insertBlankAtIndex,
    insertBlankCount: args.modal.insertBlankCount,
    insertFilePath: args.modal.insertFilePath,
    insertImageAtIndex: args.modal.insertImageAtIndex,
    insertImagePagePath: args.modal.insertImagePagePath,
    insertRange: args.pageRanges.insertRange,
    insertSourcePageCount: args.modal.insertSourcePageCount,
    interleaveFilePath: args.modal.interleaveFilePath,
    interleaveRange: args.pageRanges.interleaveRange,
    interleaveSourcePageCount: args.modal.interleaveSourcePageCount,
    keepRange: args.pageRanges.keepRange,
    loadPdfBrowser: args.browser.loadPdfBrowser,
    markdownSaveAsPath: args.modal.markdownSaveAsPath,
    mergeFilePath: args.modal.mergeFilePath,
    mergeRange: args.pageRanges.mergeRange,
    mergeSourcePageCount: args.modal.mergeSourcePageCount,
    metadataAuthor: args.security.metadataAuthor,
    metadataCreationDate: args.security.metadataCreationDate,
    metadataCreator: args.security.metadataCreator,
    metadataKeywords: args.security.metadataKeywords,
    metadataModDate: args.security.metadataModDate,
    metadataProducer: args.security.metadataProducer,
    metadataSubject: args.security.metadataSubject,
    metadataTitle: args.security.metadataTitle,
    moveRange: args.pageRanges.moveRange,
    moveRangeToIndex: args.modal.moveRangeToIndex,
    nativeDialogs: args.modal.nativeDialogs,
    newFormCheckboxChecked: args.annotation.newFormCheckboxChecked,
    newFormFieldKind: args.annotation.newFormFieldKind,
    newFormFieldName: args.annotation.newFormFieldName,
    newFormFieldOptions: args.annotation.newFormFieldOptions,
    newFormRadioGroup: args.annotation.newFormRadioGroup,
    newFormRadioOption: args.annotation.newFormRadioOption,
    noteDraft: args.annotation.noteDraft,
    openFilePath: args.modal.openFilePath,
    openPdfBrowser: args.browser.openPdfBrowser,
    pageBorderInset: args.modal.pageBorderInset,
    pageBorderRange: args.pageRanges.pageBorderRange,
    pageCount: args.doc.pageCount,
    pageFooterRange: args.pageRanges.pageFooterRange,
    pageFooterText: args.modal.pageFooterText,
    pageHeaderRange: args.pageRanges.pageHeaderRange,
    pageHeaderText: args.modal.pageHeaderText,
    pageNumbersPrefix: args.modal.pageNumbersPrefix,
    pageNumbersRange: args.pageRanges.pageNumbersRange,
    pageSizePreset: args.modal.pageSizePreset,
    pageSizeRange: args.pageRanges.pageSizeRange,
    pageTextDraft: args.annotation.pageTextDraft,
    pageTextEdits: args.annotation.pageTextEdits,
    pageTextFontSize: args.annotation.pageTextFontSize,
    pageVectorEdits: args.annotation.pageVectorEdits,
    parityRange: args.pageRanges.parityRange,
    parityRangeCommand: args.modal.parityRangeCommand,
    parityRangeOutputPath: args.modal.parityRangeOutputPath,
    pdfPasswordDraft: args.security.pdfPasswordDraft,
    pdfSummary: args.modal.pdfSummary,
    pngExportOutputPath: args.modal.pngExportOutputPath,
    pngExportRange: args.pageRanges.pngExportRange,
    prependFilePath: args.modal.prependFilePath,
    prependRange: args.pageRanges.prependRange,
    prependSourcePageCount: args.modal.prependSourcePageCount,
    protectOwnerPassword: args.security.protectOwnerPassword,
    protectUserPassword: args.security.protectUserPassword,
    protectUserPasswordConfirm: args.security.protectUserPasswordConfirm,
    recentPdfs: args.modal.recentPdfs,
    removePageTextEdit: args.pdfActions.removePageTextEdit,
    removePageVectorEdit: args.pdfActions.removePageVectorEdit,
    renameBookmarkTitle: args.modal.renameBookmarkTitle,
    replaceSourcePage: args.modal.replaceSourcePage,
    replaceSourcePageCount: args.modal.replaceSourcePageCount,
    replaceSourcePath: args.modal.replaceSourcePath,
    resolveUnsaved: args.unsaved.resolveUnsaved,
    reverseRange: args.pageRanges.reverseRange,
    rotateRange: args.pageRanges.rotateRange,
    runPdfSearch: args.search.runPdfSearch,
    saveAsPath: args.modal.saveAsPath,
    searchInputRef: args.search.searchInputRef,
    searchMatchCase: args.search.searchMatchCase,
    searchQuery: args.search.searchQuery,
    searchResultIndex: args.search.searchResultIndex,
    searchResults: args.search.searchResults,
    searchWholeWord: args.search.searchWholeWord,
    setBookmarkAllPrefix: args.modal.setBookmarkAllPrefix,
    setBookmarkTitle: args.modal.setBookmarkTitle,
    setBrowserPathInput: args.browser.setBrowserPathInput,
    setCropApplyAll: args.modal.setCropApplyAll,
    setCropMarginBottom: args.modal.setCropMarginBottom,
    setCropMarginLeft: args.modal.setCropMarginLeft,
    setCropMarginRight: args.modal.setCropMarginRight,
    setCropMarginTop: args.modal.setCropMarginTop,
    setDecryptPassword: args.security.setDecryptPassword,
    setDeleteNthValue: args.modal.setDeleteNthValue,
    setDeletePageInput: args.modal.setDeletePageInput,
    setExpandMarginBottom: args.modal.setExpandMarginBottom,
    setExpandMarginLeft: args.modal.setExpandMarginLeft,
    setExpandMarginRight: args.modal.setExpandMarginRight,
    setExpandMarginTop: args.modal.setExpandMarginTop,
    setExportPagePdfPath: args.modal.setExportPagePdfPath,
    setExportPagesPdfOutputDir: args.modal.setExportPagesPdfOutputDir,
    setExtractEvenOutputPath: args.modal.setExtractEvenOutputPath,
    setExtractOddOutputPath: args.modal.setExtractOddOutputPath,
    setExtractOutputPath: args.modal.setExtractOutputPath,
    setImageExportFormat: args.modal.setImageExportFormat,
    setImageSourceDraft: args.annotation.setImageSourceDraft,
    setInsertAtPage: args.modal.setInsertAtPage,
    setInsertBlankAtIndex: args.modal.setInsertBlankAtIndex,
    setInsertBlankCount: args.modal.setInsertBlankCount,
    setInsertFilePath: args.modal.setInsertFilePath,
    setInsertImageAtIndex: args.modal.setInsertImageAtIndex,
    setInsertImagePagePath: args.modal.setInsertImagePagePath,
    setMarkdownSaveAsPath: args.modal.setMarkdownSaveAsPath,
    setMergeFilePath: args.modal.setMergeFilePath,
    setMetadataAuthor: args.security.setMetadataAuthor,
    setMetadataCreator: args.security.setMetadataCreator,
    setMetadataKeywords: args.security.setMetadataKeywords,
    setMetadataProducer: args.security.setMetadataProducer,
    setMetadataSubject: args.security.setMetadataSubject,
    setMetadataTitle: args.security.setMetadataTitle,
    setMoveRangeToIndex: args.modal.setMoveRangeToIndex,
    setNewFormCheckboxChecked: args.annotation.setNewFormCheckboxChecked,
    setNewFormFieldKind: args.annotation.setNewFormFieldKind,
    setNewFormFieldName: args.annotation.setNewFormFieldName,
    setNewFormFieldOptions: args.annotation.setNewFormFieldOptions,
    setNewFormRadioGroup: args.annotation.setNewFormRadioGroup,
    setNewFormRadioOption: args.annotation.setNewFormRadioOption,
    setNoteDraft: args.annotation.setNoteDraft,
    setOpenFilePath: args.modal.setOpenFilePath,
    setPageBorderInset: args.modal.setPageBorderInset,
    setPageFooterText: args.modal.setPageFooterText,
    setPageHeaderText: args.modal.setPageHeaderText,
    setPageNumbersPrefix: args.modal.setPageNumbersPrefix,
    setPageSizePreset: args.modal.setPageSizePreset,
    setPageTextDraft: args.annotation.setPageTextDraft,
    setPageTextFontSize: args.annotation.setPageTextFontSize,
    setParityRangeCommand: args.modal.setParityRangeCommand,
    setParityRangeOutputPath: args.modal.setParityRangeOutputPath,
    setPdfPasswordDraft: args.security.setPdfPasswordDraft,
    setPngExportOutputPath: args.modal.setPngExportOutputPath,
    setProtectOwnerPassword: args.security.setProtectOwnerPassword,
    setProtectUserPassword: args.security.setProtectUserPassword,
    setProtectUserPasswordConfirm: args.security.setProtectUserPasswordConfirm,
    setRenameBookmarkTitle: args.modal.setRenameBookmarkTitle,
    setReplaceSourcePage: args.modal.setReplaceSourcePage,
    setSaveAsPath: args.modal.setSaveAsPath,
    setSearchMatchCase: args.search.setSearchMatchCase,
    setSearchQuery: args.search.setSearchQuery,
    setSearchWholeWord: args.search.setSearchWholeWord,
    setShowAddBookmarkModal: args.modal.setShowAddBookmarkModal,
    setShowAddFormFieldModal: args.annotation.setShowAddFormFieldModal,
    setShowBookmarkAllModal: args.modal.setShowBookmarkAllModal,
    setShowBrowserModal: args.browser.setShowBrowserModal,
    setShowCropModal: args.modal.setShowCropModal,
    setShowCropRangeModal: args.modal.setShowCropRangeModal,
    setShowDecryptModal: args.security.setShowDecryptModal,
    setShowDeleteModal: args.modal.setShowDeleteModal,
    setShowDeleteNthModal: args.modal.setShowDeleteNthModal,
    setShowDeleteRangeModal: args.modal.setShowDeleteRangeModal,
    setShowDuplicateRangeModal: args.modal.setShowDuplicateRangeModal,
    setShowExpandMarginsModal: args.modal.setShowExpandMarginsModal,
    setShowExportPagePdfModal: args.modal.setShowExportPagePdfModal,
    setShowExportPagesPdfModal: args.modal.setShowExportPagesPdfModal,
    setShowExportPngModal: args.modal.setShowExportPngModal,
    setShowExtractEvenModal: args.modal.setShowExtractEvenModal,
    setShowExtractModal: args.modal.setShowExtractModal,
    setShowExtractOddModal: args.modal.setShowExtractOddModal,
    setShowFlattenModal: args.modal.setShowFlattenModal,
    setShowImageInsertModal: args.annotation.setShowImageInsertModal,
    setShowInsertBlankPagesModal: args.modal.setShowInsertBlankPagesModal,
    setShowInsertImagePageModal: args.modal.setShowInsertImagePageModal,
    setShowInsertModal: args.modal.setShowInsertModal,
    setShowInterleaveModal: args.modal.setShowInterleaveModal,
    setShowKeepRangeModal: args.modal.setShowKeepRangeModal,
    setShowMarkdownSaveAsModal: args.modal.setShowMarkdownSaveAsModal,
    setShowMergeModal: args.modal.setShowMergeModal,
    setShowMetadataModal: args.security.setShowMetadataModal,
    setShowMoveRangeModal: args.modal.setShowMoveRangeModal,
    setShowOpenModal: args.modal.setShowOpenModal,
    setShowPageBorderModal: args.modal.setShowPageBorderModal,
    setShowPageEditsModal: args.annotation.setShowPageEditsModal,
    setShowPageFooterModal: args.modal.setShowPageFooterModal,
    setShowPageHeaderModal: args.modal.setShowPageHeaderModal,
    setShowPageNumbersModal: args.modal.setShowPageNumbersModal,
    setShowPageSizeModal: args.modal.setShowPageSizeModal,
    setShowParityRangeModal: args.modal.setShowParityRangeModal,
    setShowPrependModal: args.modal.setShowPrependModal,
    setShowProtectModal: args.security.setShowProtectModal,
    setShowRenameBookmarkModal: args.modal.setShowRenameBookmarkModal,
    setShowReplacePageModal: args.modal.setShowReplacePageModal,
    setShowReverseRangeModal: args.modal.setShowReverseRangeModal,
    setShowRotateRangeModal: args.modal.setShowRotateRangeModal,
    setShowSaveAsModal: args.modal.setShowSaveAsModal,
    setShowShrinkMarginsModal: args.modal.setShowShrinkMarginsModal,
    setShowSignModal: args.security.setShowSignModal,
    setShowSplitAtModal: args.modal.setShowSplitAtModal,
    setShowSplitEveryModal: args.modal.setShowSplitEveryModal,
    setShowSplitModal: args.modal.setShowSplitModal,
    setShowSummaryModal: args.modal.setShowSummaryModal,
    setShowSwapPagesModal: args.modal.setShowSwapPagesModal,
    setShowWatermarkModal: args.modal.setShowWatermarkModal,
    setShrinkMarginBottom: args.modal.setShrinkMarginBottom,
    setShrinkMarginLeft: args.modal.setShrinkMarginLeft,
    setShrinkMarginRight: args.modal.setShrinkMarginRight,
    setShrinkMarginTop: args.modal.setShrinkMarginTop,
    setSignCertPassword: args.security.setSignCertPassword,
    setSignCertPath: args.security.setSignCertPath,
    setSignLocation: args.security.setSignLocation,
    setSignReason: args.security.setSignReason,
    setSplitAtPage: args.modal.setSplitAtPage,
    setSplitEveryN: args.modal.setSplitEveryN,
    setSplitRanges: args.modal.setSplitRanges,
    setSwapPageA: args.modal.setSwapPageA,
    setSwapPageB: args.modal.setSwapPageB,
    setTesseractDoNotRemind: args.help.setTesseractDoNotRemind,
    setWatermarkText: args.modal.setWatermarkText,
    showAddBookmarkModal: args.modal.showAddBookmarkModal,
    showAddFormFieldModal: args.annotation.showAddFormFieldModal,
    showBookmarkAllModal: args.modal.showBookmarkAllModal,
    showBrowserModal: args.browser.showBrowserModal,
    showCropModal: args.modal.showCropModal,
    showCropRangeModal: args.modal.showCropRangeModal,
    showDecryptModal: args.security.showDecryptModal,
    showDeleteModal: args.modal.showDeleteModal,
    showDeleteNthModal: args.modal.showDeleteNthModal,
    showDeleteRangeModal: args.modal.showDeleteRangeModal,
    showDuplicateRangeModal: args.modal.showDuplicateRangeModal,
    showExpandMarginsModal: args.modal.showExpandMarginsModal,
    showExportPagePdfModal: args.modal.showExportPagePdfModal,
    showExportPagesPdfModal: args.modal.showExportPagesPdfModal,
    showExportPngModal: args.modal.showExportPngModal,
    showExtractEvenModal: args.modal.showExtractEvenModal,
    showExtractModal: args.modal.showExtractModal,
    showExtractOddModal: args.modal.showExtractOddModal,
    showFlattenModal: args.modal.showFlattenModal,
    showImageInsertModal: args.annotation.showImageInsertModal,
    showInsertBlankPagesModal: args.modal.showInsertBlankPagesModal,
    showInsertImagePageModal: args.modal.showInsertImagePageModal,
    showInsertModal: args.modal.showInsertModal,
    showInterleaveModal: args.modal.showInterleaveModal,
    showKeepRangeModal: args.modal.showKeepRangeModal,
    showMarkdownSaveAsModal: args.modal.showMarkdownSaveAsModal,
    showMergeModal: args.modal.showMergeModal,
    showMetadataModal: args.security.showMetadataModal,
    showMoveRangeModal: args.modal.showMoveRangeModal,
    showNoteModal: args.annotation.showNoteModal,
    showOpenModal: args.modal.showOpenModal,
    showPageBorderModal: args.modal.showPageBorderModal,
    showPageEditsModal: args.annotation.showPageEditsModal,
    showPageFooterModal: args.modal.showPageFooterModal,
    showPageHeaderModal: args.modal.showPageHeaderModal,
    showPageNumbersModal: args.modal.showPageNumbersModal,
    showPageSizeModal: args.modal.showPageSizeModal,
    showPageTextModal: args.annotation.showPageTextModal,
    showParityRangeModal: args.modal.showParityRangeModal,
    showPasswordModal: args.security.showPasswordModal,
    showPrependModal: args.modal.showPrependModal,
    showProtectModal: args.security.showProtectModal,
    showRenameBookmarkModal: args.modal.showRenameBookmarkModal,
    showReplacePageModal: args.modal.showReplacePageModal,
    showReverseRangeModal: args.modal.showReverseRangeModal,
    showRotateRangeModal: args.modal.showRotateRangeModal,
    showSaveAsModal: args.modal.showSaveAsModal,
    showSearchModal: args.search.showSearchModal,
    showShrinkMarginsModal: args.modal.showShrinkMarginsModal,
    showSignModal: args.security.showSignModal,
    showSplitAtModal: args.modal.showSplitAtModal,
    showSplitEveryModal: args.modal.showSplitEveryModal,
    showSplitModal: args.modal.showSplitModal,
    showSummaryModal: args.modal.showSummaryModal,
    showSwapPagesModal: args.modal.showSwapPagesModal,
    showTesseractModal: args.help.showTesseractModal,
    showToast: args.runtime.showToast,
    showUnsavedModal: args.unsaved.showUnsavedModal,
    showWatermarkModal: args.modal.showWatermarkModal,
    shrinkMarginBottom: args.modal.shrinkMarginBottom,
    shrinkMarginLeft: args.modal.shrinkMarginLeft,
    shrinkMarginRight: args.modal.shrinkMarginRight,
    shrinkMarginTop: args.modal.shrinkMarginTop,
    shrinkMarginsRange: args.pageRanges.shrinkMarginsRange,
    signCertPassword: args.security.signCertPassword,
    signCertPath: args.security.signCertPath,
    signLocation: args.security.signLocation,
    signReason: args.security.signReason,
    splitAtPage: args.modal.splitAtPage,
    splitEveryN: args.modal.splitEveryN,
    splitRanges: args.modal.splitRanges,
    startEditPageText: args.pdfActions.startEditPageText,
    stepSearchMatch: args.search.stepSearchMatch,
    submitPageText: args.pdfActions.submitPageText,
    submitTextNote: args.pdfActions.submitTextNote,
    swapPageA: args.modal.swapPageA,
    swapPageB: args.modal.swapPageB,
    tesseractDoNotRemind: args.help.tesseractDoNotRemind,
    tesseractInstallGuide: args.help.tesseractInstallGuide,
    watermarkRange: args.pageRanges.watermarkRange,
    watermarkText: args.modal.watermarkText,
    pageSizes: args.modal.pageSizes,
  } satisfies BuildAppModalCtxSourceInput);
}
