import type { AppMenuContextSource } from './buildAppMenuContext';
import type { ViewMode } from '../app/types';
import { menuSourceDocAnnotFields } from './buildAppMenuSourceDocAnnotFields';
import { menuSourcePagesFields } from './buildAppMenuSourcePagesFields';

type VoidHandler = () => void | Promise<void>;
type SortHandler = (desc: boolean) => void | Promise<void>;

/** Inputs from App hooks/state before menu void-wrapping in buildAppMenuContext. */
export type BuildAppMenuSourceInput = {
  filePath: string;
  isDirty: boolean;
  canUndo: boolean;
  canRedo: boolean;
  pageCount: number | null;
  currentPage: number;
  viewMode: ViewMode;
  highlightMode: boolean;
  noteMode: boolean;
  drawMode: boolean;
  shapeMode: boolean;
  stampMode: boolean;
  redactMode: boolean;
  imageInsertMode: boolean;
  textEditMode: boolean;
  vectorEditMode: boolean;
  showFormsPanel: boolean;
  showBookmarksPanel: boolean;
  showSignaturesPanel: boolean;
  ocrAvailable: boolean | null;
  guardUnsaved: (action: () => void) => void;
  closePdf: () => void;
  setViewMode: (mode: ViewMode) => void;
  setShowBookmarksPanel: (fn: (prev: boolean) => boolean) => void;
  setShowPageEditsModal: (open: boolean) => void;
  setShowShortcutsHelp: (open: boolean) => void;
  setShowLicenses: (open: boolean) => void;
  setShowCredits: (open: boolean) => void;
  setShowAbout: (open: boolean) => void;
  setShowCommandPalette: (open: boolean) => void;
  openTesseractGuide: () => void;
  openPdf: () => void;
  handleSave: VoidHandler;
  openSaveAs: () => void;
  undo: VoidHandler;
  redo: VoidHandler;
  handlePrint: VoidHandler;
  openSearchModal: () => void;
  handleRotatePage: VoidHandler;
  handleRotatePageCcw: VoidHandler;
  handleResetPageRotation: VoidHandler;
  handleRotatePage180: VoidHandler;
  handleRotateAllPages: VoidHandler;
  handleRotateAllPagesCcw: VoidHandler;
  handleRotateAllPages180: VoidHandler;
  handleRotateOddPages: VoidHandler;
  handleRotateEvenPages: VoidHandler;
  handleRotateOddPagesCcw: VoidHandler;
  handleRotateEvenPagesCcw: VoidHandler;
  handleRotate180OddPages: VoidHandler;
  handleRotate180EvenPages: VoidHandler;
  handleResetRotationOddPages: VoidHandler;
  handleResetRotationEvenPages: VoidHandler;
  handleResetAllRotations: VoidHandler;
  openRotateRangeModal: () => void;
  handleDuplicatePage: VoidHandler;
  handleDuplicatePageBefore: VoidHandler;
  openDuplicateRangeModal: () => void;
  openParityRangeModal: () => void;
  openMoveRangeModal: () => void;
  openKeepRangeModal: () => void;
  handleKeepOddPages: VoidHandler;
  handleKeepEvenPages: VoidHandler;
  handleDeleteOddPages: VoidHandler;
  handleDeleteEvenPages: VoidHandler;
  handleAddBlankPage: VoidHandler;
  handleAddBlankPageBefore: VoidHandler;
  openInsertBlankPagesModal: () => void;
  handleInsertBlankBetweenPages: VoidHandler;
  handleInsertBlankBeforeOddPages: VoidHandler;
  handleInsertBlankBeforeEvenPages: VoidHandler;
  handleInsertBlankAfterOddPages: VoidHandler;
  handleInsertBlankAfterEvenPages: VoidHandler;
  handleMovePageToFirst: VoidHandler;
  handleMovePageToLast: VoidHandler;
  handleMovePageUp: VoidHandler;
  handleMovePageDown: VoidHandler;
  openSwapPagesModal: () => void;
  handleReversePages: VoidHandler;
  openReverseRangeModal: () => void;
  handleReverseOddPages: VoidHandler;
  handleReverseEvenPages: VoidHandler;
  handleMoveOddPagesToStart: VoidHandler;
  handleMoveEvenPagesToStart: VoidHandler;
  handleMoveOddPagesToEnd: VoidHandler;
  handleMoveEvenPagesToEnd: VoidHandler;
  handleSplitOddEven: VoidHandler;
  handleDuplicateAllPages: VoidHandler;
  handleDuplicatePageToEnd: VoidHandler;
  handleDuplicateOddPages: VoidHandler;
  handleDuplicateEvenPages: VoidHandler;
  handleDuplicateOddPagesBefore: VoidHandler;
  handleDuplicateEvenPagesBefore: VoidHandler;
  handleDuplicateOddPagesToEnd: VoidHandler;
  handleDuplicateEvenPagesToEnd: VoidHandler;
  handleDuplicateOddPagesToStart: VoidHandler;
  handleDuplicateEvenPagesToStart: VoidHandler;
  openDeleteModal: () => void;
  openDeleteRangeModal: () => void;
  openDeleteNthModal: () => void;
  openInsertModal: () => void;
  openMergeModal: () => void;
  openInterleaveModal: () => void;
  openPrependModal: () => void;
  openReplacePageModal: () => void;
  openSplitModal: () => void;
  openSplitAtModal: () => void;
  openSplitEveryModal: () => void;
  openExtractModal: () => void;
  openExtractOddModal: () => void;
  openExtractEvenModal: () => void;
  toggleMarkdownView: VoidHandler;
  handleOptimizePdf: VoidHandler;
  openExportPngModal: () => void;
  openExportPagePdfModal: () => void;
  openExportPagesPdfModal: () => void;
  openInsertImagePageModal: () => void;
  openPageNumbersModal: () => void;
  openPageHeaderModal: () => void;
  openPageFooterModal: () => void;
  openPageSizeModal: () => void;
  openWatermarkModal: () => void;
  openCropModal: () => void;
  openCropRangeModal: () => void;
  handleCropOddPages: VoidHandler;
  handleCropEvenPages: VoidHandler;
  openExpandMarginsModal: () => void;
  openShrinkMarginsModal: () => void;
  openPageBorderModal: () => void;
  openFlattenModal: () => void;
  handleFlattenAllAnnotations: VoidHandler;
  handleFlattenOddPages: VoidHandler;
  handleFlattenEvenPages: VoidHandler;
  handleSortPagesBySize: SortHandler;
  handleSortOddPagesBySize: SortHandler;
  handleSortEvenPagesBySize: SortHandler;
  handleSortPagesByRotation: SortHandler;
  handleSortOddPagesByRotation: SortHandler;
  handleSortEvenPagesByRotation: SortHandler;
  openMetadataModal: VoidHandler;
  handleSummarizePdf: VoidHandler;
  openProtectModal: () => void;
  openDecryptModal: () => void;
  openSignModal: () => void;
  toggleSignaturesPanel: () => void;
  toggleRedactMode: () => void;
  toggleHighlightMode: () => void;
  toggleNoteMode: () => void;
  toggleDrawMode: () => void;
  toggleShapeMode: () => void;
  toggleStampMode: () => void;
  toggleImageInsertMode: () => void;
  toggleTextEditMode: () => void;
  toggleVectorEditMode: () => void;
  toggleFormsPanel: () => void;
};

export function buildAppMenuSource(input: BuildAppMenuSourceInput): AppMenuContextSource {
  return {
    ...menuSourceDocAnnotFields(input),
    ...menuSourcePagesFields(input),
  };
}
