import type { AppMenuContextSource } from './buildAppMenuContext';
import type { BuildAppMenuSourceInput } from './buildAppMenuSource';

export function menuSourcePagesFields(input: BuildAppMenuSourceInput): Pick<
  AppMenuContextSource,
  | 'handleRotatePage'
  | 'handleRotatePageCcw'
  | 'handleResetPageRotation'
  | 'handleRotatePage180'
  | 'handleRotateAllPages'
  | 'handleRotateAllPagesCcw'
  | 'handleRotateAllPages180'
  | 'handleRotateOddPages'
  | 'handleRotateEvenPages'
  | 'handleRotateOddPagesCcw'
  | 'handleRotateEvenPagesCcw'
  | 'handleRotate180OddPages'
  | 'handleRotate180EvenPages'
  | 'handleResetRotationOddPages'
  | 'handleResetRotationEvenPages'
  | 'handleResetAllRotations'
  | 'openRotateRangeModal'
  | 'handleDuplicatePage'
  | 'handleDuplicatePageBefore'
  | 'openDuplicateRangeModal'
  | 'openParityRangeModal'
  | 'openMoveRangeModal'
  | 'openKeepRangeModal'
  | 'handleKeepOddPages'
  | 'handleKeepEvenPages'
  | 'handleDeleteOddPages'
  | 'handleDeleteEvenPages'
  | 'handleAddBlankPage'
  | 'handleAddBlankPageBefore'
  | 'openInsertBlankPagesModal'
  | 'handleInsertBlankBetweenPages'
  | 'handleInsertBlankBeforeOddPages'
  | 'handleInsertBlankBeforeEvenPages'
  | 'handleInsertBlankAfterOddPages'
  | 'handleInsertBlankAfterEvenPages'
  | 'handleMovePageToFirst'
  | 'handleMovePageToLast'
  | 'handleMovePageUp'
  | 'handleMovePageDown'
  | 'openSwapPagesModal'
  | 'handleReversePages'
  | 'openReverseRangeModal'
  | 'handleReverseOddPages'
  | 'handleReverseEvenPages'
  | 'handleMoveOddPagesToStart'
  | 'handleMoveEvenPagesToStart'
  | 'handleMoveOddPagesToEnd'
  | 'handleMoveEvenPagesToEnd'
  | 'handleSplitOddEven'
  | 'handleDuplicateAllPages'
  | 'handleDuplicatePageToEnd'
  | 'handleDuplicateOddPages'
  | 'handleDuplicateEvenPages'
  | 'handleDuplicateOddPagesBefore'
  | 'handleDuplicateEvenPagesBefore'
  | 'handleDuplicateOddPagesToEnd'
  | 'handleDuplicateEvenPagesToEnd'
  | 'handleDuplicateOddPagesToStart'
  | 'handleDuplicateEvenPagesToStart'
  | 'openDeleteModal'
  | 'openDeleteRangeModal'
  | 'openDeleteNthModal'
  | 'openInsertModal'
  | 'openMergeModal'
  | 'openInterleaveModal'
  | 'openPrependModal'
  | 'openReplacePageModal'
  | 'openSplitModal'
  | 'openSplitAtModal'
  | 'openSplitEveryModal'
  | 'openExtractModal'
  | 'openExtractOddModal'
  | 'openExtractEvenModal'
  | 'handleSortPagesBySize'
  | 'handleSortOddPagesBySize'
  | 'handleSortEvenPagesBySize'
  | 'handleSortPagesByRotation'
  | 'handleSortOddPagesByRotation'
  | 'handleSortEvenPagesByRotation'
> {
  return {
    handleRotatePage: input.handleRotatePage,
    handleRotatePageCcw: input.handleRotatePageCcw,
    handleResetPageRotation: input.handleResetPageRotation,
    handleRotatePage180: input.handleRotatePage180,
    handleRotateAllPages: input.handleRotateAllPages,
    handleRotateAllPagesCcw: input.handleRotateAllPagesCcw,
    handleRotateAllPages180: input.handleRotateAllPages180,
    handleRotateOddPages: input.handleRotateOddPages,
    handleRotateEvenPages: input.handleRotateEvenPages,
    handleRotateOddPagesCcw: input.handleRotateOddPagesCcw,
    handleRotateEvenPagesCcw: input.handleRotateEvenPagesCcw,
    handleRotate180OddPages: input.handleRotate180OddPages,
    handleRotate180EvenPages: input.handleRotate180EvenPages,
    handleResetRotationOddPages: input.handleResetRotationOddPages,
    handleResetRotationEvenPages: input.handleResetRotationEvenPages,
    handleResetAllRotations: input.handleResetAllRotations,
    openRotateRangeModal: input.openRotateRangeModal,
    handleDuplicatePage: input.handleDuplicatePage,
    handleDuplicatePageBefore: input.handleDuplicatePageBefore,
    openDuplicateRangeModal: input.openDuplicateRangeModal,
    openParityRangeModal: input.openParityRangeModal,
    openMoveRangeModal: input.openMoveRangeModal,
    openKeepRangeModal: input.openKeepRangeModal,
    handleKeepOddPages: input.handleKeepOddPages,
    handleKeepEvenPages: input.handleKeepEvenPages,
    handleDeleteOddPages: input.handleDeleteOddPages,
    handleDeleteEvenPages: input.handleDeleteEvenPages,
    handleAddBlankPage: input.handleAddBlankPage,
    handleAddBlankPageBefore: input.handleAddBlankPageBefore,
    openInsertBlankPagesModal: input.openInsertBlankPagesModal,
    handleInsertBlankBetweenPages: input.handleInsertBlankBetweenPages,
    handleInsertBlankBeforeOddPages: input.handleInsertBlankBeforeOddPages,
    handleInsertBlankBeforeEvenPages: input.handleInsertBlankBeforeEvenPages,
    handleInsertBlankAfterOddPages: input.handleInsertBlankAfterOddPages,
    handleInsertBlankAfterEvenPages: input.handleInsertBlankAfterEvenPages,
    handleMovePageToFirst: input.handleMovePageToFirst,
    handleMovePageToLast: input.handleMovePageToLast,
    handleMovePageUp: input.handleMovePageUp,
    handleMovePageDown: input.handleMovePageDown,
    openSwapPagesModal: input.openSwapPagesModal,
    handleReversePages: input.handleReversePages,
    openReverseRangeModal: input.openReverseRangeModal,
    handleReverseOddPages: input.handleReverseOddPages,
    handleReverseEvenPages: input.handleReverseEvenPages,
    handleMoveOddPagesToStart: input.handleMoveOddPagesToStart,
    handleMoveEvenPagesToStart: input.handleMoveEvenPagesToStart,
    handleMoveOddPagesToEnd: input.handleMoveOddPagesToEnd,
    handleMoveEvenPagesToEnd: input.handleMoveEvenPagesToEnd,
    handleSplitOddEven: input.handleSplitOddEven,
    handleDuplicateAllPages: input.handleDuplicateAllPages,
    handleDuplicatePageToEnd: input.handleDuplicatePageToEnd,
    handleDuplicateOddPages: input.handleDuplicateOddPages,
    handleDuplicateEvenPages: input.handleDuplicateEvenPages,
    handleDuplicateOddPagesBefore: input.handleDuplicateOddPagesBefore,
    handleDuplicateEvenPagesBefore: input.handleDuplicateEvenPagesBefore,
    handleDuplicateOddPagesToEnd: input.handleDuplicateOddPagesToEnd,
    handleDuplicateEvenPagesToEnd: input.handleDuplicateEvenPagesToEnd,
    handleDuplicateOddPagesToStart: input.handleDuplicateOddPagesToStart,
    handleDuplicateEvenPagesToStart: input.handleDuplicateEvenPagesToStart,
    openDeleteModal: input.openDeleteModal,
    openDeleteRangeModal: input.openDeleteRangeModal,
    openDeleteNthModal: input.openDeleteNthModal,
    openInsertModal: input.openInsertModal,
    openMergeModal: input.openMergeModal,
    openInterleaveModal: input.openInterleaveModal,
    openPrependModal: input.openPrependModal,
    openReplacePageModal: input.openReplacePageModal,
    openSplitModal: input.openSplitModal,
    openSplitAtModal: input.openSplitAtModal,
    openSplitEveryModal: input.openSplitEveryModal,
    openExtractModal: input.openExtractModal,
    openExtractOddModal: input.openExtractOddModal,
    openExtractEvenModal: input.openExtractEvenModal,
    handleSortPagesBySize: input.handleSortPagesBySize,
    handleSortOddPagesBySize: input.handleSortOddPagesBySize,
    handleSortEvenPagesBySize: input.handleSortEvenPagesBySize,
    handleSortPagesByRotation: input.handleSortPagesByRotation,
    handleSortOddPagesByRotation: input.handleSortOddPagesByRotation,
    handleSortEvenPagesByRotation: input.handleSortEvenPagesByRotation,
  };
}
