export const KEYBOARD_SHORTCUTS = [
  { keys: 'Ctrl+O', action: 'Open PDF' },
  { keys: 'Ctrl+S', action: 'Save' },
  { keys: 'Ctrl+Shift+S', action: 'Save As' },
  { keys: 'Ctrl+W', action: 'Close PDF' },
  { keys: 'Ctrl+P', action: 'Print' },
  { keys: 'Ctrl+Z / Ctrl+Y', action: 'Undo / Redo' },
  { keys: 'Ctrl+F', action: 'Find text' },
  { keys: 'Ctrl+Shift+P', action: 'Command palette' },
  { keys: 'Ctrl+R', action: 'Rotate page' },
  { keys: 'Ctrl+Shift+D', action: 'Duplicate page' },
  { keys: 'Ctrl+Shift+N', action: 'Blank page after' },
  { keys: 'Ctrl+Shift+Y', action: 'Reverse pages' },
  { keys: 'Ctrl+Shift+I', action: 'Insert PDF' },
  { keys: 'Ctrl+Shift+G', action: 'Merge PDF' },
  { keys: 'Ctrl+Shift+K', action: 'Split PDF' },
  { keys: 'Ctrl+Shift+J', action: 'Extract pages' },
  { keys: 'Ctrl+Shift+M', action: 'Markdown view' },
  { keys: 'Ctrl+Shift+O', action: 'Optimize PDF' },
  { keys: 'Ctrl+Shift+B', action: 'Export images' },
  { keys: 'Ctrl+Shift+E', action: 'Summarize' },
  { keys: 'Ctrl+Shift+U', action: 'Sign PDF' },
  { keys: 'Delete', action: 'Delete page' },
  { keys: 'H / N / D / S / T / X', action: 'Highlight / Note / Draw / Shape / Stamp / Redact' },
  { keys: 'E / G / I / F', action: 'Page text / Vector / Insert image / Forms' },
  { keys: '← → / PageUp PageDown', action: 'Previous / next page' },
  { keys: 'Home / End', action: 'First / last page' },
  { keys: 'Ctrl + / Ctrl - / Ctrl 0', action: 'Zoom in / out / reset' },
  { keys: 'Escape', action: 'Exit tool mode or close dialog' },
] as const;
