import type { BuildAppMenuSourceInput } from './buildAppMenuSource';
import type { BuildAppMenuInputArgs } from './buildAppMenuInputArgs';

export function menuInputPagesFields(
  args: BuildAppMenuInputArgs
): Pick<
  BuildAppMenuSourceInput,
  | 'handleRotatePage'
  | 'handleRotatePageCcw'
  | 'handleResetPageRotation'
  | 'handleRotatePage180'
  | 'handleRotateAllPages'
  | 'handleRotateAllPagesCcw'
  | 'handleRotateAllPages180'
  | 'handleRotateOddPages'
  | 'handleRotateEvenPages'
  | 'handleRotateOddPagesCcw'
  | 'handleRotateEvenPagesCcw'
  | 'handleRotate180OddPages'
  | 'handleRotate180EvenPages'
  | 'handleResetRotationOddPages'
  | 'handleResetRotationEvenPages'
  | 'handleResetAllRotations'
  | 'openRotateModal'
  | 'openRotateRangeModal'
  | 'handleDuplicatePage'
  | 'handleDuplicatePageBefore'
  | 'openDuplicateRangeModal'
  | 'openParityRangeModal'
  | 'openMoveRangeModal'
  | 'openKeepRangeModal'
  | 'handleKeepOddPages'
  | 'handleKeepEvenPages'
  | 'handleDeleteOddPages'
  | 'handleDeleteEvenPages'
  | 'handleAddBlankPage'
  | 'handleAddBlankPageBefore'
  | 'openInsertBlankPagesModal'
  | 'handleInsertBlankBetweenPages'
  | 'handleInsertBlankBeforeOddPages'
  | 'handleInsertBlankBeforeEvenPages'
  | 'handleInsertBlankAfterOddPages'
  | 'handleInsertBlankAfterEvenPages'
  | 'handleMovePageToFirst'
  | 'handleMovePageToLast'
  | 'handleMovePageUp'
  | 'handleMovePageDown'
  | 'openSwapPagesModal'
  | 'handleReversePages'
  | 'openReverseRangeModal'
  | 'handleReverseOddPages'
  | 'handleReverseEvenPages'
  | 'handleMoveOddPagesToStart'
  | 'handleMoveEvenPagesToStart'
  | 'handleMoveOddPagesToEnd'
  | 'handleMoveEvenPagesToEnd'
  | 'handleSplitOddEven'
  | 'handleDuplicateAllPages'
  | 'handleDuplicatePageToEnd'
  | 'handleDuplicateOddPages'
  | 'handleDuplicateEvenPages'
  | 'handleDuplicateOddPagesBefore'
  | 'handleDuplicateEvenPagesBefore'
  | 'handleDuplicateOddPagesToEnd'
  | 'handleDuplicateEvenPagesToEnd'
  | 'handleDuplicateOddPagesToStart'
  | 'handleDuplicateEvenPagesToStart'
  | 'openDeleteModal'
  | 'openDeleteRangeModal'
  | 'openDeleteNthModal'
  | 'openInsertModal'
  | 'openMergeModal'
  | 'openInterleaveModal'
  | 'openPrependModal'
  | 'openReplacePageModal'
  | 'openSplitModal'
  | 'openSplitAtModal'
  | 'openSplitEveryModal'
  | 'openExtractModal'
  | 'openExtractOddModal'
  | 'openExtractEvenModal'
  | 'handleSortPagesBySize'
  | 'handleSortOddPagesBySize'
  | 'handleSortEvenPagesBySize'
  | 'handleSortPagesByRotation'
  | 'handleSortOddPagesByRotation'
  | 'handleSortEvenPagesByRotation'
> {
  const { pdfActions } = args;
  return {
    handleRotatePage: pdfActions.handleRotatePage,
    handleRotatePageCcw: pdfActions.handleRotatePageCcw,
    handleResetPageRotation: pdfActions.handleResetPageRotation,
    handleRotatePage180: pdfActions.handleRotatePage180,
    handleRotateAllPages: pdfActions.handleRotateAllPages,
    handleRotateAllPagesCcw: pdfActions.handleRotateAllPagesCcw,
    handleRotateAllPages180: pdfActions.handleRotateAllPages180,
    handleRotateOddPages: pdfActions.handleRotateOddPages,
    handleRotateEvenPages: pdfActions.handleRotateEvenPages,
    handleRotateOddPagesCcw: pdfActions.handleRotateOddPagesCcw,
    handleRotateEvenPagesCcw: pdfActions.handleRotateEvenPagesCcw,
    handleRotate180OddPages: pdfActions.handleRotate180OddPages,
    handleRotate180EvenPages: pdfActions.handleRotate180EvenPages,
    handleResetRotationOddPages: pdfActions.handleResetRotationOddPages,
    handleResetRotationEvenPages: pdfActions.handleResetRotationEvenPages,
    handleResetAllRotations: pdfActions.handleResetAllRotations,
    openRotateModal: pdfActions.openRotateModal,
    openRotateRangeModal: pdfActions.openRotateRangeModal,
    handleDuplicatePage: pdfActions.handleDuplicatePage,
    handleDuplicatePageBefore: pdfActions.handleDuplicatePageBefore,
    openDuplicateRangeModal: pdfActions.openDuplicateRangeModal,
    openParityRangeModal: pdfActions.openParityRangeModal,
    openMoveRangeModal: pdfActions.openMoveRangeModal,
    openKeepRangeModal: pdfActions.openKeepRangeModal,
    handleKeepOddPages: pdfActions.handleKeepOddPages,
    handleKeepEvenPages: pdfActions.handleKeepEvenPages,
    handleDeleteOddPages: pdfActions.handleDeleteOddPages,
    handleDeleteEvenPages: pdfActions.handleDeleteEvenPages,
    handleAddBlankPage: pdfActions.handleAddBlankPage,
    handleAddBlankPageBefore: pdfActions.handleAddBlankPageBefore,
    openInsertBlankPagesModal: pdfActions.openInsertBlankPagesModal,
    handleInsertBlankBetweenPages: pdfActions.handleInsertBlankBetweenPages,
    handleInsertBlankBeforeOddPages: pdfActions.handleInsertBlankBeforeOddPages,
    handleInsertBlankBeforeEvenPages:
      pdfActions.handleInsertBlankBeforeEvenPages,
    handleInsertBlankAfterOddPages: pdfActions.handleInsertBlankAfterOddPages,
    handleInsertBlankAfterEvenPages: pdfActions.handleInsertBlankAfterEvenPages,
    handleMovePageToFirst: pdfActions.handleMovePageToFirst,
    handleMovePageToLast: pdfActions.handleMovePageToLast,
    handleMovePageUp: pdfActions.handleMovePageUp,
    handleMovePageDown: pdfActions.handleMovePageDown,
    openSwapPagesModal: pdfActions.openSwapPagesModal,
    handleReversePages: pdfActions.handleReversePages,
    openReverseRangeModal: pdfActions.openReverseRangeModal,
    handleReverseOddPages: pdfActions.handleReverseOddPages,
    handleReverseEvenPages: pdfActions.handleReverseEvenPages,
    handleMoveOddPagesToStart: pdfActions.handleMoveOddPagesToStart,
    handleMoveEvenPagesToStart: pdfActions.handleMoveEvenPagesToStart,
    handleMoveOddPagesToEnd: pdfActions.handleMoveOddPagesToEnd,
    handleMoveEvenPagesToEnd: pdfActions.handleMoveEvenPagesToEnd,
    handleSplitOddEven: pdfActions.handleSplitOddEven,
    handleDuplicateAllPages: pdfActions.handleDuplicateAllPages,
    handleDuplicatePageToEnd: pdfActions.handleDuplicatePageToEnd,
    handleDuplicateOddPages: pdfActions.handleDuplicateOddPages,
    handleDuplicateEvenPages: pdfActions.handleDuplicateEvenPages,
    handleDuplicateOddPagesBefore: pdfActions.handleDuplicateOddPagesBefore,
    handleDuplicateEvenPagesBefore: pdfActions.handleDuplicateEvenPagesBefore,
    handleDuplicateOddPagesToEnd: pdfActions.handleDuplicateOddPagesToEnd,
    handleDuplicateEvenPagesToEnd: pdfActions.handleDuplicateEvenPagesToEnd,
    handleDuplicateOddPagesToStart: pdfActions.handleDuplicateOddPagesToStart,
    handleDuplicateEvenPagesToStart: pdfActions.handleDuplicateEvenPagesToStart,
    openDeleteModal: pdfActions.openDeleteModal,
    openDeleteRangeModal: pdfActions.openDeleteRangeModal,
    openDeleteNthModal: pdfActions.openDeleteNthModal,
    openInsertModal: pdfActions.openInsertModal,
    openMergeModal: pdfActions.openMergeModal,
    openInterleaveModal: pdfActions.openInterleaveModal,
    openPrependModal: pdfActions.openPrependModal,
    openReplacePageModal: pdfActions.openReplacePageModal,
    openSplitModal: pdfActions.openSplitModal,
    openSplitAtModal: pdfActions.openSplitAtModal,
    openSplitEveryModal: pdfActions.openSplitEveryModal,
    openExtractModal: pdfActions.openExtractModal,
    openExtractOddModal: pdfActions.openExtractOddModal,
    openExtractEvenModal: pdfActions.openExtractEvenModal,
    handleSortPagesBySize: pdfActions.handleSortPagesBySize,
    handleSortOddPagesBySize: pdfActions.handleSortOddPagesBySize,
    handleSortEvenPagesBySize: pdfActions.handleSortEvenPagesBySize,
    handleSortPagesByRotation: pdfActions.handleSortPagesByRotation,
    handleSortOddPagesByRotation: pdfActions.handleSortOddPagesByRotation,
    handleSortEvenPagesByRotation: pdfActions.handleSortEvenPagesByRotation,
  };
}
