import type { AppMenuContext } from './types';
import type { AppMenuContextSource } from './buildAppMenuContext';
import { voidRun } from './menuBuilders';

export function menuContextDocAnnotFields(source: AppMenuContextSource): Pick<
  AppMenuContext,
  | 'hasPdf'
  | 'isDirty'
  | 'canUndo'
  | 'canRedo'
  | 'pageCount'
  | 'currentPage'
  | 'viewMode'
  | 'highlightMode'
  | 'noteMode'
  | 'drawMode'
  | 'shapeMode'
  | 'stampMode'
  | 'redactMode'
  | 'imageInsertMode'
  | 'textEditMode'
  | 'vectorEditMode'
  | 'showFormsPanel'
  | 'showBookmarksPanel'
  | 'showSignaturesPanel'
  | 'tesseractInstalled'
  | 'openPdf'
  | 'handleSave'
  | 'openSaveAs'
  | 'requestClosePdf'
  | 'undo'
  | 'redo'
  | 'handlePrint'
  | 'openSearchModal'
  | 'setViewModePdf'
  | 'toggleMarkdownView'
  | 'handleOptimizePdf'
  | 'openExportPngModal'
  | 'openExportPagePdfModal'
  | 'openExportPagesPdfModal'
  | 'openInsertImagePageModal'
  | 'openPageNumbersModal'
  | 'openPageHeaderModal'
  | 'openPageFooterModal'
  | 'openPageSizeModal'
  | 'openWatermarkModal'
  | 'openCropModal'
  | 'openCropRangeModal'
  | 'handleCropOddPages'
  | 'handleCropEvenPages'
  | 'openExpandMarginsModal'
  | 'openShrinkMarginsModal'
  | 'openPageBorderModal'
  | 'openFlattenModal'
  | 'handleFlattenAllAnnotations'
  | 'handleFlattenOddPages'
  | 'handleFlattenEvenPages'
  | 'openMetadataModal'
  | 'handleSummarizePdf'
  | 'openProtectModal'
  | 'openDecryptModal'
  | 'openSignModal'
  | 'toggleSignaturesPanel'
  | 'toggleBookmarksPanel'
  | 'toggleRedactMode'
  | 'toggleHighlightMode'
  | 'toggleNoteMode'
  | 'toggleDrawMode'
  | 'toggleShapeMode'
  | 'toggleStampMode'
  | 'toggleImageInsertMode'
  | 'toggleTextEditMode'
  | 'toggleVectorEditMode'
  | 'openPageEditsModal'
  | 'toggleFormsPanel'
  | 'openTesseractGuide'
  | 'openShortcutsHelp'
  | 'openLicenses'
  | 'openCredits'
  | 'openAbout'
  | 'openCommandPalette'
> {
  return {
    hasPdf: source.hasPdf,
    isDirty: source.isDirty,
    canUndo: source.canUndo,
    canRedo: source.canRedo,
    pageCount: source.pageCount,
    currentPage: source.currentPage,
    viewMode: source.viewMode,
    highlightMode: source.highlightMode,
    noteMode: source.noteMode,
    drawMode: source.drawMode,
    shapeMode: source.shapeMode,
    stampMode: source.stampMode,
    redactMode: source.redactMode,
    imageInsertMode: source.imageInsertMode,
    textEditMode: source.textEditMode,
    vectorEditMode: source.vectorEditMode,
    showFormsPanel: source.showFormsPanel,
    showBookmarksPanel: source.showBookmarksPanel,
    showSignaturesPanel: source.showSignaturesPanel,
    tesseractInstalled: source.tesseractInstalled,
    openPdf: source.openPdf,
    handleSave: source.handleSave,
    openSaveAs: source.openSaveAs,
    requestClosePdf: source.requestClosePdf,
    undo: source.undo,
    redo: source.redo,
    handlePrint: source.handlePrint,
    openSearchModal: source.openSearchModal,
    setViewModePdf: source.setViewModePdf,
    toggleMarkdownView: source.toggleMarkdownView,
    handleOptimizePdf: source.handleOptimizePdf,
    openExportPngModal: source.openExportPngModal,
    openExportPagePdfModal: source.openExportPagePdfModal,
    openExportPagesPdfModal: source.openExportPagesPdfModal,
    openInsertImagePageModal: source.openInsertImagePageModal,
    openPageNumbersModal: source.openPageNumbersModal,
    openPageHeaderModal: source.openPageHeaderModal,
    openPageFooterModal: source.openPageFooterModal,
    openPageSizeModal: source.openPageSizeModal,
    openWatermarkModal: source.openWatermarkModal,
    openCropModal: source.openCropModal,
    openCropRangeModal: source.openCropRangeModal,
    handleCropOddPages: voidRun(source.handleCropOddPages),
    handleCropEvenPages: voidRun(source.handleCropEvenPages),
    openExpandMarginsModal: source.openExpandMarginsModal,
    openShrinkMarginsModal: source.openShrinkMarginsModal,
    openPageBorderModal: source.openPageBorderModal,
    openFlattenModal: source.openFlattenModal,
    handleFlattenAllAnnotations: voidRun(source.handleFlattenAllAnnotations),
    handleFlattenOddPages: voidRun(source.handleFlattenOddPages),
    handleFlattenEvenPages: voidRun(source.handleFlattenEvenPages),
    openMetadataModal: voidRun(source.openMetadataModal),
    handleSummarizePdf: source.handleSummarizePdf,
    openProtectModal: source.openProtectModal,
    openDecryptModal: source.openDecryptModal,
    openSignModal: source.openSignModal,
    toggleSignaturesPanel: source.toggleSignaturesPanel,
    toggleBookmarksPanel: source.toggleBookmarksPanel,
    toggleRedactMode: source.toggleRedactMode,
    toggleHighlightMode: source.toggleHighlightMode,
    toggleNoteMode: source.toggleNoteMode,
    toggleDrawMode: source.toggleDrawMode,
    toggleShapeMode: source.toggleShapeMode,
    toggleStampMode: source.toggleStampMode,
    toggleImageInsertMode: source.toggleImageInsertMode,
    toggleTextEditMode: source.toggleTextEditMode,
    toggleVectorEditMode: source.toggleVectorEditMode,
    openPageEditsModal: source.openPageEditsModal,
    toggleFormsPanel: source.toggleFormsPanel,
    openTesseractGuide: source.openTesseractGuide,
    openShortcutsHelp: source.openShortcutsHelp,
    openLicenses: source.openLicenses,
    openCredits: source.openCredits,
    openAbout: source.openAbout,
    openCommandPalette: source.openCommandPalette,
  };
}
