import type { BuildAppMenuSourceInput } from './buildAppMenuSource';
import type { BuildAppMenuInputArgs } from './buildAppMenuInputArgs';

export function menuInputDocFields(args: BuildAppMenuInputArgs): Pick<
  BuildAppMenuSourceInput,
  | 'filePath'
  | 'isDirty'
  | 'canUndo'
  | 'canRedo'
  | 'pageCount'
  | 'currentPage'
  | 'viewMode'
  | 'highlightMode'
  | 'noteMode'
  | 'drawMode'
  | 'shapeMode'
  | 'stampMode'
  | 'redactMode'
  | 'imageInsertMode'
  | 'textEditMode'
  | 'vectorEditMode'
  | 'showFormsPanel'
  | 'showBookmarksPanel'
  | 'showSignaturesPanel'
  | 'ocrAvailable'
  | 'guardUnsaved'
  | 'closePdf'
  | 'setViewMode'
  | 'setShowBookmarksPanel'
  | 'setShowPageEditsModal'
  | 'setShowShortcutsHelp'
  | 'setShowLicenses'
  | 'setShowCredits'
  | 'setShowAbout'
  | 'setShowCommandPalette'
  | 'openTesseractGuide'
  | 'openPdf'
  | 'handleSave'
  | 'openSaveAs'
  | 'undo'
  | 'redo'
  | 'handlePrint'
  | 'openSearchModal'
  | 'toggleMarkdownView'
  | 'handleOptimizePdf'
  | 'openExportPngModal'
  | 'openExportPagePdfModal'
  | 'openExportPagesPdfModal'
  | 'openInsertImagePageModal'
  | 'openPageNumbersModal'
  | 'openPageHeaderModal'
  | 'openPageFooterModal'
  | 'openPageSizeModal'
  | 'openWatermarkModal'
  | 'openCropModal'
  | 'openCropRangeModal'
  | 'handleCropOddPages'
  | 'handleCropEvenPages'
  | 'openExpandMarginsModal'
  | 'openShrinkMarginsModal'
  | 'openPageBorderModal'
  | 'openFlattenModal'
  | 'handleFlattenAllAnnotations'
  | 'handleFlattenOddPages'
  | 'handleFlattenEvenPages'
  | 'openMetadataModal'
  | 'handleSummarizePdf'
  | 'openProtectModal'
  | 'openDecryptModal'
  | 'openSignModal'
  | 'toggleSignaturesPanel'
  | 'toggleRedactMode'
  | 'toggleHighlightMode'
  | 'toggleNoteMode'
  | 'toggleDrawMode'
  | 'toggleShapeMode'
  | 'toggleStampMode'
  | 'toggleImageInsertMode'
  | 'toggleTextEditMode'
  | 'toggleVectorEditMode'
  | 'toggleFormsPanel'
> {
  const { doc, annotation, panels, history, chrome, help, pdfActions } = args;
  return {
    filePath: doc.filePath,
    isDirty: doc.isDirty,
    canUndo: history.canUndo,
    canRedo: history.canRedo,
    pageCount: doc.pageCount,
    currentPage: doc.currentPage,
    viewMode: doc.viewMode,
    highlightMode: annotation.highlightMode,
    noteMode: annotation.noteMode,
    drawMode: annotation.drawMode,
    shapeMode: annotation.shapeMode,
    stampMode: annotation.stampMode,
    redactMode: annotation.redactMode,
    imageInsertMode: annotation.imageInsertMode,
    textEditMode: annotation.textEditMode,
    vectorEditMode: annotation.vectorEditMode,
    showFormsPanel: panels.showFormsPanel,
    showBookmarksPanel: panels.showBookmarksPanel,
    showSignaturesPanel: panels.showSignaturesPanel,
    ocrAvailable: doc.ocrAvailable,
    guardUnsaved: chrome.guardUnsaved,
    closePdf: chrome.closePdf,
    setViewMode: chrome.setViewMode,
    setShowBookmarksPanel: chrome.setShowBookmarksPanel,
    setShowPageEditsModal: chrome.setShowPageEditsModal,
    setShowShortcutsHelp: help.setShowShortcutsHelp,
    setShowLicenses: help.setShowLicenses,
    setShowCredits: help.setShowCredits,
    setShowAbout: help.setShowAbout,
    setShowCommandPalette: help.setShowCommandPalette,
    openTesseractGuide: chrome.openTesseractGuide,
    openPdf: chrome.openPdf,
    handleSave: pdfActions.handleSave,
    openSaveAs: pdfActions.openSaveAs,
    undo: history.undo,
    redo: history.redo,
    handlePrint: chrome.handlePrint,
    openSearchModal: chrome.openSearchModal,
    toggleMarkdownView: pdfActions.toggleMarkdownView,
    handleOptimizePdf: pdfActions.handleOptimizePdf,
    openExportPngModal: pdfActions.openExportPngModal,
    openExportPagePdfModal: pdfActions.openExportPagePdfModal,
    openExportPagesPdfModal: pdfActions.openExportPagesPdfModal,
    openInsertImagePageModal: pdfActions.openInsertImagePageModal,
    openPageNumbersModal: pdfActions.openPageNumbersModal,
    openPageHeaderModal: pdfActions.openPageHeaderModal,
    openPageFooterModal: pdfActions.openPageFooterModal,
    openPageSizeModal: pdfActions.openPageSizeModal,
    openWatermarkModal: pdfActions.openWatermarkModal,
    openCropModal: pdfActions.openCropModal,
    openCropRangeModal: pdfActions.openCropRangeModal,
    handleCropOddPages: pdfActions.handleCropOddPages,
    handleCropEvenPages: pdfActions.handleCropEvenPages,
    openExpandMarginsModal: pdfActions.openExpandMarginsModal,
    openShrinkMarginsModal: pdfActions.openShrinkMarginsModal,
    openPageBorderModal: pdfActions.openPageBorderModal,
    openFlattenModal: pdfActions.openFlattenModal,
    handleFlattenAllAnnotations: pdfActions.handleFlattenAllAnnotations,
    handleFlattenOddPages: pdfActions.handleFlattenOddPages,
    handleFlattenEvenPages: pdfActions.handleFlattenEvenPages,
    openMetadataModal: pdfActions.openMetadataModal,
    handleSummarizePdf: pdfActions.handleSummarizePdf,
    openProtectModal: pdfActions.openProtectModal,
    openDecryptModal: pdfActions.openDecryptModal,
    openSignModal: pdfActions.openSignModal,
    toggleSignaturesPanel: pdfActions.toggleSignaturesPanel,
    toggleRedactMode: pdfActions.toggleRedactMode,
    toggleHighlightMode: pdfActions.toggleHighlightMode,
    toggleNoteMode: pdfActions.toggleNoteMode,
    toggleDrawMode: pdfActions.toggleDrawMode,
    toggleShapeMode: pdfActions.toggleShapeMode,
    toggleStampMode: pdfActions.toggleStampMode,
    toggleImageInsertMode: pdfActions.toggleImageInsertMode,
    toggleTextEditMode: pdfActions.toggleTextEditMode,
    toggleVectorEditMode: pdfActions.toggleVectorEditMode,
    toggleFormsPanel: pdfActions.toggleFormsPanel,
  };
}
