import type { ShortcutBindings } from '../app/useShortcutBindingsState';

export type MenuAction = {
  id: string;
  label: string;
  shortcut?: string;
  shortcutCommandId?: import('../settings/shortcutRegistry').ShortcutCommandId;
  disabled?: boolean;
  danger?: boolean;
  active?: boolean;
  run: () => void;
};

export type MenuSeparator = { separator: true };

export type MenuSubmenu = {
  label: string;
  items: MenuEntry[];
};

export type MenuEntry = MenuAction | MenuSeparator | MenuSubmenu;

export type MenuRoot = {
  id: string;
  label: string;
  items: MenuEntry[];
  disabled?: boolean;
};

export type FlatMenuAction = MenuAction & {
  path: string;
};

export interface AppMenuContext {
  hasPdf: boolean;
  isDirty: boolean;
  canUndo: boolean;
  canRedo: boolean;
  pageCount: number | null;
  currentPage: number;
  viewMode: 'pdf' | 'markdown';
  scrollViewMode: 'single' | 'continuous';
  highlightMode: boolean;
  noteMode: boolean;
  drawMode: boolean;
  shapeMode: boolean;
  stampMode: boolean;
  redactMode: boolean;
  imageInsertMode: boolean;
  textEditMode: boolean;
  vectorEditMode: boolean;
  showFormsPanel: boolean;
  showBookmarksPanel: boolean;
  showAnnotationsPanel: boolean;
  showSignaturesPanel: boolean;
  showPdfUaPanel: boolean;
  togglePdfUaPanel: () => void;
  tesseractInstalled: boolean;
  openPdf: () => void;
  handleSave: () => void | Promise<void>;
  openSaveAs: () => void;
  requestClosePdf: () => void;
  undo: () => void | Promise<void>;
  redo: () => void | Promise<void>;
  handlePrint: () => void | Promise<void>;
  openPrintDialog: () => void;
  openSearchModal: () => void;
  handleRotatePage: () => void | Promise<void>;
  handleRotatePageCcw: () => void | Promise<void>;
  handleResetPageRotation: () => void | Promise<void>;
  handleRotatePage180: () => void | Promise<void>;
  handleRotateAllPages: () => void | Promise<void>;
  handleRotateAllPagesCcw: () => void | Promise<void>;
  handleRotateAllPages180: () => void | Promise<void>;
  handleRotateOddPages: () => void | Promise<void>;
  handleRotateEvenPages: () => void | Promise<void>;
  handleRotateOddPagesCcw: () => void | Promise<void>;
  handleRotateEvenPagesCcw: () => void | Promise<void>;
  handleRotate180OddPages: () => void | Promise<void>;
  handleRotate180EvenPages: () => void | Promise<void>;
  handleResetRotationOddPages: () => void | Promise<void>;
  handleResetRotationEvenPages: () => void | Promise<void>;
  handleResetAllRotations: () => void | Promise<void>;
  openRotateModal: () => void;
  openRotateRangeModal: () => void;
  handleDuplicatePage: () => void | Promise<void>;
  handleDuplicatePageBefore: () => void | Promise<void>;
  openDuplicateRangeModal: () => void;
  openParityRangeModal: () => void;
  openMoveRangeModal: () => void;
  openKeepRangeModal: () => void;
  handleKeepOddPages: () => void | Promise<void>;
  handleKeepEvenPages: () => void | Promise<void>;
  handleDeleteOddPages: () => void | Promise<void>;
  handleDeleteEvenPages: () => void | Promise<void>;
  handleAddBlankPage: () => void | Promise<void>;
  handleAddBlankPageBefore: () => void | Promise<void>;
  openInsertBlankPagesModal: () => void;
  handleInsertBlankBetweenPages: () => void | Promise<void>;
  handleInsertBlankBeforeOddPages: () => void | Promise<void>;
  handleInsertBlankBeforeEvenPages: () => void | Promise<void>;
  handleInsertBlankAfterOddPages: () => void | Promise<void>;
  handleInsertBlankAfterEvenPages: () => void | Promise<void>;
  handleMovePageToFirst: () => void | Promise<void>;
  handleMovePageToLast: () => void | Promise<void>;
  handleMovePageUp: () => void | Promise<void>;
  handleMovePageDown: () => void | Promise<void>;
  openSwapPagesModal: () => void;
  handleReversePages: () => void | Promise<void>;
  openReverseRangeModal: () => void;
  handleReverseOddPages: () => void | Promise<void>;
  handleReverseEvenPages: () => void | Promise<void>;
  handleMoveOddPagesToStart: () => void | Promise<void>;
  handleMoveEvenPagesToStart: () => void | Promise<void>;
  handleMoveOddPagesToEnd: () => void | Promise<void>;
  handleMoveEvenPagesToEnd: () => void | Promise<void>;
  handleSplitOddEven: () => void | Promise<void>;
  handleDuplicateAllPages: () => void | Promise<void>;
  handleDuplicatePageToEnd: () => void | Promise<void>;
  handleDuplicateOddPages: () => void | Promise<void>;
  handleDuplicateEvenPages: () => void | Promise<void>;
  handleDuplicateOddPagesBefore: () => void | Promise<void>;
  handleDuplicateEvenPagesBefore: () => void | Promise<void>;
  handleDuplicateOddPagesToEnd: () => void | Promise<void>;
  handleDuplicateEvenPagesToEnd: () => void | Promise<void>;
  handleDuplicateOddPagesToStart: () => void | Promise<void>;
  handleDuplicateEvenPagesToStart: () => void | Promise<void>;
  openDeleteModal: () => void;
  openDeleteRangeModal: () => void;
  openDeleteNthModal: () => void;
  openInsertModal: () => void;
  openMergeModal: () => void;
  openInterleaveModal: () => void;
  openPrependModal: () => void;
  openReplacePageModal: () => void;
  openSplitModal: () => void;
  openSplitAtModal: () => void;
  openSplitEveryModal: () => void;
  openExtractModal: () => void;
  openExtractOddModal: () => void;
  openExtractEvenModal: () => void;
  setViewModePdf: () => void;
  toggleMarkdownView: () => void | Promise<void>;
  handleOptimizePdf: () => void | Promise<void>;
  handleMakePdfSearchable: () => void | Promise<void>;
  hasRedactions: boolean;
  openApplyRedactionsModal: () => void;
  openBatesNumberModal: () => void;
  openExportPngModal: () => void;
  openExportPagePdfModal: () => void;
  openExportPagesPdfModal: () => void;
  openInsertImagePageModal: () => void;
  openPageNumbersModal: () => void;
  openPageHeaderModal: () => void;
  openPageFooterModal: () => void;
  openPageSizeModal: () => void;
  openWatermarkModal: () => void;
  openCropModal: () => void;
  openCropRangeModal: () => void;
  handleCropOddPages: () => void | Promise<void>;
  handleCropEvenPages: () => void | Promise<void>;
  openExpandMarginsModal: () => void;
  openShrinkMarginsModal: () => void;
  openPageBorderModal: () => void;
  openFlattenModal: () => void;
  handleFlattenAllAnnotations: () => void | Promise<void>;
  handleFlattenOddPages: () => void | Promise<void>;
  handleFlattenEvenPages: () => void | Promise<void>;
  handleSortPagesBySize: (desc: boolean) => void | Promise<void>;
  handleSortOddPagesBySize: (desc: boolean) => void | Promise<void>;
  handleSortEvenPagesBySize: (desc: boolean) => void | Promise<void>;
  handleSortPagesByRotation: (desc: boolean) => void | Promise<void>;
  handleSortOddPagesByRotation: (desc: boolean) => void | Promise<void>;
  handleSortEvenPagesByRotation: (desc: boolean) => void | Promise<void>;
  openMetadataModal: () => void | Promise<void>;
  handleSummarizePdf: () => void | Promise<void>;
  openProtectModal: () => void;
  openDecryptModal: () => void;
  openSignModal: () => void;
  toggleSignaturesPanel: () => void;
  toggleBookmarksPanel: () => void;
  toggleAnnotationsPanel: () => void;
  toggleContinuousScroll: () => void;
  toggleRedactMode: () => void;
  hasTextSelection: boolean;
  highlightSelection: () => void;
  toggleHighlightMode: () => void;
  toggleNoteMode: () => void;
  toggleDrawMode: () => void;
  toggleShapeMode: () => void;
  toggleStampMode: () => void;
  toggleImageInsertMode: () => void;
  toggleTextEditMode: () => void;
  editTextRunMode: boolean;
  toggleEditTextRunMode: () => void;
  toggleVectorEditMode: () => void;
  openPageEditsModal: () => void;
  toggleFormsPanel: () => void;
  openTesseractGuide: () => void;
  openShortcutsHelp: () => void;
  openLicenses: () => void;
  openCredits: () => void;
  openAbout: () => void;
  openUpdateModal: () => void;
  updaterSupported: boolean;
  openCommandPalette: () => void;
  activeSurface: import('../app/useAppSurfaceState').AppSurface;
  openSettings: (
    focus?: import('../app/useAppSurfaceState').SettingsFocusSection
  ) => void;
  shortcutBindings: ShortcutBindings;
}

export type AppMenus = {
  menus: MenuRoot[];
  quickAccess: MenuAction[];
  allActions: FlatMenuAction[];
};

export type VoidHandler = () => void | Promise<void>;
export type SortHandler = (desc: boolean) => void | Promise<void>;

/** Raw handlers from App before menu-specific void wrapping. */
export type AppMenuContextSource = {
  hasPdf: boolean;
  isDirty: boolean;
  canUndo: boolean;
  canRedo: boolean;
  pageCount: number | null;
  currentPage: number;
  viewMode: 'pdf' | 'markdown';
  scrollViewMode: 'single' | 'continuous';
  highlightMode: boolean;
  noteMode: boolean;
  drawMode: boolean;
  shapeMode: boolean;
  stampMode: boolean;
  redactMode: boolean;
  imageInsertMode: boolean;
  textEditMode: boolean;
  vectorEditMode: boolean;
  showFormsPanel: boolean;
  showBookmarksPanel: boolean;
  showAnnotationsPanel: boolean;
  showSignaturesPanel: boolean;
  showPdfUaPanel: boolean;
  togglePdfUaPanel: () => void;
  tesseractInstalled: boolean;
  openPdf: () => void;
  handleSave: VoidHandler;
  openSaveAs: () => void;
  requestClosePdf: () => void;
  undo: VoidHandler;
  redo: VoidHandler;
  handlePrint: VoidHandler;
  openPrintDialog: VoidHandler;
  openSearchModal: () => void;
  handleRotatePage: VoidHandler;
  handleRotatePageCcw: VoidHandler;
  handleResetPageRotation: VoidHandler;
  handleRotatePage180: VoidHandler;
  handleRotateAllPages: VoidHandler;
  handleRotateAllPagesCcw: VoidHandler;
  handleRotateAllPages180: VoidHandler;
  handleRotateOddPages: VoidHandler;
  handleRotateEvenPages: VoidHandler;
  handleRotateOddPagesCcw: VoidHandler;
  handleRotateEvenPagesCcw: VoidHandler;
  handleRotate180OddPages: VoidHandler;
  handleRotate180EvenPages: VoidHandler;
  handleResetRotationOddPages: VoidHandler;
  handleResetRotationEvenPages: VoidHandler;
  handleResetAllRotations: VoidHandler;
  openRotateModal: () => void;
  openRotateRangeModal: () => void;
  handleDuplicatePage: VoidHandler;
  handleDuplicatePageBefore: VoidHandler;
  openDuplicateRangeModal: () => void;
  openParityRangeModal: () => void;
  openMoveRangeModal: () => void;
  openKeepRangeModal: () => void;
  handleKeepOddPages: VoidHandler;
  handleKeepEvenPages: VoidHandler;
  handleDeleteOddPages: VoidHandler;
  handleDeleteEvenPages: VoidHandler;
  handleAddBlankPage: VoidHandler;
  handleAddBlankPageBefore: VoidHandler;
  openInsertBlankPagesModal: () => void;
  handleInsertBlankBetweenPages: VoidHandler;
  handleInsertBlankBeforeOddPages: VoidHandler;
  handleInsertBlankBeforeEvenPages: VoidHandler;
  handleInsertBlankAfterOddPages: VoidHandler;
  handleInsertBlankAfterEvenPages: VoidHandler;
  handleMovePageToFirst: VoidHandler;
  handleMovePageToLast: VoidHandler;
  handleMovePageUp: VoidHandler;
  handleMovePageDown: VoidHandler;
  openSwapPagesModal: () => void;
  handleReversePages: VoidHandler;
  openReverseRangeModal: () => void;
  handleReverseOddPages: VoidHandler;
  handleReverseEvenPages: VoidHandler;
  handleMoveOddPagesToStart: VoidHandler;
  handleMoveEvenPagesToStart: VoidHandler;
  handleMoveOddPagesToEnd: VoidHandler;
  handleMoveEvenPagesToEnd: VoidHandler;
  handleSplitOddEven: VoidHandler;
  handleDuplicateAllPages: VoidHandler;
  handleDuplicatePageToEnd: VoidHandler;
  handleDuplicateOddPages: VoidHandler;
  handleDuplicateEvenPages: VoidHandler;
  handleDuplicateOddPagesBefore: VoidHandler;
  handleDuplicateEvenPagesBefore: VoidHandler;
  handleDuplicateOddPagesToEnd: VoidHandler;
  handleDuplicateEvenPagesToEnd: VoidHandler;
  handleDuplicateOddPagesToStart: VoidHandler;
  handleDuplicateEvenPagesToStart: VoidHandler;
  openDeleteModal: () => void;
  openDeleteRangeModal: () => void;
  openDeleteNthModal: () => void;
  openInsertModal: () => void;
  openMergeModal: () => void;
  openInterleaveModal: () => void;
  openPrependModal: () => void;
  openReplacePageModal: () => void;
  openSplitModal: () => void;
  openSplitAtModal: () => void;
  openSplitEveryModal: () => void;
  openExtractModal: () => void;
  openExtractOddModal: () => void;
  openExtractEvenModal: () => void;
  setViewModePdf: () => void;
  toggleMarkdownView: VoidHandler;
  handleOptimizePdf: VoidHandler;
  handleMakePdfSearchable: VoidHandler;
  hasRedactions: boolean;
  openApplyRedactionsModal: () => void;
  openBatesNumberModal: () => void;
  openExportPngModal: () => void;
  openExportPagePdfModal: () => void;
  openExportPagesPdfModal: () => void;
  openInsertImagePageModal: () => void;
  openPageNumbersModal: () => void;
  openPageHeaderModal: () => void;
  openPageFooterModal: () => void;
  openPageSizeModal: () => void;
  openWatermarkModal: () => void;
  openCropModal: () => void;
  openCropRangeModal: () => void;
  handleCropOddPages: VoidHandler;
  handleCropEvenPages: VoidHandler;
  openExpandMarginsModal: () => void;
  openShrinkMarginsModal: () => void;
  openPageBorderModal: () => void;
  openFlattenModal: () => void;
  handleFlattenAllAnnotations: VoidHandler;
  handleFlattenOddPages: VoidHandler;
  handleFlattenEvenPages: VoidHandler;
  handleSortPagesBySize: SortHandler;
  handleSortOddPagesBySize: SortHandler;
  handleSortEvenPagesBySize: SortHandler;
  handleSortPagesByRotation: SortHandler;
  handleSortOddPagesByRotation: SortHandler;
  handleSortEvenPagesByRotation: SortHandler;
  openMetadataModal: VoidHandler;
  handleSummarizePdf: VoidHandler;
  openProtectModal: () => void;
  openDecryptModal: () => void;
  openSignModal: () => void;
  toggleSignaturesPanel: () => void;
  toggleBookmarksPanel: () => void;
  toggleAnnotationsPanel: () => void;
  toggleContinuousScroll: () => void;
  toggleRedactMode: () => void;
  hasTextSelection: boolean;
  highlightSelection: () => void;
  toggleHighlightMode: () => void;
  toggleNoteMode: () => void;
  toggleDrawMode: () => void;
  toggleShapeMode: () => void;
  toggleStampMode: () => void;
  toggleImageInsertMode: () => void;
  toggleTextEditMode: () => void;
  editTextRunMode: boolean;
  toggleEditTextRunMode: () => void;
  toggleVectorEditMode: () => void;
  openPageEditsModal: () => void;
  toggleFormsPanel: () => void;
  openTesseractGuide: () => void;
  openShortcutsHelp: () => void;
  openLicenses: () => void;
  openCredits: () => void;
  openAbout: () => void;
  openUpdateModal: () => void;
  updaterSupported: boolean;
  openCommandPalette: () => void;
  activeSurface: import('../app/useAppSurfaceState').AppSurface;
  openSettings: (
    focus?: import('../app/useAppSurfaceState').SettingsFocusSection
  ) => void;
  shortcutBindings: ShortcutBindings;
};
