export type MenuAction = {
  id: string;
  label: string;
  shortcut?: string;
  disabled?: boolean;
  danger?: boolean;
  active?: boolean;
  run: () => void;
};

export type MenuSeparator = { separator: true };

export type MenuSubmenu = {
  label: string;
  items: MenuEntry[];
};

export type MenuEntry = MenuAction | MenuSeparator | MenuSubmenu;

export type MenuRoot = {
  id: string;
  label: string;
  items: MenuEntry[];
  disabled?: boolean;
};

export type FlatMenuAction = MenuAction & {
  path: string;
};

export interface AppMenuContext {
  hasPdf: boolean;
  isDirty: boolean;
  canUndo: boolean;
  canRedo: boolean;
  pageCount: number | null;
  currentPage: number;
  viewMode: 'pdf' | 'markdown';
  highlightMode: boolean;
  noteMode: boolean;
  drawMode: boolean;
  shapeMode: boolean;
  stampMode: boolean;
  redactMode: boolean;
  imageInsertMode: boolean;
  textEditMode: boolean;
  vectorEditMode: boolean;
  showFormsPanel: boolean;
  showBookmarksPanel: boolean;
  showSignaturesPanel: boolean;
  tesseractInstalled: boolean;
  openPdf: () => void;
  handleSave: () => void | Promise<void>;
  openSaveAs: () => void;
  requestClosePdf: () => void;
  undo: () => void | Promise<void>;
  redo: () => void | Promise<void>;
  handlePrint: () => void | Promise<void>;
  openSearchModal: () => void;
  handleRotatePage: () => void | Promise<void>;
  handleRotatePageCcw: () => void | Promise<void>;
  handleResetPageRotation: () => void | Promise<void>;
  handleRotatePage180: () => void | Promise<void>;
  handleRotateAllPages: () => void | Promise<void>;
  handleRotateAllPagesCcw: () => void | Promise<void>;
  handleRotateAllPages180: () => void | Promise<void>;
  handleRotateOddPages: () => void | Promise<void>;
  handleRotateEvenPages: () => void | Promise<void>;
  handleRotateOddPagesCcw: () => void | Promise<void>;
  handleRotateEvenPagesCcw: () => void | Promise<void>;
  handleRotate180OddPages: () => void | Promise<void>;
  handleRotate180EvenPages: () => void | Promise<void>;
  handleResetRotationOddPages: () => void | Promise<void>;
  handleResetRotationEvenPages: () => void | Promise<void>;
  handleResetAllRotations: () => void | Promise<void>;
  openRotateRangeModal: () => void;
  handleDuplicatePage: () => void | Promise<void>;
  handleDuplicatePageBefore: () => void | Promise<void>;
  openDuplicateRangeModal: () => void;
  openParityRangeModal: () => void;
  openMoveRangeModal: () => void;
  openKeepRangeModal: () => void;
  handleKeepOddPages: () => void | Promise<void>;
  handleKeepEvenPages: () => void | Promise<void>;
  handleDeleteOddPages: () => void | Promise<void>;
  handleDeleteEvenPages: () => void | Promise<void>;
  handleAddBlankPage: () => void | Promise<void>;
  handleAddBlankPageBefore: () => void | Promise<void>;
  openInsertBlankPagesModal: () => void;
  handleInsertBlankBetweenPages: () => void | Promise<void>;
  handleInsertBlankBeforeOddPages: () => void | Promise<void>;
  handleInsertBlankBeforeEvenPages: () => void | Promise<void>;
  handleInsertBlankAfterOddPages: () => void | Promise<void>;
  handleInsertBlankAfterEvenPages: () => void | Promise<void>;
  handleMovePageToFirst: () => void | Promise<void>;
  handleMovePageToLast: () => void | Promise<void>;
  handleMovePageUp: () => void | Promise<void>;
  handleMovePageDown: () => void | Promise<void>;
  openSwapPagesModal: () => void;
  handleReversePages: () => void | Promise<void>;
  openReverseRangeModal: () => void;
  handleReverseOddPages: () => void | Promise<void>;
  handleReverseEvenPages: () => void | Promise<void>;
  handleMoveOddPagesToStart: () => void | Promise<void>;
  handleMoveEvenPagesToStart: () => void | Promise<void>;
  handleMoveOddPagesToEnd: () => void | Promise<void>;
  handleMoveEvenPagesToEnd: () => void | Promise<void>;
  handleSplitOddEven: () => void | Promise<void>;
  handleDuplicateAllPages: () => void | Promise<void>;
  handleDuplicatePageToEnd: () => void | Promise<void>;
  handleDuplicateOddPages: () => void | Promise<void>;
  handleDuplicateEvenPages: () => void | Promise<void>;
  handleDuplicateOddPagesBefore: () => void | Promise<void>;
  handleDuplicateEvenPagesBefore: () => void | Promise<void>;
  handleDuplicateOddPagesToEnd: () => void | Promise<void>;
  handleDuplicateEvenPagesToEnd: () => void | Promise<void>;
  handleDuplicateOddPagesToStart: () => void | Promise<void>;
  handleDuplicateEvenPagesToStart: () => void | Promise<void>;
  openDeleteModal: () => void;
  openDeleteRangeModal: () => void;
  openDeleteNthModal: () => void;
  openInsertModal: () => void;
  openMergeModal: () => void;
  openInterleaveModal: () => void;
  openPrependModal: () => void;
  openReplacePageModal: () => void;
  openSplitModal: () => void;
  openSplitAtModal: () => void;
  openSplitEveryModal: () => void;
  openExtractModal: () => void;
  openExtractOddModal: () => void;
  openExtractEvenModal: () => void;
  setViewModePdf: () => void;
  toggleMarkdownView: () => void | Promise<void>;
  handleOptimizePdf: () => void | Promise<void>;
  openExportPngModal: () => void;
  openExportPagePdfModal: () => void;
  openExportPagesPdfModal: () => void;
  openInsertImagePageModal: () => void;
  openPageNumbersModal: () => void;
  openPageHeaderModal: () => void;
  openPageFooterModal: () => void;
  openPageSizeModal: () => void;
  openWatermarkModal: () => void;
  openCropModal: () => void;
  openCropRangeModal: () => void;
  handleCropOddPages: () => void | Promise<void>;
  handleCropEvenPages: () => void | Promise<void>;
  openExpandMarginsModal: () => void;
  openShrinkMarginsModal: () => void;
  openPageBorderModal: () => void;
  openFlattenModal: () => void;
  handleFlattenAllAnnotations: () => void | Promise<void>;
  handleFlattenOddPages: () => void | Promise<void>;
  handleFlattenEvenPages: () => void | Promise<void>;
  handleSortPagesBySize: (desc: boolean) => void | Promise<void>;
  handleSortOddPagesBySize: (desc: boolean) => void | Promise<void>;
  handleSortEvenPagesBySize: (desc: boolean) => void | Promise<void>;
  handleSortPagesByRotation: (desc: boolean) => void | Promise<void>;
  handleSortOddPagesByRotation: (desc: boolean) => void | Promise<void>;
  handleSortEvenPagesByRotation: (desc: boolean) => void | Promise<void>;
  openMetadataModal: () => void | Promise<void>;
  handleSummarizePdf: () => void | Promise<void>;
  openProtectModal: () => void;
  openDecryptModal: () => void;
  openSignModal: () => void;
  toggleSignaturesPanel: () => void;
  toggleBookmarksPanel: () => void;
  toggleRedactMode: () => void;
  toggleHighlightMode: () => void;
  toggleNoteMode: () => void;
  toggleDrawMode: () => void;
  toggleShapeMode: () => void;
  toggleStampMode: () => void;
  toggleImageInsertMode: () => void;
  toggleTextEditMode: () => void;
  toggleVectorEditMode: () => void;
  openPageEditsModal: () => void;
  toggleFormsPanel: () => void;
  openTesseractGuide: () => void;
  openShortcutsHelp: () => void;
  openCommandPalette: () => void;
}

export type AppMenus = {
  menus: MenuRoot[];
  quickAccess: MenuAction[];
  allActions: FlatMenuAction[];
};
