import type { UseModalDismissOptions } from './useModalDismiss';
import { buildModalDismissSource } from './buildModalDismissSource';
import type { useAppModalState } from './useAppModalState';
import type { useSecurityFormState } from './useSecurityFormState';
import type { useAnnotationDraftState } from './useAnnotationDraftState';
import type { useHelpChromeState } from './useHelpChromeState';

type ModalState = ReturnType<typeof useAppModalState>;
type SecurityState = ReturnType<typeof useSecurityFormState>;
type AnnotationState = ReturnType<typeof useAnnotationDraftState>;
type HelpState = ReturnType<typeof useHelpChromeState>;

export type BuildModalDismissInputArgs = {
  modal: ModalState;
  security: SecurityState;
  annotation: AnnotationState;
  help: HelpState;
  unsaved: { showUnsavedModal: boolean; resolveUnsaved: UseModalDismissOptions['resolveUnsaved'] };
  browser: { showBrowserModal: boolean; setShowBrowserModal: (show: boolean) => void };
  search: { showSearchModal: boolean; closeSearchModal: () => void };
};

export function buildModalDismissInput(args: BuildModalDismissInputArgs) {
  return buildModalDismissSource({
    showUnsavedModal: args.unsaved.showUnsavedModal,
    showSaveAsModal: args.modal.showSaveAsModal,
    showMarkdownSaveAsModal: args.modal.showMarkdownSaveAsModal,
    showProtectModal: args.security.showProtectModal,
    showSignModal: args.security.showSignModal,
    showMetadataModal: args.security.showMetadataModal,
    showPasswordModal: args.security.showPasswordModal,
    showOpenModal: args.modal.showOpenModal,
    showBrowserModal: args.browser.showBrowserModal,
    showDeleteModal: args.modal.showDeleteModal,
    showSplitModal: args.modal.showSplitModal,
    showExtractModal: args.modal.showExtractModal,
    showExportPngModal: args.modal.showExportPngModal,
    showDeleteRangeModal: args.modal.showDeleteRangeModal,
    showPageNumbersModal: args.modal.showPageNumbersModal,
    showWatermarkModal: args.modal.showWatermarkModal,
    showCropModal: args.modal.showCropModal,
    showFlattenModal: args.modal.showFlattenModal,
    showAddBookmarkModal: args.modal.showAddBookmarkModal,
    showRenameBookmarkModal: args.modal.showRenameBookmarkModal,
    showDuplicateRangeModal: args.modal.showDuplicateRangeModal,
    showPageHeaderModal: args.modal.showPageHeaderModal,
    showPageFooterModal: args.modal.showPageFooterModal,
    showSwapPagesModal: args.modal.showSwapPagesModal,
    showReplacePageModal: args.modal.showReplacePageModal,
    showInterleaveModal: args.modal.showInterleaveModal,
    showPageSizeModal: args.modal.showPageSizeModal,
    showDecryptModal: args.security.showDecryptModal,
    showRotateRangeModal: args.modal.showRotateRangeModal,
    showKeepRangeModal: args.modal.showKeepRangeModal,
    showMoveRangeModal: args.modal.showMoveRangeModal,
    showPrependModal: args.modal.showPrependModal,
    showSplitEveryModal: args.modal.showSplitEveryModal,
    showPageBorderModal: args.modal.showPageBorderModal,
    showBookmarkAllModal: args.modal.showBookmarkAllModal,
    showExpandMarginsModal: args.modal.showExpandMarginsModal,
    showShrinkMarginsModal: args.modal.showShrinkMarginsModal,
    showDeleteNthModal: args.modal.showDeleteNthModal,
    showExtractOddModal: args.modal.showExtractOddModal,
    showExtractEvenModal: args.modal.showExtractEvenModal,
    showSplitAtModal: args.modal.showSplitAtModal,
    showReverseRangeModal: args.modal.showReverseRangeModal,
    showInsertBlankPagesModal: args.modal.showInsertBlankPagesModal,
    showCropRangeModal: args.modal.showCropRangeModal,
    showParityRangeModal: args.modal.showParityRangeModal,
    showExportPagesPdfModal: args.modal.showExportPagesPdfModal,
    showInsertImagePageModal: args.modal.showInsertImagePageModal,
    showExportPagePdfModal: args.modal.showExportPagePdfModal,
    showInsertModal: args.modal.showInsertModal,
    showMergeModal: args.modal.showMergeModal,
    showSearchModal: args.search.showSearchModal,
    showNoteModal: args.annotation.showNoteModal,
    showImageInsertModal: args.annotation.showImageInsertModal,
    showAddFormFieldModal: args.annotation.showAddFormFieldModal,
    showSummaryModal: args.modal.showSummaryModal,
    showPageTextModal: args.annotation.showPageTextModal,
    showPageEditsModal: args.annotation.showPageEditsModal,
    showCommandPalette: args.help.showCommandPalette,
    showShortcutsHelp: args.help.showShortcutsHelp,
    showLicenses: args.help.showLicenses,
    showCredits: args.help.showCredits,
    showAbout: args.help.showAbout,
    showTesseractModal: args.help.showTesseractModal,
    closeSearchModal: args.search.closeSearchModal,
    resolveUnsaved: args.unsaved.resolveUnsaved,
    setShowSaveAsModal: args.modal.setShowSaveAsModal,
    setShowMarkdownSaveAsModal: args.modal.setShowMarkdownSaveAsModal,
    setShowProtectModal: args.security.setShowProtectModal,
    setShowSignModal: args.security.setShowSignModal,
    setShowMetadataModal: args.security.setShowMetadataModal,
    setShowPasswordModal: args.security.setShowPasswordModal,
    setPendingEncryptedPath: args.security.setPendingEncryptedPath,
    setPdfPasswordDraft: args.security.setPdfPasswordDraft,
    setShowOpenModal: args.modal.setShowOpenModal,
    setShowBrowserModal: args.browser.setShowBrowserModal,
    setShowDeleteModal: args.modal.setShowDeleteModal,
    setShowSplitModal: args.modal.setShowSplitModal,
    setShowExtractModal: args.modal.setShowExtractModal,
    setShowExportPngModal: args.modal.setShowExportPngModal,
    setShowDeleteRangeModal: args.modal.setShowDeleteRangeModal,
    setShowPageNumbersModal: args.modal.setShowPageNumbersModal,
    setShowWatermarkModal: args.modal.setShowWatermarkModal,
    setShowCropModal: args.modal.setShowCropModal,
    setShowFlattenModal: args.modal.setShowFlattenModal,
    setShowAddBookmarkModal: args.modal.setShowAddBookmarkModal,
    setShowRenameBookmarkModal: args.modal.setShowRenameBookmarkModal,
    setShowDuplicateRangeModal: args.modal.setShowDuplicateRangeModal,
    setShowPageHeaderModal: args.modal.setShowPageHeaderModal,
    setShowPageFooterModal: args.modal.setShowPageFooterModal,
    setShowSwapPagesModal: args.modal.setShowSwapPagesModal,
    setShowReplacePageModal: args.modal.setShowReplacePageModal,
    setShowInterleaveModal: args.modal.setShowInterleaveModal,
    setShowPageSizeModal: args.modal.setShowPageSizeModal,
    setShowDecryptModal: args.security.setShowDecryptModal,
    setShowRotateRangeModal: args.modal.setShowRotateRangeModal,
    setShowKeepRangeModal: args.modal.setShowKeepRangeModal,
    setShowMoveRangeModal: args.modal.setShowMoveRangeModal,
    setShowPrependModal: args.modal.setShowPrependModal,
    setShowSplitEveryModal: args.modal.setShowSplitEveryModal,
    setShowPageBorderModal: args.modal.setShowPageBorderModal,
    setShowBookmarkAllModal: args.modal.setShowBookmarkAllModal,
    setShowExpandMarginsModal: args.modal.setShowExpandMarginsModal,
    setShowReverseRangeModal: args.modal.setShowReverseRangeModal,
    setShowInsertBlankPagesModal: args.modal.setShowInsertBlankPagesModal,
    setShowCropRangeModal: args.modal.setShowCropRangeModal,
    setShowExportPagesPdfModal: args.modal.setShowExportPagesPdfModal,
    setShowInsertImagePageModal: args.modal.setShowInsertImagePageModal,
    setShowExportPagePdfModal: args.modal.setShowExportPagePdfModal,
    setShowInsertModal: args.modal.setShowInsertModal,
    setInsertFilePath: args.modal.setInsertFilePath,
    setShowMergeModal: args.modal.setShowMergeModal,
    setMergeFilePath: args.modal.setMergeFilePath,
    setShowImageInsertModal: args.annotation.setShowImageInsertModal,
    setShowAddFormFieldModal: args.annotation.setShowAddFormFieldModal,
    setShowSummaryModal: args.modal.setShowSummaryModal,
    setShowPageTextModal: args.annotation.setShowPageTextModal,
    setEditingTextIndex: args.annotation.setEditingTextIndex,
    setPendingTextPos: args.annotation.setPendingTextPos,
    setShowPageEditsModal: args.annotation.setShowPageEditsModal,
    setShowCommandPalette: args.help.setShowCommandPalette,
    setShowShortcutsHelp: args.help.setShowShortcutsHelp,
    setShowLicenses: args.help.setShowLicenses,
    setShowCredits: args.help.setShowCredits,
    setShowAbout: args.help.setShowAbout,
    setShowTesseractModal: args.help.setShowTesseractModal,
  } satisfies UseModalDismissOptions);
}
