// Auto-generated by scripts/gen-parity-docmod.py — do not edit.

fn parity_docmod_match(page_index: u32, modulus: u32, remainder: u32) -> bool {
    page_index % modulus == remainder
}

fn parity_docmod_indices(total: u32, modulus: u32, remainder: u32) -> Vec<u32> {
    (0..total).filter(|i| parity_docmod_match(*i, modulus, remainder)).collect()
}

fn parity_docmod_rotate(path: &Path, modulus: u32, remainder: u32, delta: i64) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut rotated = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let current = page_rotation(&doc, page_id);
        set_page_rotation(&mut doc, page_id, current + delta)?;
        rotated += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(rotated)
}

fn parity_docmod_reset_rotation(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut reset = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        set_page_rotation(&mut doc, page_id, 0)?;
        reset += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(reset)
}

fn parity_docmod_delete(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let total = kids.len();
    let mut to_delete: Vec<usize> = (0..total)
        .filter(|i| parity_docmod_match(*i as u32, modulus, remainder))
        .collect();
    if to_delete.is_empty() {
        return Ok(0);
    }
    if to_delete.len() >= total {
        return Err("Cannot delete every page in the document".to_string());
    }
    to_delete.sort_by(|a, b| b.cmp(a));
    let deleted = to_delete.len() as u32;
    for idx in to_delete {
        kids.remove(idx);
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_docmod_keep(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (kids, _) = get_pages_kids(&doc)?;
    let kept: Vec<Object> = kids
        .iter()
        .enumerate()
        .filter(|(i, _)| parity_docmod_match(*i as u32, modulus, remainder))
        .map(|(_, kid)| kid.clone())
        .collect();
    if kept.is_empty() {
        return Err(format!("Document has no pages matching mod-{modulus} remainder {remainder}"));
    }
    if kept.len() == kids.len() {
        return Err("Nothing to delete — all pages match the keep filter".to_string());
    }
    let deleted = (kids.len() - kept.len()) as u32;
    set_pages_kids(&mut doc, pages_ref, kept)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_docmod_dup_append(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let path_buf = PathBuf::from(path);
    let total = Document::load(&path_buf).map_err(|e| e.to_string())?.get_pages().len() as u32;
    let indices = parity_docmod_indices(total, modulus, remainder);
    if indices.is_empty() {
        return Ok(0);
    }
    let path_str = path_buf.to_string_lossy().into_owned();
    let copied = indices.len() as u32;
    for idx in indices {
        let at = Document::load(&path_buf).map_err(|e| e.to_string())?.get_pages().len() as u32;
        insert_pdf(path_str.clone(), path_str.clone(), at, idx, idx)?;
    }
    Ok(copied)
}

fn parity_docmod_flatten(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut removed = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let count = doc
            .get_dictionary(page_id)
            .ok()
            .and_then(|d| d.get(b"Annots").ok())
            .and_then(|o| o.as_array().ok())
            .map(|a| a.len() as u32)
            .unwrap_or(0);
        if count > 0 {
            doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"Annots");
            removed += count;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(removed)
}

#[allow(clippy::too_many_arguments)]
fn parity_docmod_crop(path: &Path, modulus: u32, remainder: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut cropped = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_crop_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        cropped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cropped)
}

#[allow(clippy::too_many_arguments)]
fn parity_docmod_expand(path: &Path, modulus: u32, remainder: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut expanded = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_expand_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        expanded += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(expanded)
}

#[allow(clippy::too_many_arguments)]
fn parity_docmod_shrink(path: &Path, modulus: u32, remainder: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut shrunk = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_shrink_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        shrunk += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(shrunk)
}

fn parity_docmod_reverse(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (0..kids.len())
        .filter(|i| parity_docmod_match(*i as u32, modulus, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut parity_kids: Vec<Object> = parity_indices.iter().map(|i| kids[*i].clone()).collect();
    parity_kids.reverse();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = parity_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_docmod_move_to_start(path: &Path, modulus: u32, remainder: u32) -> Result<(), String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (kids, _) = get_pages_kids(&doc)?;
    let mut matched = Vec::new();
    let mut rest = Vec::new();
    for (i, kid) in kids.into_iter().enumerate() {
        if parity_docmod_match(i as u32, modulus, remainder) {
            matched.push(kid);
        } else {
            rest.push(kid);
        }
    }
    set_pages_kids(&mut doc, pages_ref, matched.into_iter().chain(rest).collect())?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(())
}

fn parity_docmod_move_to_end(path: &Path, modulus: u32, remainder: u32) -> Result<(), String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (kids, _) = get_pages_kids(&doc)?;
    let mut matched = Vec::new();
    let mut rest = Vec::new();
    for (i, kid) in kids.into_iter().enumerate() {
        if parity_docmod_match(i as u32, modulus, remainder) {
            matched.push(kid);
        } else {
            rest.push(kid);
        }
    }
    set_pages_kids(&mut doc, pages_ref, rest.into_iter().chain(matched).collect())?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(())
}

fn parity_docmod_clear_crop(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut cleared = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        if doc.get_dictionary(page_id).ok().and_then(|d| d.get(b"CropBox").ok()).is_some() {
            doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"CropBox");
            cleared += 1;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cleared)
}

fn parity_docmod_dup_before(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let path_buf = PathBuf::from(path);
    let total = Document::load(&path_buf).map_err(|e| e.to_string())?.get_pages().len() as u32;
    let indices = parity_docmod_indices(total, modulus, remainder);
    if indices.is_empty() {
        return Ok(0);
    }
    let path_str = path_buf.to_string_lossy().into_owned();
    let copied = indices.len() as u32;
    for idx in indices.into_iter().rev() {
        insert_pdf(path_str.clone(), path_str.clone(), idx, idx, idx)?;
    }
    Ok(copied)
}

fn parity_docmod_sort_rotation(path: &Path, modulus: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (0..kids.len())
        .filter(|i| parity_docmod_match(*i as u32, modulus, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, i64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let rot = kid.as_reference().ok().map(|id| page_rotation(&doc, id).rem_euclid(360)).unwrap_or(0);
            (*i, rot, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.cmp(&b.1);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_docmod_sort_size(path: &Path, modulus: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (0..kids.len())
        .filter(|i| parity_docmod_match(*i as u32, modulus, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, f64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let area = kid
                .as_reference()
                .ok()
                .and_then(|id| page_media_box(&doc, id).ok())
                .map(|m| (m[2] - m[0]) * (m[3] - m[1]))
                .unwrap_or(0.0);
            (*i, area, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_docmod_page_numbers(path: &Path, modulus: u32, remainder: u32, prefix: Option<String>) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let prefix = prefix.unwrap_or_default();
    let total = doc.get_pages().len() as u32;
    let mut stamped = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 1100.0)?;
        let label = format!("{prefix}{}", page_index + 1);
        let ops = build_page_number_ops(&font_name, &label, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_docmod_watermark(path: &Path, modulus: u32, remainder: u32, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Watermark text cannot be empty".to_string());
    }
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut stamped = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (cx, cy) = viewer_point_to_pdf(&doc, page_id, 400.0, 566.0)?;
        let ops = build_watermark_ops(&font_name, trimmed, cx, cy);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_docmod_header(path: &Path, modulus: u32, remainder: u32, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Header text cannot be empty".to_string());
    }
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut stamped = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 40.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_docmod_footer(path: &Path, modulus: u32, remainder: u32, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Footer text cannot be empty".to_string());
    }
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut stamped = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 1100.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_docmod_border(path: &Path, modulus: u32, remainder: u32, inset: f64) -> Result<u32, String> {
    if inset < 0.0 {
        return Err("Border inset must be non-negative".to_string());
    }
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut drawn = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let ops = build_page_border_ops(&doc, page_id, inset)?;
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        drawn += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(drawn)
}

fn parity_docmod_bookmark(path: &Path, modulus: u32, remainder: u32, prefix: Option<String>) -> Result<u32, String> {
    let prefix = prefix.unwrap_or_else(|| "Page ".to_string());
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut count = 0u32;
    for (page_num, page_id) in doc.get_pages() {
        let page_index = page_num - 1;
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let title = format!("{prefix}{page_num}");
        append_outline_item(&mut doc, &title, page_id)?;
        count += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(count)
}

fn parity_docmod_page_size(path: &Path, modulus: u32, remainder: u32, preset: &str) -> Result<u32, String> {
    let (w, h) = page_size_preset_dims(preset)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let total = doc.get_pages().len() as u32;
    let mut resized = 0u32;
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let page = doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?;
        page.set(
            "MediaBox",
            Object::Array(vec![Object::Integer(0), Object::Integer(0), Object::Real(w as f32), Object::Real(h as f32)]),
        );
        page.remove(b"CropBox");
        resized += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(resized)
}

fn parity_docmod_blank(path: &Path, modulus: u32, remainder: u32, after: bool) -> Result<u32, String> {
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let indices: Vec<usize> = (0..kids.len())
        .filter(|i| parity_docmod_match(*i as u32, modulus, remainder))
        .collect();
    if indices.is_empty() {
        return Ok(0);
    }
    for &idx in indices.iter().rev() {
        let page_id = create_blank_page(&mut doc, pages_ref);
        let at = if after { idx + 1 } else { idx };
        kids.insert(at, Object::Reference(page_id));
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(indices.len() as u32)
}

fn parity_docmod_dup_to_end(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let path_buf = PathBuf::from(path);
    let total = Document::load(&path_buf).map_err(|e| e.to_string())?.get_pages().len() as u32;
    let indices = parity_docmod_indices(total, modulus, remainder);
    if indices.is_empty() {
        return Ok(0);
    }
    let path_str = path_buf.to_string_lossy().into_owned();
    let copied = indices.len() as u32;
    for idx in indices.into_iter().rev() {
        let new_idx = duplicate_page(path_str.clone(), idx)?;
        move_page_to_last(path_str.clone(), new_idx)?;
    }
    Ok(copied)
}

fn parity_docmod_dup_to_start(path: &Path, modulus: u32, remainder: u32) -> Result<u32, String> {
    let path_buf = PathBuf::from(path);
    let total = Document::load(&path_buf).map_err(|e| e.to_string())?.get_pages().len() as u32;
    let indices = parity_docmod_indices(total, modulus, remainder);
    if indices.is_empty() {
        return Ok(0);
    }
    let path_str = path_buf.to_string_lossy().into_owned();
    let copied = indices.len() as u32;
    for (offset, idx) in indices.into_iter().rev().enumerate() {
        let offset = offset as u32;
        let source = idx + offset;
        insert_pdf(path_str.clone(), path_str.clone(), offset, source, source)?;
    }
    Ok(copied)
}

fn parity_docmod_extract(path: &Path, output_path: &Path, modulus: u32, remainder: u32) -> Result<String, String> {
    if path == output_path {
        return Err("Output path must differ from the source PDF".to_string());
    }
    let doc = Document::load(path).map_err(|e| e.to_string())?;
    let (all_kids, pages_ref) = get_pages_kids(&doc)?;
    let subset: Vec<Object> = all_kids
        .iter()
        .enumerate()
        .filter(|(i, _)| parity_docmod_match(*i as u32, modulus, remainder))
        .map(|(_, kid)| kid.clone())
        .collect();
    if subset.is_empty() {
        return Err(format!("Document has no pages matching mod-{modulus} remainder {remainder}"));
    }
    let mut out = Document::load(path).map_err(|e| e.to_string())?;
    set_pages_kids(&mut out, pages_ref, subset)?;
    out.prune_objects();
    if let Some(parent) = output_path.parent() {
        if !parent.as_os_str().is_empty() {
            fs::create_dir_all(parent).map_err(|e| e.to_string())?;
        }
    }
    out.save(output_path).map_err(|e| e.to_string())?;
    Ok(output_path.to_string_lossy().into_owned())
}

fn parity_docmod_export_pdf(path: &Path, output_dir: &Path, modulus: u32, remainder: u32) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    let total = Document::load(path).map_err(|e| e.to_string())?.get_pages().len() as u32;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let path_str = path.to_string_lossy().into_owned();
    let mut written = Vec::new();
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let file_name = format!("page-{:03}.pdf", page_index + 1);
        let output_path = output_dir.join(file_name);
        let out = extract_pdf_pages(path_str.clone(), output_path.to_string_lossy().into_owned(), page_index, page_index)?;
        written.push(out);
    }
    Ok(written)
}

fn parity_docmod_export_rendered(path: &Path, output_dir: &Path, modulus: u32, remainder: u32, ext: &str, render: ParityPageRenderFn) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    let total = Document::load(path).map_err(|e| e.to_string())?.get_pages().len() as u32;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let mut written = Vec::new();
    for page_index in 0..total {
        if !parity_docmod_match(page_index, modulus, remainder) {
            continue;
        }
        let bytes = render(path, page_index, EXPORT_PNG_W, EXPORT_PNG_H)?;
        let file_name = format!("page-{:03}.{ext}", page_index + 1);
        let output_path = output_dir.join(file_name);
        write_png_output(&output_path, &bytes)?;
        written.push(output_path.to_string_lossy().into_owned());
    }
    Ok(written)
}


/// Document-wide mod-3 remainder 0 — rotate_cw
#[tauri::command]
fn rotate_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 3, 0, 90)
}


/// Document-wide mod-3 remainder 0 — rotate_ccw
#[tauri::command]
fn rotate_mod3_0_pages_ccw(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 3, 0, -90)
}


/// Document-wide mod-3 remainder 0 — rotate_180
#[tauri::command]
fn rotate_180_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 3, 0, 180)
}


/// Document-wide mod-3 remainder 0 — reset_rot
#[tauri::command]
fn reset_rotation_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_reset_rotation(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — delete
#[tauri::command]
fn delete_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_delete(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — keep
#[tauri::command]
fn keep_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_keep(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — dup_append
#[tauri::command]
fn duplicate_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_dup_append(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — flatten
#[tauri::command]
fn flatten_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_flatten(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — crop
#[tauri::command]
fn crop_mod3_0_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_crop(&PathBuf::from(&path), 3, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-3 remainder 0 — expand
#[tauri::command]
fn expand_mod3_0_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_expand(&PathBuf::from(&path), 3, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-3 remainder 0 — shrink
#[tauri::command]
fn shrink_mod3_0_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_shrink(&PathBuf::from(&path), 3, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-3 remainder 0 — reverse
#[tauri::command]
fn reverse_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_reverse(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — move_start
#[tauri::command]
fn move_mod3_0_pages_to_start(path: String) -> Result<(), String> {
    parity_docmod_move_to_start(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — move_end
#[tauri::command]
fn move_mod3_0_pages_to_end(path: String) -> Result<(), String> {
    parity_docmod_move_to_end(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — clear_crop
#[tauri::command]
fn clear_crop_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_clear_crop(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — dup_before
#[tauri::command]
fn duplicate_mod3_0_pages_before(path: String) -> Result<u32, String> {
    parity_docmod_dup_before(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — sort_rot
#[tauri::command]
fn sort_mod3_0_pages_by_rotation(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_rotation(&PathBuf::from(&path), 3, 0, descending)
}


/// Document-wide mod-3 remainder 0 — sort_size
#[tauri::command]
fn sort_mod3_0_pages_by_size(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_size(&PathBuf::from(&path), 3, 0, descending)
}


/// Document-wide mod-3 remainder 0 — page_numbers
#[tauri::command]
fn add_page_numbers_mod3_0_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_page_numbers(&PathBuf::from(&path), 3, 0, prefix)
}


/// Document-wide mod-3 remainder 0 — watermark
#[tauri::command]
fn add_text_watermark_mod3_0_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_watermark(&PathBuf::from(&path), 3, 0, &text)
}


/// Document-wide mod-3 remainder 0 — header
#[tauri::command]
fn add_page_header_mod3_0_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_header(&PathBuf::from(&path), 3, 0, &text)
}


/// Document-wide mod-3 remainder 0 — footer
#[tauri::command]
fn add_page_footer_mod3_0_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_footer(&PathBuf::from(&path), 3, 0, &text)
}


/// Document-wide mod-3 remainder 0 — border
#[tauri::command]
fn add_page_border_mod3_0_pages(path: String, inset: f64) -> Result<u32, String> {
    parity_docmod_border(&PathBuf::from(&path), 3, 0, inset)
}


/// Document-wide mod-3 remainder 0 — bookmark
#[tauri::command]
fn bookmark_mod3_0_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_bookmark(&PathBuf::from(&path), 3, 0, prefix)
}


/// Document-wide mod-3 remainder 0 — page_size
#[tauri::command]
fn set_page_size_mod3_0_pages(path: String, preset: String) -> Result<u32, String> {
    parity_docmod_page_size(&PathBuf::from(&path), 3, 0, &preset)
}


/// Document-wide mod-3 remainder 0 — blank_before
#[tauri::command]
fn insert_blank_before_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 3, 0, false)
}


/// Document-wide mod-3 remainder 0 — blank_after
#[tauri::command]
fn insert_blank_after_mod3_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 3, 0, true)
}


/// Document-wide mod-3 remainder 0 — dup_to_end
#[tauri::command]
fn duplicate_mod3_0_pages_to_end(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_end(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — dup_to_start
#[tauri::command]
fn duplicate_mod3_0_pages_to_start(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_start(&PathBuf::from(&path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — extract
#[tauri::command]
fn extract_mod3_0_pages(path: String, output_path: String) -> Result<String, String> {
    parity_docmod_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), 3, 0)
}


/// Document-wide mod-3 remainder 0 — export_pdf
#[tauri::command]
fn export_mod3_0_pages_as_pdf(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0)
}


/// Document-wide mod-3 remainder 0 — export_png
#[tauri::command]
fn export_mod3_0_pages_png(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0, "png", render_page_png)
}


/// Document-wide mod-3 remainder 0 — export_jpeg
#[tauri::command]
fn export_mod3_0_pages_jpeg(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0, "jpeg", render_page_jpeg)
}


/// Document-wide mod-3 remainder 0 — export_webp
#[tauri::command]
fn export_mod3_0_pages_webp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0, "webp", render_page_webp)
}


/// Document-wide mod-3 remainder 0 — export_bmp
#[tauri::command]
fn export_mod3_0_pages_bmp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0, "bmp", render_page_bmp)
}


/// Document-wide mod-3 remainder 0 — export_tiff
#[tauri::command]
fn export_mod3_0_pages_tiff(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0, "tiff", render_page_tiff)
}


/// Document-wide mod-3 remainder 0 — export_gif
#[tauri::command]
fn export_mod3_0_pages_gif(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0, "gif", render_page_gif)
}


/// Document-wide mod-3 remainder 0 — export_ppm
#[tauri::command]
fn export_mod3_0_pages_ppm(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0, "ppm", render_page_ppm)
}


/// Document-wide mod-3 remainder 0 — export_tga
#[tauri::command]
fn export_mod3_0_pages_tga(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0, "tga", render_page_tga)
}


/// Document-wide mod-3 remainder 0 — export_ico
#[tauri::command]
fn export_mod3_0_pages_ico(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 0, "ico", render_page_ico)
}


/// Document-wide mod-3 remainder 1 — rotate_cw
#[tauri::command]
fn rotate_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 3, 1, 90)
}


/// Document-wide mod-3 remainder 1 — rotate_ccw
#[tauri::command]
fn rotate_mod3_1_pages_ccw(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 3, 1, -90)
}


/// Document-wide mod-3 remainder 1 — rotate_180
#[tauri::command]
fn rotate_180_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 3, 1, 180)
}


/// Document-wide mod-3 remainder 1 — reset_rot
#[tauri::command]
fn reset_rotation_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_reset_rotation(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — delete
#[tauri::command]
fn delete_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_delete(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — keep
#[tauri::command]
fn keep_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_keep(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — dup_append
#[tauri::command]
fn duplicate_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_dup_append(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — flatten
#[tauri::command]
fn flatten_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_flatten(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — crop
#[tauri::command]
fn crop_mod3_1_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_crop(&PathBuf::from(&path), 3, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-3 remainder 1 — expand
#[tauri::command]
fn expand_mod3_1_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_expand(&PathBuf::from(&path), 3, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-3 remainder 1 — shrink
#[tauri::command]
fn shrink_mod3_1_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_shrink(&PathBuf::from(&path), 3, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-3 remainder 1 — reverse
#[tauri::command]
fn reverse_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_reverse(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — move_start
#[tauri::command]
fn move_mod3_1_pages_to_start(path: String) -> Result<(), String> {
    parity_docmod_move_to_start(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — move_end
#[tauri::command]
fn move_mod3_1_pages_to_end(path: String) -> Result<(), String> {
    parity_docmod_move_to_end(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — clear_crop
#[tauri::command]
fn clear_crop_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_clear_crop(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — dup_before
#[tauri::command]
fn duplicate_mod3_1_pages_before(path: String) -> Result<u32, String> {
    parity_docmod_dup_before(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — sort_rot
#[tauri::command]
fn sort_mod3_1_pages_by_rotation(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_rotation(&PathBuf::from(&path), 3, 1, descending)
}


/// Document-wide mod-3 remainder 1 — sort_size
#[tauri::command]
fn sort_mod3_1_pages_by_size(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_size(&PathBuf::from(&path), 3, 1, descending)
}


/// Document-wide mod-3 remainder 1 — page_numbers
#[tauri::command]
fn add_page_numbers_mod3_1_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_page_numbers(&PathBuf::from(&path), 3, 1, prefix)
}


/// Document-wide mod-3 remainder 1 — watermark
#[tauri::command]
fn add_text_watermark_mod3_1_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_watermark(&PathBuf::from(&path), 3, 1, &text)
}


/// Document-wide mod-3 remainder 1 — header
#[tauri::command]
fn add_page_header_mod3_1_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_header(&PathBuf::from(&path), 3, 1, &text)
}


/// Document-wide mod-3 remainder 1 — footer
#[tauri::command]
fn add_page_footer_mod3_1_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_footer(&PathBuf::from(&path), 3, 1, &text)
}


/// Document-wide mod-3 remainder 1 — border
#[tauri::command]
fn add_page_border_mod3_1_pages(path: String, inset: f64) -> Result<u32, String> {
    parity_docmod_border(&PathBuf::from(&path), 3, 1, inset)
}


/// Document-wide mod-3 remainder 1 — bookmark
#[tauri::command]
fn bookmark_mod3_1_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_bookmark(&PathBuf::from(&path), 3, 1, prefix)
}


/// Document-wide mod-3 remainder 1 — page_size
#[tauri::command]
fn set_page_size_mod3_1_pages(path: String, preset: String) -> Result<u32, String> {
    parity_docmod_page_size(&PathBuf::from(&path), 3, 1, &preset)
}


/// Document-wide mod-3 remainder 1 — blank_before
#[tauri::command]
fn insert_blank_before_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 3, 1, false)
}


/// Document-wide mod-3 remainder 1 — blank_after
#[tauri::command]
fn insert_blank_after_mod3_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 3, 1, true)
}


/// Document-wide mod-3 remainder 1 — dup_to_end
#[tauri::command]
fn duplicate_mod3_1_pages_to_end(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_end(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — dup_to_start
#[tauri::command]
fn duplicate_mod3_1_pages_to_start(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_start(&PathBuf::from(&path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — extract
#[tauri::command]
fn extract_mod3_1_pages(path: String, output_path: String) -> Result<String, String> {
    parity_docmod_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), 3, 1)
}


/// Document-wide mod-3 remainder 1 — export_pdf
#[tauri::command]
fn export_mod3_1_pages_as_pdf(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1)
}


/// Document-wide mod-3 remainder 1 — export_png
#[tauri::command]
fn export_mod3_1_pages_png(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1, "png", render_page_png)
}


/// Document-wide mod-3 remainder 1 — export_jpeg
#[tauri::command]
fn export_mod3_1_pages_jpeg(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1, "jpeg", render_page_jpeg)
}


/// Document-wide mod-3 remainder 1 — export_webp
#[tauri::command]
fn export_mod3_1_pages_webp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1, "webp", render_page_webp)
}


/// Document-wide mod-3 remainder 1 — export_bmp
#[tauri::command]
fn export_mod3_1_pages_bmp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1, "bmp", render_page_bmp)
}


/// Document-wide mod-3 remainder 1 — export_tiff
#[tauri::command]
fn export_mod3_1_pages_tiff(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1, "tiff", render_page_tiff)
}


/// Document-wide mod-3 remainder 1 — export_gif
#[tauri::command]
fn export_mod3_1_pages_gif(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1, "gif", render_page_gif)
}


/// Document-wide mod-3 remainder 1 — export_ppm
#[tauri::command]
fn export_mod3_1_pages_ppm(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1, "ppm", render_page_ppm)
}


/// Document-wide mod-3 remainder 1 — export_tga
#[tauri::command]
fn export_mod3_1_pages_tga(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1, "tga", render_page_tga)
}


/// Document-wide mod-3 remainder 1 — export_ico
#[tauri::command]
fn export_mod3_1_pages_ico(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 1, "ico", render_page_ico)
}


/// Document-wide mod-3 remainder 2 — rotate_cw
#[tauri::command]
fn rotate_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 3, 2, 90)
}


/// Document-wide mod-3 remainder 2 — rotate_ccw
#[tauri::command]
fn rotate_mod3_2_pages_ccw(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 3, 2, -90)
}


/// Document-wide mod-3 remainder 2 — rotate_180
#[tauri::command]
fn rotate_180_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 3, 2, 180)
}


/// Document-wide mod-3 remainder 2 — reset_rot
#[tauri::command]
fn reset_rotation_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_reset_rotation(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — delete
#[tauri::command]
fn delete_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_delete(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — keep
#[tauri::command]
fn keep_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_keep(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — dup_append
#[tauri::command]
fn duplicate_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_dup_append(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — flatten
#[tauri::command]
fn flatten_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_flatten(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — crop
#[tauri::command]
fn crop_mod3_2_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_crop(&PathBuf::from(&path), 3, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-3 remainder 2 — expand
#[tauri::command]
fn expand_mod3_2_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_expand(&PathBuf::from(&path), 3, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-3 remainder 2 — shrink
#[tauri::command]
fn shrink_mod3_2_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_shrink(&PathBuf::from(&path), 3, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-3 remainder 2 — reverse
#[tauri::command]
fn reverse_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_reverse(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — move_start
#[tauri::command]
fn move_mod3_2_pages_to_start(path: String) -> Result<(), String> {
    parity_docmod_move_to_start(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — move_end
#[tauri::command]
fn move_mod3_2_pages_to_end(path: String) -> Result<(), String> {
    parity_docmod_move_to_end(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — clear_crop
#[tauri::command]
fn clear_crop_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_clear_crop(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — dup_before
#[tauri::command]
fn duplicate_mod3_2_pages_before(path: String) -> Result<u32, String> {
    parity_docmod_dup_before(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — sort_rot
#[tauri::command]
fn sort_mod3_2_pages_by_rotation(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_rotation(&PathBuf::from(&path), 3, 2, descending)
}


/// Document-wide mod-3 remainder 2 — sort_size
#[tauri::command]
fn sort_mod3_2_pages_by_size(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_size(&PathBuf::from(&path), 3, 2, descending)
}


/// Document-wide mod-3 remainder 2 — page_numbers
#[tauri::command]
fn add_page_numbers_mod3_2_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_page_numbers(&PathBuf::from(&path), 3, 2, prefix)
}


/// Document-wide mod-3 remainder 2 — watermark
#[tauri::command]
fn add_text_watermark_mod3_2_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_watermark(&PathBuf::from(&path), 3, 2, &text)
}


/// Document-wide mod-3 remainder 2 — header
#[tauri::command]
fn add_page_header_mod3_2_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_header(&PathBuf::from(&path), 3, 2, &text)
}


/// Document-wide mod-3 remainder 2 — footer
#[tauri::command]
fn add_page_footer_mod3_2_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_footer(&PathBuf::from(&path), 3, 2, &text)
}


/// Document-wide mod-3 remainder 2 — border
#[tauri::command]
fn add_page_border_mod3_2_pages(path: String, inset: f64) -> Result<u32, String> {
    parity_docmod_border(&PathBuf::from(&path), 3, 2, inset)
}


/// Document-wide mod-3 remainder 2 — bookmark
#[tauri::command]
fn bookmark_mod3_2_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_bookmark(&PathBuf::from(&path), 3, 2, prefix)
}


/// Document-wide mod-3 remainder 2 — page_size
#[tauri::command]
fn set_page_size_mod3_2_pages(path: String, preset: String) -> Result<u32, String> {
    parity_docmod_page_size(&PathBuf::from(&path), 3, 2, &preset)
}


/// Document-wide mod-3 remainder 2 — blank_before
#[tauri::command]
fn insert_blank_before_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 3, 2, false)
}


/// Document-wide mod-3 remainder 2 — blank_after
#[tauri::command]
fn insert_blank_after_mod3_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 3, 2, true)
}


/// Document-wide mod-3 remainder 2 — dup_to_end
#[tauri::command]
fn duplicate_mod3_2_pages_to_end(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_end(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — dup_to_start
#[tauri::command]
fn duplicate_mod3_2_pages_to_start(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_start(&PathBuf::from(&path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — extract
#[tauri::command]
fn extract_mod3_2_pages(path: String, output_path: String) -> Result<String, String> {
    parity_docmod_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), 3, 2)
}


/// Document-wide mod-3 remainder 2 — export_pdf
#[tauri::command]
fn export_mod3_2_pages_as_pdf(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2)
}


/// Document-wide mod-3 remainder 2 — export_png
#[tauri::command]
fn export_mod3_2_pages_png(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2, "png", render_page_png)
}


/// Document-wide mod-3 remainder 2 — export_jpeg
#[tauri::command]
fn export_mod3_2_pages_jpeg(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2, "jpeg", render_page_jpeg)
}


/// Document-wide mod-3 remainder 2 — export_webp
#[tauri::command]
fn export_mod3_2_pages_webp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2, "webp", render_page_webp)
}


/// Document-wide mod-3 remainder 2 — export_bmp
#[tauri::command]
fn export_mod3_2_pages_bmp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2, "bmp", render_page_bmp)
}


/// Document-wide mod-3 remainder 2 — export_tiff
#[tauri::command]
fn export_mod3_2_pages_tiff(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2, "tiff", render_page_tiff)
}


/// Document-wide mod-3 remainder 2 — export_gif
#[tauri::command]
fn export_mod3_2_pages_gif(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2, "gif", render_page_gif)
}


/// Document-wide mod-3 remainder 2 — export_ppm
#[tauri::command]
fn export_mod3_2_pages_ppm(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2, "ppm", render_page_ppm)
}


/// Document-wide mod-3 remainder 2 — export_tga
#[tauri::command]
fn export_mod3_2_pages_tga(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2, "tga", render_page_tga)
}


/// Document-wide mod-3 remainder 2 — export_ico
#[tauri::command]
fn export_mod3_2_pages_ico(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 3, 2, "ico", render_page_ico)
}


/// Document-wide mod-4 remainder 0 — rotate_cw
#[tauri::command]
fn rotate_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 0, 90)
}


/// Document-wide mod-4 remainder 0 — rotate_ccw
#[tauri::command]
fn rotate_mod4_0_pages_ccw(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 0, -90)
}


/// Document-wide mod-4 remainder 0 — rotate_180
#[tauri::command]
fn rotate_180_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 0, 180)
}


/// Document-wide mod-4 remainder 0 — reset_rot
#[tauri::command]
fn reset_rotation_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_reset_rotation(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — delete
#[tauri::command]
fn delete_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_delete(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — keep
#[tauri::command]
fn keep_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_keep(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — dup_append
#[tauri::command]
fn duplicate_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_dup_append(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — flatten
#[tauri::command]
fn flatten_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_flatten(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — crop
#[tauri::command]
fn crop_mod4_0_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_crop(&PathBuf::from(&path), 4, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 0 — expand
#[tauri::command]
fn expand_mod4_0_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_expand(&PathBuf::from(&path), 4, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 0 — shrink
#[tauri::command]
fn shrink_mod4_0_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_shrink(&PathBuf::from(&path), 4, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 0 — reverse
#[tauri::command]
fn reverse_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_reverse(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — move_start
#[tauri::command]
fn move_mod4_0_pages_to_start(path: String) -> Result<(), String> {
    parity_docmod_move_to_start(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — move_end
#[tauri::command]
fn move_mod4_0_pages_to_end(path: String) -> Result<(), String> {
    parity_docmod_move_to_end(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — clear_crop
#[tauri::command]
fn clear_crop_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_clear_crop(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — dup_before
#[tauri::command]
fn duplicate_mod4_0_pages_before(path: String) -> Result<u32, String> {
    parity_docmod_dup_before(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — sort_rot
#[tauri::command]
fn sort_mod4_0_pages_by_rotation(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_rotation(&PathBuf::from(&path), 4, 0, descending)
}


/// Document-wide mod-4 remainder 0 — sort_size
#[tauri::command]
fn sort_mod4_0_pages_by_size(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_size(&PathBuf::from(&path), 4, 0, descending)
}


/// Document-wide mod-4 remainder 0 — page_numbers
#[tauri::command]
fn add_page_numbers_mod4_0_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_page_numbers(&PathBuf::from(&path), 4, 0, prefix)
}


/// Document-wide mod-4 remainder 0 — watermark
#[tauri::command]
fn add_text_watermark_mod4_0_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_watermark(&PathBuf::from(&path), 4, 0, &text)
}


/// Document-wide mod-4 remainder 0 — header
#[tauri::command]
fn add_page_header_mod4_0_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_header(&PathBuf::from(&path), 4, 0, &text)
}


/// Document-wide mod-4 remainder 0 — footer
#[tauri::command]
fn add_page_footer_mod4_0_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_footer(&PathBuf::from(&path), 4, 0, &text)
}


/// Document-wide mod-4 remainder 0 — border
#[tauri::command]
fn add_page_border_mod4_0_pages(path: String, inset: f64) -> Result<u32, String> {
    parity_docmod_border(&PathBuf::from(&path), 4, 0, inset)
}


/// Document-wide mod-4 remainder 0 — bookmark
#[tauri::command]
fn bookmark_mod4_0_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_bookmark(&PathBuf::from(&path), 4, 0, prefix)
}


/// Document-wide mod-4 remainder 0 — page_size
#[tauri::command]
fn set_page_size_mod4_0_pages(path: String, preset: String) -> Result<u32, String> {
    parity_docmod_page_size(&PathBuf::from(&path), 4, 0, &preset)
}


/// Document-wide mod-4 remainder 0 — blank_before
#[tauri::command]
fn insert_blank_before_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 4, 0, false)
}


/// Document-wide mod-4 remainder 0 — blank_after
#[tauri::command]
fn insert_blank_after_mod4_0_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 4, 0, true)
}


/// Document-wide mod-4 remainder 0 — dup_to_end
#[tauri::command]
fn duplicate_mod4_0_pages_to_end(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_end(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — dup_to_start
#[tauri::command]
fn duplicate_mod4_0_pages_to_start(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_start(&PathBuf::from(&path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — extract
#[tauri::command]
fn extract_mod4_0_pages(path: String, output_path: String) -> Result<String, String> {
    parity_docmod_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), 4, 0)
}


/// Document-wide mod-4 remainder 0 — export_pdf
#[tauri::command]
fn export_mod4_0_pages_as_pdf(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0)
}


/// Document-wide mod-4 remainder 0 — export_png
#[tauri::command]
fn export_mod4_0_pages_png(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0, "png", render_page_png)
}


/// Document-wide mod-4 remainder 0 — export_jpeg
#[tauri::command]
fn export_mod4_0_pages_jpeg(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0, "jpeg", render_page_jpeg)
}


/// Document-wide mod-4 remainder 0 — export_webp
#[tauri::command]
fn export_mod4_0_pages_webp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0, "webp", render_page_webp)
}


/// Document-wide mod-4 remainder 0 — export_bmp
#[tauri::command]
fn export_mod4_0_pages_bmp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0, "bmp", render_page_bmp)
}


/// Document-wide mod-4 remainder 0 — export_tiff
#[tauri::command]
fn export_mod4_0_pages_tiff(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0, "tiff", render_page_tiff)
}


/// Document-wide mod-4 remainder 0 — export_gif
#[tauri::command]
fn export_mod4_0_pages_gif(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0, "gif", render_page_gif)
}


/// Document-wide mod-4 remainder 0 — export_ppm
#[tauri::command]
fn export_mod4_0_pages_ppm(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0, "ppm", render_page_ppm)
}


/// Document-wide mod-4 remainder 0 — export_tga
#[tauri::command]
fn export_mod4_0_pages_tga(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0, "tga", render_page_tga)
}


/// Document-wide mod-4 remainder 0 — export_ico
#[tauri::command]
fn export_mod4_0_pages_ico(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 0, "ico", render_page_ico)
}


/// Document-wide mod-4 remainder 1 — rotate_cw
#[tauri::command]
fn rotate_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 1, 90)
}


/// Document-wide mod-4 remainder 1 — rotate_ccw
#[tauri::command]
fn rotate_mod4_1_pages_ccw(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 1, -90)
}


/// Document-wide mod-4 remainder 1 — rotate_180
#[tauri::command]
fn rotate_180_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 1, 180)
}


/// Document-wide mod-4 remainder 1 — reset_rot
#[tauri::command]
fn reset_rotation_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_reset_rotation(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — delete
#[tauri::command]
fn delete_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_delete(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — keep
#[tauri::command]
fn keep_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_keep(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — dup_append
#[tauri::command]
fn duplicate_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_dup_append(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — flatten
#[tauri::command]
fn flatten_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_flatten(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — crop
#[tauri::command]
fn crop_mod4_1_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_crop(&PathBuf::from(&path), 4, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 1 — expand
#[tauri::command]
fn expand_mod4_1_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_expand(&PathBuf::from(&path), 4, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 1 — shrink
#[tauri::command]
fn shrink_mod4_1_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_shrink(&PathBuf::from(&path), 4, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 1 — reverse
#[tauri::command]
fn reverse_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_reverse(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — move_start
#[tauri::command]
fn move_mod4_1_pages_to_start(path: String) -> Result<(), String> {
    parity_docmod_move_to_start(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — move_end
#[tauri::command]
fn move_mod4_1_pages_to_end(path: String) -> Result<(), String> {
    parity_docmod_move_to_end(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — clear_crop
#[tauri::command]
fn clear_crop_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_clear_crop(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — dup_before
#[tauri::command]
fn duplicate_mod4_1_pages_before(path: String) -> Result<u32, String> {
    parity_docmod_dup_before(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — sort_rot
#[tauri::command]
fn sort_mod4_1_pages_by_rotation(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_rotation(&PathBuf::from(&path), 4, 1, descending)
}


/// Document-wide mod-4 remainder 1 — sort_size
#[tauri::command]
fn sort_mod4_1_pages_by_size(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_size(&PathBuf::from(&path), 4, 1, descending)
}


/// Document-wide mod-4 remainder 1 — page_numbers
#[tauri::command]
fn add_page_numbers_mod4_1_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_page_numbers(&PathBuf::from(&path), 4, 1, prefix)
}


/// Document-wide mod-4 remainder 1 — watermark
#[tauri::command]
fn add_text_watermark_mod4_1_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_watermark(&PathBuf::from(&path), 4, 1, &text)
}


/// Document-wide mod-4 remainder 1 — header
#[tauri::command]
fn add_page_header_mod4_1_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_header(&PathBuf::from(&path), 4, 1, &text)
}


/// Document-wide mod-4 remainder 1 — footer
#[tauri::command]
fn add_page_footer_mod4_1_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_footer(&PathBuf::from(&path), 4, 1, &text)
}


/// Document-wide mod-4 remainder 1 — border
#[tauri::command]
fn add_page_border_mod4_1_pages(path: String, inset: f64) -> Result<u32, String> {
    parity_docmod_border(&PathBuf::from(&path), 4, 1, inset)
}


/// Document-wide mod-4 remainder 1 — bookmark
#[tauri::command]
fn bookmark_mod4_1_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_bookmark(&PathBuf::from(&path), 4, 1, prefix)
}


/// Document-wide mod-4 remainder 1 — page_size
#[tauri::command]
fn set_page_size_mod4_1_pages(path: String, preset: String) -> Result<u32, String> {
    parity_docmod_page_size(&PathBuf::from(&path), 4, 1, &preset)
}


/// Document-wide mod-4 remainder 1 — blank_before
#[tauri::command]
fn insert_blank_before_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 4, 1, false)
}


/// Document-wide mod-4 remainder 1 — blank_after
#[tauri::command]
fn insert_blank_after_mod4_1_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 4, 1, true)
}


/// Document-wide mod-4 remainder 1 — dup_to_end
#[tauri::command]
fn duplicate_mod4_1_pages_to_end(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_end(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — dup_to_start
#[tauri::command]
fn duplicate_mod4_1_pages_to_start(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_start(&PathBuf::from(&path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — extract
#[tauri::command]
fn extract_mod4_1_pages(path: String, output_path: String) -> Result<String, String> {
    parity_docmod_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), 4, 1)
}


/// Document-wide mod-4 remainder 1 — export_pdf
#[tauri::command]
fn export_mod4_1_pages_as_pdf(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1)
}


/// Document-wide mod-4 remainder 1 — export_png
#[tauri::command]
fn export_mod4_1_pages_png(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1, "png", render_page_png)
}


/// Document-wide mod-4 remainder 1 — export_jpeg
#[tauri::command]
fn export_mod4_1_pages_jpeg(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1, "jpeg", render_page_jpeg)
}


/// Document-wide mod-4 remainder 1 — export_webp
#[tauri::command]
fn export_mod4_1_pages_webp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1, "webp", render_page_webp)
}


/// Document-wide mod-4 remainder 1 — export_bmp
#[tauri::command]
fn export_mod4_1_pages_bmp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1, "bmp", render_page_bmp)
}


/// Document-wide mod-4 remainder 1 — export_tiff
#[tauri::command]
fn export_mod4_1_pages_tiff(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1, "tiff", render_page_tiff)
}


/// Document-wide mod-4 remainder 1 — export_gif
#[tauri::command]
fn export_mod4_1_pages_gif(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1, "gif", render_page_gif)
}


/// Document-wide mod-4 remainder 1 — export_ppm
#[tauri::command]
fn export_mod4_1_pages_ppm(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1, "ppm", render_page_ppm)
}


/// Document-wide mod-4 remainder 1 — export_tga
#[tauri::command]
fn export_mod4_1_pages_tga(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1, "tga", render_page_tga)
}


/// Document-wide mod-4 remainder 1 — export_ico
#[tauri::command]
fn export_mod4_1_pages_ico(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 1, "ico", render_page_ico)
}


/// Document-wide mod-4 remainder 2 — rotate_cw
#[tauri::command]
fn rotate_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 2, 90)
}


/// Document-wide mod-4 remainder 2 — rotate_ccw
#[tauri::command]
fn rotate_mod4_2_pages_ccw(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 2, -90)
}


/// Document-wide mod-4 remainder 2 — rotate_180
#[tauri::command]
fn rotate_180_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 2, 180)
}


/// Document-wide mod-4 remainder 2 — reset_rot
#[tauri::command]
fn reset_rotation_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_reset_rotation(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — delete
#[tauri::command]
fn delete_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_delete(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — keep
#[tauri::command]
fn keep_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_keep(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — dup_append
#[tauri::command]
fn duplicate_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_dup_append(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — flatten
#[tauri::command]
fn flatten_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_flatten(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — crop
#[tauri::command]
fn crop_mod4_2_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_crop(&PathBuf::from(&path), 4, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 2 — expand
#[tauri::command]
fn expand_mod4_2_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_expand(&PathBuf::from(&path), 4, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 2 — shrink
#[tauri::command]
fn shrink_mod4_2_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_shrink(&PathBuf::from(&path), 4, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 2 — reverse
#[tauri::command]
fn reverse_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_reverse(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — move_start
#[tauri::command]
fn move_mod4_2_pages_to_start(path: String) -> Result<(), String> {
    parity_docmod_move_to_start(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — move_end
#[tauri::command]
fn move_mod4_2_pages_to_end(path: String) -> Result<(), String> {
    parity_docmod_move_to_end(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — clear_crop
#[tauri::command]
fn clear_crop_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_clear_crop(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — dup_before
#[tauri::command]
fn duplicate_mod4_2_pages_before(path: String) -> Result<u32, String> {
    parity_docmod_dup_before(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — sort_rot
#[tauri::command]
fn sort_mod4_2_pages_by_rotation(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_rotation(&PathBuf::from(&path), 4, 2, descending)
}


/// Document-wide mod-4 remainder 2 — sort_size
#[tauri::command]
fn sort_mod4_2_pages_by_size(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_size(&PathBuf::from(&path), 4, 2, descending)
}


/// Document-wide mod-4 remainder 2 — page_numbers
#[tauri::command]
fn add_page_numbers_mod4_2_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_page_numbers(&PathBuf::from(&path), 4, 2, prefix)
}


/// Document-wide mod-4 remainder 2 — watermark
#[tauri::command]
fn add_text_watermark_mod4_2_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_watermark(&PathBuf::from(&path), 4, 2, &text)
}


/// Document-wide mod-4 remainder 2 — header
#[tauri::command]
fn add_page_header_mod4_2_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_header(&PathBuf::from(&path), 4, 2, &text)
}


/// Document-wide mod-4 remainder 2 — footer
#[tauri::command]
fn add_page_footer_mod4_2_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_footer(&PathBuf::from(&path), 4, 2, &text)
}


/// Document-wide mod-4 remainder 2 — border
#[tauri::command]
fn add_page_border_mod4_2_pages(path: String, inset: f64) -> Result<u32, String> {
    parity_docmod_border(&PathBuf::from(&path), 4, 2, inset)
}


/// Document-wide mod-4 remainder 2 — bookmark
#[tauri::command]
fn bookmark_mod4_2_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_bookmark(&PathBuf::from(&path), 4, 2, prefix)
}


/// Document-wide mod-4 remainder 2 — page_size
#[tauri::command]
fn set_page_size_mod4_2_pages(path: String, preset: String) -> Result<u32, String> {
    parity_docmod_page_size(&PathBuf::from(&path), 4, 2, &preset)
}


/// Document-wide mod-4 remainder 2 — blank_before
#[tauri::command]
fn insert_blank_before_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 4, 2, false)
}


/// Document-wide mod-4 remainder 2 — blank_after
#[tauri::command]
fn insert_blank_after_mod4_2_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 4, 2, true)
}


/// Document-wide mod-4 remainder 2 — dup_to_end
#[tauri::command]
fn duplicate_mod4_2_pages_to_end(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_end(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — dup_to_start
#[tauri::command]
fn duplicate_mod4_2_pages_to_start(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_start(&PathBuf::from(&path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — extract
#[tauri::command]
fn extract_mod4_2_pages(path: String, output_path: String) -> Result<String, String> {
    parity_docmod_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), 4, 2)
}


/// Document-wide mod-4 remainder 2 — export_pdf
#[tauri::command]
fn export_mod4_2_pages_as_pdf(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2)
}


/// Document-wide mod-4 remainder 2 — export_png
#[tauri::command]
fn export_mod4_2_pages_png(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2, "png", render_page_png)
}


/// Document-wide mod-4 remainder 2 — export_jpeg
#[tauri::command]
fn export_mod4_2_pages_jpeg(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2, "jpeg", render_page_jpeg)
}


/// Document-wide mod-4 remainder 2 — export_webp
#[tauri::command]
fn export_mod4_2_pages_webp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2, "webp", render_page_webp)
}


/// Document-wide mod-4 remainder 2 — export_bmp
#[tauri::command]
fn export_mod4_2_pages_bmp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2, "bmp", render_page_bmp)
}


/// Document-wide mod-4 remainder 2 — export_tiff
#[tauri::command]
fn export_mod4_2_pages_tiff(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2, "tiff", render_page_tiff)
}


/// Document-wide mod-4 remainder 2 — export_gif
#[tauri::command]
fn export_mod4_2_pages_gif(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2, "gif", render_page_gif)
}


/// Document-wide mod-4 remainder 2 — export_ppm
#[tauri::command]
fn export_mod4_2_pages_ppm(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2, "ppm", render_page_ppm)
}


/// Document-wide mod-4 remainder 2 — export_tga
#[tauri::command]
fn export_mod4_2_pages_tga(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2, "tga", render_page_tga)
}


/// Document-wide mod-4 remainder 2 — export_ico
#[tauri::command]
fn export_mod4_2_pages_ico(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 2, "ico", render_page_ico)
}


/// Document-wide mod-4 remainder 3 — rotate_cw
#[tauri::command]
fn rotate_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 3, 90)
}


/// Document-wide mod-4 remainder 3 — rotate_ccw
#[tauri::command]
fn rotate_mod4_3_pages_ccw(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 3, -90)
}


/// Document-wide mod-4 remainder 3 — rotate_180
#[tauri::command]
fn rotate_180_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_rotate(&PathBuf::from(&path), 4, 3, 180)
}


/// Document-wide mod-4 remainder 3 — reset_rot
#[tauri::command]
fn reset_rotation_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_reset_rotation(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — delete
#[tauri::command]
fn delete_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_delete(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — keep
#[tauri::command]
fn keep_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_keep(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — dup_append
#[tauri::command]
fn duplicate_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_dup_append(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — flatten
#[tauri::command]
fn flatten_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_flatten(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — crop
#[tauri::command]
fn crop_mod4_3_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_crop(&PathBuf::from(&path), 4, 3, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 3 — expand
#[tauri::command]
fn expand_mod4_3_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_expand(&PathBuf::from(&path), 4, 3, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 3 — shrink
#[tauri::command]
fn shrink_mod4_3_pages(path: String, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_docmod_shrink(&PathBuf::from(&path), 4, 3, margin_top, margin_right, margin_bottom, margin_left)
}


/// Document-wide mod-4 remainder 3 — reverse
#[tauri::command]
fn reverse_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_reverse(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — move_start
#[tauri::command]
fn move_mod4_3_pages_to_start(path: String) -> Result<(), String> {
    parity_docmod_move_to_start(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — move_end
#[tauri::command]
fn move_mod4_3_pages_to_end(path: String) -> Result<(), String> {
    parity_docmod_move_to_end(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — clear_crop
#[tauri::command]
fn clear_crop_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_clear_crop(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — dup_before
#[tauri::command]
fn duplicate_mod4_3_pages_before(path: String) -> Result<u32, String> {
    parity_docmod_dup_before(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — sort_rot
#[tauri::command]
fn sort_mod4_3_pages_by_rotation(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_rotation(&PathBuf::from(&path), 4, 3, descending)
}


/// Document-wide mod-4 remainder 3 — sort_size
#[tauri::command]
fn sort_mod4_3_pages_by_size(path: String, descending: bool) -> Result<u32, String> {
    parity_docmod_sort_size(&PathBuf::from(&path), 4, 3, descending)
}


/// Document-wide mod-4 remainder 3 — page_numbers
#[tauri::command]
fn add_page_numbers_mod4_3_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_page_numbers(&PathBuf::from(&path), 4, 3, prefix)
}


/// Document-wide mod-4 remainder 3 — watermark
#[tauri::command]
fn add_text_watermark_mod4_3_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_watermark(&PathBuf::from(&path), 4, 3, &text)
}


/// Document-wide mod-4 remainder 3 — header
#[tauri::command]
fn add_page_header_mod4_3_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_header(&PathBuf::from(&path), 4, 3, &text)
}


/// Document-wide mod-4 remainder 3 — footer
#[tauri::command]
fn add_page_footer_mod4_3_pages(path: String, text: String) -> Result<u32, String> {
    parity_docmod_footer(&PathBuf::from(&path), 4, 3, &text)
}


/// Document-wide mod-4 remainder 3 — border
#[tauri::command]
fn add_page_border_mod4_3_pages(path: String, inset: f64) -> Result<u32, String> {
    parity_docmod_border(&PathBuf::from(&path), 4, 3, inset)
}


/// Document-wide mod-4 remainder 3 — bookmark
#[tauri::command]
fn bookmark_mod4_3_pages(path: String, prefix: Option<String>) -> Result<u32, String> {
    parity_docmod_bookmark(&PathBuf::from(&path), 4, 3, prefix)
}


/// Document-wide mod-4 remainder 3 — page_size
#[tauri::command]
fn set_page_size_mod4_3_pages(path: String, preset: String) -> Result<u32, String> {
    parity_docmod_page_size(&PathBuf::from(&path), 4, 3, &preset)
}


/// Document-wide mod-4 remainder 3 — blank_before
#[tauri::command]
fn insert_blank_before_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 4, 3, false)
}


/// Document-wide mod-4 remainder 3 — blank_after
#[tauri::command]
fn insert_blank_after_mod4_3_pages(path: String) -> Result<u32, String> {
    parity_docmod_blank(&PathBuf::from(&path), 4, 3, true)
}


/// Document-wide mod-4 remainder 3 — dup_to_end
#[tauri::command]
fn duplicate_mod4_3_pages_to_end(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_end(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — dup_to_start
#[tauri::command]
fn duplicate_mod4_3_pages_to_start(path: String) -> Result<u32, String> {
    parity_docmod_dup_to_start(&PathBuf::from(&path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — extract
#[tauri::command]
fn extract_mod4_3_pages(path: String, output_path: String) -> Result<String, String> {
    parity_docmod_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), 4, 3)
}


/// Document-wide mod-4 remainder 3 — export_pdf
#[tauri::command]
fn export_mod4_3_pages_as_pdf(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3)
}


/// Document-wide mod-4 remainder 3 — export_png
#[tauri::command]
fn export_mod4_3_pages_png(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3, "png", render_page_png)
}


/// Document-wide mod-4 remainder 3 — export_jpeg
#[tauri::command]
fn export_mod4_3_pages_jpeg(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3, "jpeg", render_page_jpeg)
}


/// Document-wide mod-4 remainder 3 — export_webp
#[tauri::command]
fn export_mod4_3_pages_webp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3, "webp", render_page_webp)
}


/// Document-wide mod-4 remainder 3 — export_bmp
#[tauri::command]
fn export_mod4_3_pages_bmp(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3, "bmp", render_page_bmp)
}


/// Document-wide mod-4 remainder 3 — export_tiff
#[tauri::command]
fn export_mod4_3_pages_tiff(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3, "tiff", render_page_tiff)
}


/// Document-wide mod-4 remainder 3 — export_gif
#[tauri::command]
fn export_mod4_3_pages_gif(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3, "gif", render_page_gif)
}


/// Document-wide mod-4 remainder 3 — export_ppm
#[tauri::command]
fn export_mod4_3_pages_ppm(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3, "ppm", render_page_ppm)
}


/// Document-wide mod-4 remainder 3 — export_tga
#[tauri::command]
fn export_mod4_3_pages_tga(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3, "tga", render_page_tga)
}


/// Document-wide mod-4 remainder 3 — export_ico
#[tauri::command]
fn export_mod4_3_pages_ico(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_docmod_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), 4, 3, "ico", render_page_ico)
}
