// Auto-generated by scripts/gen-parity-batch7.py - do not edit.
fn parity_third_match(page_index: u32, start_page: u32, end_page: u32, third: u32) -> bool {
    if page_index < start_page || page_index > end_page {
        return false;
    }
    let span = end_page - start_page;
    let t1 = start_page + span / 3;
    let t2 = start_page + (2 * span) / 3;
    match third {
        0 => page_index <= t1,
        1 => page_index > t1 && page_index <= t2,
        2 => page_index > t2,
        _ => false,
    }
}


fn parity_third_indices(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<Vec<u32>, String> {
    validate_page_range(path, start_page, end_page)?;
    Ok((start_page..=end_page)
        .filter(|i| parity_third_match(*i, start_page, end_page, third))
        .collect())
}

fn parity_third_rotate(path: &Path, start_page: u32, end_page: u32, third: u32, delta: i64) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut rotated = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let current = page_rotation(&doc, page_id);
        set_page_rotation(&mut doc, page_id, current + delta)?;
        rotated += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(rotated)
}

fn parity_third_reset_rotation(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut reset = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        set_page_rotation(&mut doc, page_id, 0)?;
        reset += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(reset)
}

fn parity_third_delete(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let mut to_delete: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_third_match(*i as u32, start_page, end_page, third))
        .collect();
    if to_delete.is_empty() {
        return Ok(0);
    }
    if kids.len() - to_delete.len() < 1 {
        return Err("Cannot delete every page in the document".to_string());
    }
    to_delete.sort_by(|a, b| b.cmp(a));
    let deleted = to_delete.len() as u32;
    for idx in to_delete {
        kids.remove(idx);
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_third_keep(path: &Path, start_page: u32, end_page: u32, keep_third: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (kids, _) = get_pages_kids(&doc)?;
    let kept: Vec<Object> = kids
        .iter()
        .enumerate()
        .filter(|(i, _)| {
            let idx = *i as u32;
            if idx < start_page || idx > end_page {
                return true;
            }
            parity_third_match(idx, start_page, end_page, keep_third)
        })
        .map(|(_, kid)| kid.clone())
        .collect();
    if kept.is_empty() {
        return Err("No pages would remain after keep filter".to_string());
    }
    if kept.len() == kids.len() {
        return Err("Nothing to delete - all pages in range match the keep filter".to_string());
    }
    let deleted = (kids.len() - kept.len()) as u32;
    set_pages_kids(&mut doc, pages_ref, kept)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_third_dup_append(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<u32, String> {
    let indices = parity_third_indices(path, start_page, end_page, third)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in &indices {
        duplicate_page(path_str.clone(), idx)?;
    }
    Ok(indices.len() as u32)
}

fn parity_third_flatten(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut removed = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let count = doc
            .get_dictionary(page_id)
            .ok()
            .and_then(|d| d.get(b"Annots").ok())
            .and_then(|o| o.as_array().ok())
            .map(|a| a.len() as u32)
            .unwrap_or(0);
        if count > 0 {
            doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"Annots");
            removed += count;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(removed)
}

fn parity_third_reverse(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_third_match(*i as u32, start_page, end_page, third))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut parity_kids: Vec<Object> = parity_indices.iter().map(|i| kids[*i].clone()).collect();
    parity_kids.reverse();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = parity_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

#[allow(clippy::too_many_arguments)]
fn parity_third_crop(path: &Path, start_page: u32, end_page: u32, third: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut cropped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_crop_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        cropped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cropped)
}

fn parity_third_extract(path: &Path, output_path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<String, String> {
    if path == output_path {
        return Err("Output path must differ from the source PDF".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let doc = Document::load(path).map_err(|e| e.to_string())?;
    let (all_kids, pages_ref) = get_pages_kids(&doc)?;
    let subset: Vec<Object> = all_kids
        .iter()
        .enumerate()
        .filter(|(i, _)| parity_third_match(*i as u32, start_page, end_page, third))
        .map(|(_, kid)| kid.clone())
        .collect();
    if subset.is_empty() {
        return Err("No pages match the extract filter in range".to_string());
    }
    let mut out = Document::with_version(doc.version.clone());
    set_pages_kids(&mut out, pages_ref, subset)?;
    out.save(output_path).map_err(|e| e.to_string())?;
    Ok(output_path.to_string_lossy().into_owned())
}

fn parity_third_export_pdf(path: &Path, output_dir: &Path, start_page: u32, end_page: u32, third: u32) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let path_str = path.to_string_lossy().into_owned();
    let mut written = Vec::new();
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let file_name = format!("page-{:03}.pdf", page_index + 1);
        let output_path = output_dir.join(file_name);
        let out = extract_pdf_pages(path_str.clone(), output_path.to_string_lossy().into_owned(), page_index, page_index)?;
        written.push(out);
    }
    Ok(written)
}

#[allow(clippy::too_many_arguments)]
fn parity_third_export_rendered(path: &Path, output_dir: &Path, start_page: u32, end_page: u32, third: u32, ext: &str, render: ParityPageRenderFn) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let mut written = Vec::new();
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let bytes = render(path, page_index, EXPORT_PNG_W, EXPORT_PNG_H)?;
        let file_name = format!("page-{:03}.{ext}", page_index + 1);
        let output_path = output_dir.join(file_name);
        write_png_output(&output_path, &bytes)?;
        written.push(output_path.to_string_lossy().into_owned());
    }
    Ok(written)
}

fn parity_third_page_numbers(path: &Path, start_page: u32, end_page: u32, third: u32, prefix: Option<String>) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let prefix = prefix.unwrap_or_default();
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 1100.0)?;
        let label = format!("{prefix}{}", page_index + 1);
        let ops = build_page_number_ops(&font_name, &label, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_third_watermark(path: &Path, start_page: u32, end_page: u32, third: u32, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Watermark text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (cx, cy) = viewer_point_to_pdf(&doc, page_id, 400.0, 566.0)?;
        let ops = build_watermark_ops(&font_name, trimmed, cx, cy);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}
fn parity_third_dup_before(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<u32, String> {
    let indices = parity_third_indices(path, start_page, end_page, third)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in indices.iter().rev() {
        insert_pdf(path_str.clone(), path_str.clone(), idx, idx, idx)?;
    }
    Ok(indices.len() as u32)
}

fn parity_third_dup_to_start(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<u32, String> {
    let indices = parity_third_indices(path, start_page, end_page, third)?;
    let path_str = path.to_string_lossy().into_owned();
    for (offset, &idx) in indices.iter().rev().enumerate() {
        let offset = offset as u32;
        let source = idx + offset;
        insert_pdf(path_str.clone(), path_str.clone(), offset, source, source)?;
    }
    Ok(indices.len() as u32)
}

fn parity_third_dup_to_end(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<u32, String> {
    let indices = parity_third_indices(path, start_page, end_page, third)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in indices.iter().rev() {
        let new_idx = duplicate_page(path_str.clone(), idx)?;
        move_page_to_last(path_str.clone(), new_idx)?;
    }
    Ok(indices.len() as u32)
}

#[allow(clippy::too_many_arguments)]
fn parity_third_expand(path: &Path, start_page: u32, end_page: u32, third: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut expanded = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_expand_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        expanded += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(expanded)
}

#[allow(clippy::too_many_arguments)]
fn parity_third_shrink(path: &Path, start_page: u32, end_page: u32, third: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut shrunk = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_shrink_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        shrunk += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(shrunk)
}

fn parity_third_clear_crop(path: &Path, start_page: u32, end_page: u32, third: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut cleared = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        if doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"CropBox").is_some() {
            cleared += 1;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cleared)
}

fn parity_third_blank(path: &Path, start_page: u32, end_page: u32, third: u32, after: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_third_match(*i as u32, start_page, end_page, third))
        .collect();
    for &idx in indices.iter().rev() {
        let page_id = create_blank_page(&mut doc, pages_ref);
        let at = if after { idx + 1 } else { idx };
        kids.insert(at, Object::Reference(page_id));
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(indices.len() as u32)
}

fn parity_third_bookmark(path: &Path, start_page: u32, end_page: u32, third: u32, prefix: Option<String>) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let prefix = prefix.unwrap_or_else(|| "Page ".to_string());
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut count = 0u32;
    for (page_num, page_id) in doc.get_pages() {
        let page_index = page_num - 1;
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let title = format!("{prefix}{page_num}");
        append_outline_item(&mut doc, &title, page_id)?;
        count += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(count)
}

fn parity_third_page_size(path: &Path, start_page: u32, end_page: u32, third: u32, preset: &str) -> Result<u32, String> {
    let (w, h) = page_size_preset_dims(preset)?;
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut resized = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let page = doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?;
        page.set(
            "MediaBox",
            Object::Array(vec![Object::Integer(0), Object::Integer(0), Object::Real(w as f32), Object::Real(h as f32)]),
        );
        page.remove(b"CropBox");
        resized += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(resized)
}

fn parity_third_header(path: &Path, start_page: u32, end_page: u32, third: u32, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Header text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 40.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_third_footer(path: &Path, start_page: u32, end_page: u32, third: u32, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Footer text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 1100.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_third_border(path: &Path, start_page: u32, end_page: u32, third: u32, inset: f64) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut drawn = 0u32;
    for page_index in start_page..=end_page {
        if !parity_third_match(page_index, start_page, end_page, third) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let ops = build_page_border_ops(&doc, page_id, inset)?;
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        drawn += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(drawn)
}

fn parity_third_sort_rotation(path: &Path, start_page: u32, end_page: u32, third: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_third_match(*i as u32, start_page, end_page, third))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, i64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let rot = kid.as_reference().ok().map(|id| page_rotation(&doc, id).rem_euclid(360)).unwrap_or(0);
            (*i, rot, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.cmp(&b.1);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_third_sort_size(path: &Path, start_page: u32, end_page: u32, third: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_third_match(*i as u32, start_page, end_page, third))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, f64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let area = kid
                .as_reference()
                .ok()
                .and_then(|id| page_media_box(&doc, id).ok())
                .map(|m| (m[2] - m[0]) * (m[3] - m[1]))
                .unwrap_or(0.0);
            (*i, area, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}



/// First third of page range - rotate_cw
#[tauri::command]
fn rotate_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_rotate(&PathBuf::from(&path), start_page, end_page, 0, 90)
}


/// Second third of page range - rotate_cw
#[tauri::command]
fn rotate_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_rotate(&PathBuf::from(&path), start_page, end_page, 1, 90)
}


/// Third third of page range - rotate_cw
#[tauri::command]
fn rotate_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_rotate(&PathBuf::from(&path), start_page, end_page, 2, 90)
}


/// First third of page range - rotate_ccw
#[tauri::command]
fn rotate_first_third_pages_in_range_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_rotate(&PathBuf::from(&path), start_page, end_page, 0, -90)
}


/// Second third of page range - rotate_ccw
#[tauri::command]
fn rotate_second_third_pages_in_range_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_rotate(&PathBuf::from(&path), start_page, end_page, 1, -90)
}


/// Third third of page range - rotate_ccw
#[tauri::command]
fn rotate_third_third_pages_in_range_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_rotate(&PathBuf::from(&path), start_page, end_page, 2, -90)
}


/// First third of page range - rotate_180
#[tauri::command]
fn rotate_180_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_rotate(&PathBuf::from(&path), start_page, end_page, 0, 180)
}


/// Second third of page range - rotate_180
#[tauri::command]
fn rotate_180_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_rotate(&PathBuf::from(&path), start_page, end_page, 1, 180)
}


/// Third third of page range - rotate_180
#[tauri::command]
fn rotate_180_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_rotate(&PathBuf::from(&path), start_page, end_page, 2, 180)
}


/// First third of page range - reset_rot
#[tauri::command]
fn reset_rotation_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_reset_rotation(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - reset_rot
#[tauri::command]
fn reset_rotation_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_reset_rotation(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - reset_rot
#[tauri::command]
fn reset_rotation_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_reset_rotation(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - delete
#[tauri::command]
fn delete_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_delete(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - delete
#[tauri::command]
fn delete_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_delete(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - delete
#[tauri::command]
fn delete_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_delete(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - keep
#[tauri::command]
fn keep_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_keep(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - keep
#[tauri::command]
fn keep_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_keep(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - keep
#[tauri::command]
fn keep_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_keep(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - dup_append
#[tauri::command]
fn duplicate_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_append(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - dup_append
#[tauri::command]
fn duplicate_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_append(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - dup_append
#[tauri::command]
fn duplicate_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_append(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - flatten
#[tauri::command]
fn flatten_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_flatten(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - flatten
#[tauri::command]
fn flatten_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_flatten(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - flatten
#[tauri::command]
fn flatten_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_flatten(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - reverse
#[tauri::command]
fn reverse_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_reverse(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - reverse
#[tauri::command]
fn reverse_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_reverse(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - reverse
#[tauri::command]
fn reverse_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_reverse(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - crop
#[tauri::command]
fn crop_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_third_crop(&PathBuf::from(&path), start_page, end_page, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Second third of page range - crop
#[tauri::command]
fn crop_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_third_crop(&PathBuf::from(&path), start_page, end_page, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Third third of page range - crop
#[tauri::command]
fn crop_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_third_crop(&PathBuf::from(&path), start_page, end_page, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// First third of page range - extract
#[tauri::command]
fn extract_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_third_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 0)
}


/// Second third of page range - extract
#[tauri::command]
fn extract_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_third_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 1)
}


/// Third third of page range - extract
#[tauri::command]
fn extract_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_third_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 2)
}


/// First third of page range - export_pdf
#[tauri::command]
fn export_first_third_pages_in_range_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0)
}


/// Second third of page range - export_pdf
#[tauri::command]
fn export_second_third_pages_in_range_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1)
}


/// Third third of page range - export_pdf
#[tauri::command]
fn export_third_third_pages_in_range_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2)
}


/// First third of page range - export_png
#[tauri::command]
fn export_first_third_pages_in_range_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "png", render_page_png)
}


/// Second third of page range - export_png
#[tauri::command]
fn export_second_third_pages_in_range_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "png", render_page_png)
}


/// Third third of page range - export_png
#[tauri::command]
fn export_third_third_pages_in_range_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "png", render_page_png)
}


/// First third of page range - export_jpeg
#[tauri::command]
fn export_first_third_pages_in_range_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "jpeg", render_page_jpeg)
}


/// Second third of page range - export_jpeg
#[tauri::command]
fn export_second_third_pages_in_range_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "jpeg", render_page_jpeg)
}


/// Third third of page range - export_jpeg
#[tauri::command]
fn export_third_third_pages_in_range_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "jpeg", render_page_jpeg)
}


/// First third of page range - page_numbers
#[tauri::command]
fn add_page_numbers_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_third_page_numbers(&PathBuf::from(&path), start_page, end_page, 0, prefix)
}


/// Second third of page range - page_numbers
#[tauri::command]
fn add_page_numbers_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_third_page_numbers(&PathBuf::from(&path), start_page, end_page, 1, prefix)
}


/// Third third of page range - page_numbers
#[tauri::command]
fn add_page_numbers_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_third_page_numbers(&PathBuf::from(&path), start_page, end_page, 2, prefix)
}


/// First third of page range - watermark
#[tauri::command]
fn add_text_watermark_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_third_watermark(&PathBuf::from(&path), start_page, end_page, 0, &text)
}


/// Second third of page range - watermark
#[tauri::command]
fn add_text_watermark_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_third_watermark(&PathBuf::from(&path), start_page, end_page, 1, &text)
}


/// Third third of page range - watermark
#[tauri::command]
fn add_text_watermark_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_third_watermark(&PathBuf::from(&path), start_page, end_page, 2, &text)
}


/// First third of page range - dup_before
#[tauri::command]
fn duplicate_first_third_pages_in_range_before(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_before(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - dup_before
#[tauri::command]
fn duplicate_second_third_pages_in_range_before(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_before(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - dup_before
#[tauri::command]
fn duplicate_third_third_pages_in_range_before(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_before(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - dup_to_start
#[tauri::command]
fn duplicate_first_third_pages_in_range_to_start(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_to_start(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - dup_to_start
#[tauri::command]
fn duplicate_second_third_pages_in_range_to_start(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_to_start(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - dup_to_start
#[tauri::command]
fn duplicate_third_third_pages_in_range_to_start(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_to_start(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - dup_to_end
#[tauri::command]
fn duplicate_first_third_pages_in_range_to_end(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_to_end(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - dup_to_end
#[tauri::command]
fn duplicate_second_third_pages_in_range_to_end(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_to_end(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - dup_to_end
#[tauri::command]
fn duplicate_third_third_pages_in_range_to_end(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_dup_to_end(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - expand
#[tauri::command]
fn expand_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_third_expand(&PathBuf::from(&path), start_page, end_page, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Second third of page range - expand
#[tauri::command]
fn expand_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_third_expand(&PathBuf::from(&path), start_page, end_page, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Third third of page range - expand
#[tauri::command]
fn expand_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_third_expand(&PathBuf::from(&path), start_page, end_page, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// First third of page range - shrink
#[tauri::command]
fn shrink_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_third_shrink(&PathBuf::from(&path), start_page, end_page, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Second third of page range - shrink
#[tauri::command]
fn shrink_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_third_shrink(&PathBuf::from(&path), start_page, end_page, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Third third of page range - shrink
#[tauri::command]
fn shrink_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_third_shrink(&PathBuf::from(&path), start_page, end_page, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// First third of page range - clear_crop
#[tauri::command]
fn clear_crop_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_clear_crop(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Second third of page range - clear_crop
#[tauri::command]
fn clear_crop_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_clear_crop(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Third third of page range - clear_crop
#[tauri::command]
fn clear_crop_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_clear_crop(&PathBuf::from(&path), start_page, end_page, 2)
}


/// First third of page range - blank_before
#[tauri::command]
fn insert_blank_before_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_blank(&PathBuf::from(&path), start_page, end_page, 0, false)
}


/// Second third of page range - blank_before
#[tauri::command]
fn insert_blank_before_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_blank(&PathBuf::from(&path), start_page, end_page, 1, false)
}


/// Third third of page range - blank_before
#[tauri::command]
fn insert_blank_before_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_blank(&PathBuf::from(&path), start_page, end_page, 2, false)
}


/// First third of page range - blank_after
#[tauri::command]
fn insert_blank_after_first_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_blank(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Second third of page range - blank_after
#[tauri::command]
fn insert_blank_after_second_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_blank(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Third third of page range - blank_after
#[tauri::command]
fn insert_blank_after_third_third_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_blank(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// First third of page range - bookmark
#[tauri::command]
fn bookmark_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_third_bookmark(&PathBuf::from(&path), start_page, end_page, 0, prefix)
}


/// Second third of page range - bookmark
#[tauri::command]
fn bookmark_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_third_bookmark(&PathBuf::from(&path), start_page, end_page, 1, prefix)
}


/// Third third of page range - bookmark
#[tauri::command]
fn bookmark_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_third_bookmark(&PathBuf::from(&path), start_page, end_page, 2, prefix)
}


/// First third of page range - page_size
#[tauri::command]
fn set_page_size_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_third_page_size(&PathBuf::from(&path), start_page, end_page, 0, &preset)
}


/// Second third of page range - page_size
#[tauri::command]
fn set_page_size_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_third_page_size(&PathBuf::from(&path), start_page, end_page, 1, &preset)
}


/// Third third of page range - page_size
#[tauri::command]
fn set_page_size_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_third_page_size(&PathBuf::from(&path), start_page, end_page, 2, &preset)
}


/// First third of page range - header
#[tauri::command]
fn add_page_header_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_third_header(&PathBuf::from(&path), start_page, end_page, 0, &text)
}


/// Second third of page range - header
#[tauri::command]
fn add_page_header_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_third_header(&PathBuf::from(&path), start_page, end_page, 1, &text)
}


/// Third third of page range - header
#[tauri::command]
fn add_page_header_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_third_header(&PathBuf::from(&path), start_page, end_page, 2, &text)
}


/// First third of page range - footer
#[tauri::command]
fn add_page_footer_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_third_footer(&PathBuf::from(&path), start_page, end_page, 0, &text)
}


/// Second third of page range - footer
#[tauri::command]
fn add_page_footer_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_third_footer(&PathBuf::from(&path), start_page, end_page, 1, &text)
}


/// Third third of page range - footer
#[tauri::command]
fn add_page_footer_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_third_footer(&PathBuf::from(&path), start_page, end_page, 2, &text)
}


/// First third of page range - border
#[tauri::command]
fn add_page_border_first_third_pages_in_range(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_third_border(&PathBuf::from(&path), start_page, end_page, 0, inset)
}


/// Second third of page range - border
#[tauri::command]
fn add_page_border_second_third_pages_in_range(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_third_border(&PathBuf::from(&path), start_page, end_page, 1, inset)
}


/// Third third of page range - border
#[tauri::command]
fn add_page_border_third_third_pages_in_range(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_third_border(&PathBuf::from(&path), start_page, end_page, 2, inset)
}


/// First third of page range - export_webp
#[tauri::command]
fn export_first_third_pages_in_range_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "webp", render_page_webp)
}


/// Second third of page range - export_webp
#[tauri::command]
fn export_second_third_pages_in_range_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "webp", render_page_webp)
}


/// Third third of page range - export_webp
#[tauri::command]
fn export_third_third_pages_in_range_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "webp", render_page_webp)
}


/// First third of page range - export_bmp
#[tauri::command]
fn export_first_third_pages_in_range_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "bmp", render_page_bmp)
}


/// Second third of page range - export_bmp
#[tauri::command]
fn export_second_third_pages_in_range_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "bmp", render_page_bmp)
}


/// Third third of page range - export_bmp
#[tauri::command]
fn export_third_third_pages_in_range_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "bmp", render_page_bmp)
}


/// First third of page range - export_tiff
#[tauri::command]
fn export_first_third_pages_in_range_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "tiff", render_page_tiff)
}


/// Second third of page range - export_tiff
#[tauri::command]
fn export_second_third_pages_in_range_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "tiff", render_page_tiff)
}


/// Third third of page range - export_tiff
#[tauri::command]
fn export_third_third_pages_in_range_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "tiff", render_page_tiff)
}


/// First third of page range - export_gif
#[tauri::command]
fn export_first_third_pages_in_range_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "gif", render_page_gif)
}


/// Second third of page range - export_gif
#[tauri::command]
fn export_second_third_pages_in_range_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "gif", render_page_gif)
}


/// Third third of page range - export_gif
#[tauri::command]
fn export_third_third_pages_in_range_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "gif", render_page_gif)
}


/// First third of page range - export_ppm
#[tauri::command]
fn export_first_third_pages_in_range_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "ppm", render_page_ppm)
}


/// Second third of page range - export_ppm
#[tauri::command]
fn export_second_third_pages_in_range_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "ppm", render_page_ppm)
}


/// Third third of page range - export_ppm
#[tauri::command]
fn export_third_third_pages_in_range_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "ppm", render_page_ppm)
}


/// First third of page range - export_tga
#[tauri::command]
fn export_first_third_pages_in_range_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "tga", render_page_tga)
}


/// Second third of page range - export_tga
#[tauri::command]
fn export_second_third_pages_in_range_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "tga", render_page_tga)
}


/// Third third of page range - export_tga
#[tauri::command]
fn export_third_third_pages_in_range_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "tga", render_page_tga)
}


/// First third of page range - export_ico
#[tauri::command]
fn export_first_third_pages_in_range_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "ico", render_page_ico)
}


/// Second third of page range - export_ico
#[tauri::command]
fn export_second_third_pages_in_range_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "ico", render_page_ico)
}


/// Third third of page range - export_ico
#[tauri::command]
fn export_third_third_pages_in_range_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_third_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "ico", render_page_ico)
}


/// First third of page range - sort_rot
#[tauri::command]
fn sort_first_third_pages_in_range_by_rotation(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_sort_rotation(&PathBuf::from(&path), start_page, end_page, 0, false)
}


/// Second third of page range - sort_rot
#[tauri::command]
fn sort_second_third_pages_in_range_by_rotation(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_sort_rotation(&PathBuf::from(&path), start_page, end_page, 1, false)
}


/// Third third of page range - sort_rot
#[tauri::command]
fn sort_third_third_pages_in_range_by_rotation(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_sort_rotation(&PathBuf::from(&path), start_page, end_page, 2, false)
}


/// First third of page range - sort_size
#[tauri::command]
fn sort_first_third_pages_in_range_by_size(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_sort_size(&PathBuf::from(&path), start_page, end_page, 0, false)
}


/// Second third of page range - sort_size
#[tauri::command]
fn sort_second_third_pages_in_range_by_size(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_sort_size(&PathBuf::from(&path), start_page, end_page, 1, false)
}


/// Third third of page range - sort_size
#[tauri::command]
fn sort_third_third_pages_in_range_by_size(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_third_sort_size(&PathBuf::from(&path), start_page, end_page, 2, false)
}
