// Auto-generated by scripts/gen-parity-batch.py — do not edit.

#[allow(clippy::manual_is_multiple_of)]
fn parity_batch_match(page_index: u32, start_page: u32, end_page: u32, odd: bool, local: bool) -> bool {
    if page_index < start_page || page_index > end_page {
        return false;
    }
    let even_indexed = if local {
        (page_index - start_page).is_multiple_of(2)
    } else {
        page_index.is_multiple_of(2)
    };
    even_indexed == odd
}

fn parity_batch_indices(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<Vec<u32>, String> {
    validate_page_range(path, start_page, end_page)?;
    Ok((start_page..=end_page)
        .filter(|i| parity_batch_match(*i, start_page, end_page, odd, local))
        .collect())
}

fn parity_batch_rotate(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, delta: i64) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut rotated = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let current = page_rotation(&doc, page_id);
        set_page_rotation(&mut doc, page_id, current + delta)?;
        rotated += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(rotated)
}

fn parity_batch_reset_rotation(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut reset = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        set_page_rotation(&mut doc, page_id, 0)?;
        reset += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(reset)
}

fn parity_batch_delete(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let mut to_delete: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_batch_match(*i as u32, start_page, end_page, odd, local))
        .collect();
    if to_delete.is_empty() {
        return Ok(0);
    }
    if kids.len() - to_delete.len() < 1 {
        return Err("Cannot delete every page in the document".to_string());
    }
    to_delete.sort_by(|a, b| b.cmp(a));
    let deleted = to_delete.len() as u32;
    for idx in to_delete {
        kids.remove(idx);
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_batch_keep(path: &Path, start_page: u32, end_page: u32, keep_odd: bool, local: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (kids, _) = get_pages_kids(&doc)?;
    let kept: Vec<Object> = kids
        .iter()
        .enumerate()
        .filter(|(i, _)| {
            let idx = *i as u32;
            if idx < start_page || idx > end_page {
                return true;
            }
            parity_batch_match(idx, start_page, end_page, keep_odd, local)
        })
        .map(|(_, kid)| kid.clone())
        .collect();
    if kept.is_empty() {
        return Err("No pages would remain after keep filter".to_string());
    }
    if kept.len() == kids.len() {
        return Err("Nothing to delete — all pages in range match the keep filter".to_string());
    }
    let deleted = (kids.len() - kept.len()) as u32;
    set_pages_kids(&mut doc, pages_ref, kept)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_batch_dup_append(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<u32, String> {
    let indices = parity_batch_indices(path, start_page, end_page, odd, local)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in &indices {
        duplicate_page(path_str.clone(), idx)?;
    }
    Ok(indices.len() as u32)
}

fn parity_batch_dup_before(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<u32, String> {
    let indices = parity_batch_indices(path, start_page, end_page, odd, local)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in indices.iter().rev() {
        insert_pdf(path_str.clone(), path_str.clone(), idx, idx, idx)?;
    }
    Ok(indices.len() as u32)
}

fn parity_batch_dup_to_start(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<u32, String> {
    let indices = parity_batch_indices(path, start_page, end_page, odd, local)?;
    let path_str = path.to_string_lossy().into_owned();
    for (offset, &idx) in indices.iter().rev().enumerate() {
        let offset = offset as u32;
        let source = idx + offset;
        insert_pdf(path_str.clone(), path_str.clone(), offset, source, source)?;
    }
    Ok(indices.len() as u32)
}

fn parity_batch_dup_to_end(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<u32, String> {
    let indices = parity_batch_indices(path, start_page, end_page, odd, local)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in indices.iter().rev() {
        let new_idx = duplicate_page(path_str.clone(), idx)?;
        move_page_to_last(path_str.clone(), new_idx)?;
    }
    Ok(indices.len() as u32)
}

fn parity_batch_flatten(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut removed = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let count = doc
            .get_dictionary(page_id)
            .ok()
            .and_then(|d| d.get(b"Annots").ok())
            .and_then(|o| o.as_array().ok())
            .map(|a| a.len() as u32)
            .unwrap_or(0);
        if count > 0 {
            doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"Annots");
            removed += count;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(removed)
}

fn parity_batch_reverse(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_batch_match(*i as u32, start_page, end_page, odd, local))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut parity_kids: Vec<Object> = parity_indices.iter().map(|i| kids[*i].clone()).collect();
    parity_kids.reverse();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = parity_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

#[allow(clippy::manual_is_multiple_of)]
fn parity_batch_move_seg(path: &Path, start_page: u32, end_page: u32, odd_first: bool, local: bool) -> Result<(), String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let start = start_page as usize;
    let end = end_page as usize;
    let segment: Vec<Object> = kids.drain(start..=end).collect();
    let mut odd_kids = Vec::new();
    let mut even_kids = Vec::new();
    for (i, kid) in segment.into_iter().enumerate() {
        let global_idx = start + i;
        let is_odd = if local {
            (i as u32).is_multiple_of(2)
        } else {
            global_idx.is_multiple_of(2)
        };
        if is_odd {
            odd_kids.push(kid);
        } else {
            even_kids.push(kid);
        }
    }
    let reordered: Vec<Object> = if odd_first {
        odd_kids.into_iter().chain(even_kids).collect()
    } else {
        even_kids.into_iter().chain(odd_kids).collect()
    };
    for (offset, kid) in reordered.into_iter().enumerate() {
        kids.insert(start + offset, kid);
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(())
}

fn parity_batch_sort_rotation(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_batch_match(*i as u32, start_page, end_page, odd, local))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, i64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let rot = kid.as_reference().ok().map(|id| page_rotation(&doc, id).rem_euclid(360)).unwrap_or(0);
            (*i, rot, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.cmp(&b.1);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_batch_sort_size(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_batch_match(*i as u32, start_page, end_page, odd, local))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, f64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let area = kid
                .as_reference()
                .ok()
                .and_then(|id| page_media_box(&doc, id).ok())
                .map(|m| (m[2] - m[0]) * (m[3] - m[1]))
                .unwrap_or(0.0);
            (*i, area, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

#[allow(clippy::too_many_arguments)]
fn parity_batch_crop(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut cropped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_crop_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        cropped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cropped)
}

#[allow(clippy::too_many_arguments)]
fn parity_batch_expand(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut expanded = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_expand_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        expanded += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(expanded)
}

#[allow(clippy::too_many_arguments)]
fn parity_batch_shrink(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut shrunk = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_shrink_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        shrunk += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(shrunk)
}

fn parity_batch_clear_crop(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut cleared = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        if doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"CropBox").is_some() {
            cleared += 1;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cleared)
}

fn parity_batch_blank(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, after: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_batch_match(*i as u32, start_page, end_page, odd, local))
        .collect();
    for &idx in indices.iter().rev() {
        let page_id = create_blank_page(&mut doc, pages_ref);
        let at = if after { idx + 1 } else { idx };
        kids.insert(at, Object::Reference(page_id));
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(indices.len() as u32)
}

fn parity_batch_bookmark(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, prefix: Option<String>) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let prefix = prefix.unwrap_or_else(|| "Page ".to_string());
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut count = 0u32;
    for (page_num, page_id) in doc.get_pages() {
        let page_index = page_num - 1;
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let title = format!("{prefix}{page_num}");
        append_outline_item(&mut doc, &title, page_id)?;
        count += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(count)
}

fn parity_batch_page_size(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, preset: &str) -> Result<u32, String> {
    let (w, h) = page_size_preset_dims(preset)?;
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut resized = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let page = doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?;
        page.set(
            "MediaBox",
            Object::Array(vec![Object::Integer(0), Object::Integer(0), Object::Real(w as f32), Object::Real(h as f32)]),
        );
        page.remove(b"CropBox");
        resized += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(resized)
}

fn parity_batch_extract(path: &Path, output_path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<String, String> {
    if path == output_path {
        return Err("Output path must differ from the source PDF".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let doc = Document::load(path).map_err(|e| e.to_string())?;
    let (all_kids, pages_ref) = get_pages_kids(&doc)?;
    let subset: Vec<Object> = all_kids
        .iter()
        .enumerate()
        .filter(|(i, _)| parity_batch_match(*i as u32, start_page, end_page, odd, local))
        .map(|(_, kid)| kid.clone())
        .collect();
    if subset.is_empty() {
        return Err("No pages match the extract filter in range".to_string());
    }
    let mut out = Document::with_version(doc.version.clone());
    set_pages_kids(&mut out, pages_ref, subset)?;
    out.save(output_path).map_err(|e| e.to_string())?;
    Ok(output_path.to_string_lossy().into_owned())
}

fn parity_batch_page_numbers(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, prefix: Option<String>) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let prefix = prefix.unwrap_or_default();
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 1100.0)?;
        let label = format!("{prefix}{}", page_index + 1);
        let ops = build_page_number_ops(&font_name, &label, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_batch_watermark(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Watermark text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (cx, cy) = viewer_point_to_pdf(&doc, page_id, 400.0, 566.0)?;
        let ops = build_watermark_ops(&font_name, trimmed, cx, cy);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_batch_header(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Header text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 40.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_batch_footer(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Footer text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 1100.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_batch_border(path: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, inset: f64) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut drawn = 0u32;
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let ops = build_page_border_ops(&doc, page_id, inset)?;
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        drawn += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(drawn)
}

fn parity_batch_export_pdf(path: &Path, output_dir: &Path, start_page: u32, end_page: u32, odd: bool, local: bool) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let path_str = path.to_string_lossy().into_owned();
    let mut written = Vec::new();
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let file_name = format!("page-{:03}.pdf", page_index + 1);
        let output_path = output_dir.join(file_name);
        let out = extract_pdf_pages(path_str.clone(), output_path.to_string_lossy().into_owned(), page_index, page_index)?;
        written.push(out);
    }
    Ok(written)
}

#[allow(clippy::too_many_arguments)]
fn parity_batch_export_rendered(path: &Path, output_dir: &Path, start_page: u32, end_page: u32, odd: bool, local: bool, ext: &str, render: ParityPageRenderFn) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let mut written = Vec::new();
    for page_index in start_page..=end_page {
        if !parity_batch_match(page_index, start_page, end_page, odd, local) {
            continue;
        }
        let bytes = render(path, page_index, EXPORT_PNG_W, EXPORT_PNG_H)?;
        let file_name = format!("page-{:03}.{ext}", page_index + 1);
        let output_path = output_dir.join(file_name);
        write_png_output(&output_path, &bytes)?;
        written.push(output_path.to_string_lossy().into_owned());
    }
    Ok(written)
}

fn parity_batch_export_ico_doc(path: &Path, output_dir: &Path, odd: bool) -> Result<Vec<String>, String> {
    export_pages_by_parity_rendered(path, output_dir, odd, "ico", render_page_ico)
}


/// Global odd parity within page range — rotate_cw
#[tauri::command]
fn rotate_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, true, false, 90)
}


/// Global even parity within page range — rotate_cw
#[tauri::command]
fn rotate_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, false, false, 90)
}


/// Global odd parity within page range — rotate_ccw
#[tauri::command]
fn rotate_odd_pages_in_range_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, true, false, -90)
}


/// Global even parity within page range — rotate_ccw
#[tauri::command]
fn rotate_even_pages_in_range_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, false, false, -90)
}


/// Global odd parity within page range — rotate_180
#[tauri::command]
fn rotate_180_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, true, false, 180)
}


/// Global even parity within page range — rotate_180
#[tauri::command]
fn rotate_180_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, false, false, 180)
}


/// Global odd parity within page range — reset_rot
#[tauri::command]
fn reset_rotation_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_reset_rotation(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — reset_rot
#[tauri::command]
fn reset_rotation_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_reset_rotation(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global odd parity within page range — delete
#[tauri::command]
fn delete_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_delete(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — delete
#[tauri::command]
fn delete_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_delete(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global odd parity within page range — keep
#[tauri::command]
fn keep_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_keep(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — keep
#[tauri::command]
fn keep_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_keep(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global odd parity within page range — dup_append
#[tauri::command]
fn duplicate_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_append(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — dup_append
#[tauri::command]
fn duplicate_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_append(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global odd parity within page range — dup_before
#[tauri::command]
fn duplicate_odd_pages_in_range_before(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_before(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — dup_before
#[tauri::command]
fn duplicate_even_pages_in_range_before(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_before(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global odd parity within page range — dup_to_start
#[tauri::command]
fn duplicate_odd_pages_in_range_to_start(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_to_start(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — dup_to_start
#[tauri::command]
fn duplicate_even_pages_in_range_to_start(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_to_start(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global odd parity within page range — dup_to_end
#[tauri::command]
fn duplicate_odd_pages_in_range_to_end(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_to_end(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — dup_to_end
#[tauri::command]
fn duplicate_even_pages_in_range_to_end(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_to_end(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global odd parity within page range — flatten
#[tauri::command]
fn flatten_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_flatten(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — flatten
#[tauri::command]
fn flatten_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_flatten(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global odd parity within page range — reverse
#[tauri::command]
fn reverse_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_reverse(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — reverse
#[tauri::command]
fn reverse_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_reverse(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global parity move in range — move_odd_start
#[tauri::command]
fn move_odd_pages_in_range_to_start(path: String, start_page: u32, end_page: u32) -> Result<(), String> {
    parity_batch_move_seg(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global parity move in range — move_even_start
#[tauri::command]
fn move_even_pages_in_range_to_start(path: String, start_page: u32, end_page: u32) -> Result<(), String> {
    parity_batch_move_seg(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global parity move in range — move_odd_end
#[tauri::command]
fn move_odd_pages_in_range_to_end(path: String, start_page: u32, end_page: u32) -> Result<(), String> {
    parity_batch_move_seg(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global parity move in range — move_even_end
#[tauri::command]
fn move_even_pages_in_range_to_end(path: String, start_page: u32, end_page: u32) -> Result<(), String> {
    parity_batch_move_seg(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global odd parity within page range — sort_rot
#[tauri::command]
fn sort_odd_pages_in_range_by_rotation(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_rotation(&PathBuf::from(&path), start_page, end_page, true, false, false)
}


/// Global even parity within page range — sort_rot
#[tauri::command]
fn sort_even_pages_in_range_by_rotation(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_rotation(&PathBuf::from(&path), start_page, end_page, false, false, false)
}


/// Global odd parity within page range — sort_size
#[tauri::command]
fn sort_odd_pages_in_range_by_size(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_size(&PathBuf::from(&path), start_page, end_page, true, false, false)
}


/// Global even parity within page range — sort_size
#[tauri::command]
fn sort_even_pages_in_range_by_size(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_size(&PathBuf::from(&path), start_page, end_page, false, false, false)
}


/// Global odd parity within page range — crop
#[tauri::command]
fn crop_odd_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_crop(&PathBuf::from(&path), start_page, end_page, true, false, margin_top, margin_right, margin_bottom, margin_left)
}


/// Global even parity within page range — crop
#[tauri::command]
fn crop_even_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_crop(&PathBuf::from(&path), start_page, end_page, false, false, margin_top, margin_right, margin_bottom, margin_left)
}


/// Global odd parity within page range — expand
#[tauri::command]
fn expand_odd_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_expand(&PathBuf::from(&path), start_page, end_page, true, false, margin_top, margin_right, margin_bottom, margin_left)
}


/// Global even parity within page range — expand
#[tauri::command]
fn expand_even_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_expand(&PathBuf::from(&path), start_page, end_page, false, false, margin_top, margin_right, margin_bottom, margin_left)
}


/// Global odd parity within page range — shrink
#[tauri::command]
fn shrink_odd_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_shrink(&PathBuf::from(&path), start_page, end_page, true, false, margin_top, margin_right, margin_bottom, margin_left)
}


/// Global even parity within page range — shrink
#[tauri::command]
fn shrink_even_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_shrink(&PathBuf::from(&path), start_page, end_page, false, false, margin_top, margin_right, margin_bottom, margin_left)
}


/// Global odd parity within page range — clear_crop
#[tauri::command]
fn clear_crop_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_clear_crop(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Global even parity within page range — clear_crop
#[tauri::command]
fn clear_crop_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_clear_crop(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Global odd parity within page range — blank_before
#[tauri::command]
fn insert_blank_before_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_blank(&PathBuf::from(&path), start_page, end_page, true, false, false)
}


/// Global even parity within page range — blank_before
#[tauri::command]
fn insert_blank_before_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_blank(&PathBuf::from(&path), start_page, end_page, false, false, false)
}


/// Global odd parity within page range — blank_after
#[tauri::command]
fn insert_blank_after_odd_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_blank(&PathBuf::from(&path), start_page, end_page, true, false, true)
}


/// Global even parity within page range — blank_after
#[tauri::command]
fn insert_blank_after_even_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_blank(&PathBuf::from(&path), start_page, end_page, false, false, true)
}


/// Global odd parity within page range — bookmark
#[tauri::command]
fn bookmark_odd_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_batch_bookmark(&PathBuf::from(&path), start_page, end_page, true, false, prefix)
}


/// Global even parity within page range — bookmark
#[tauri::command]
fn bookmark_even_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_batch_bookmark(&PathBuf::from(&path), start_page, end_page, false, false, prefix)
}


/// Global odd parity within page range — page_size
#[tauri::command]
fn set_page_size_odd_pages_in_range(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_batch_page_size(&PathBuf::from(&path), start_page, end_page, true, false, &preset)
}


/// Global even parity within page range — page_size
#[tauri::command]
fn set_page_size_even_pages_in_range(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_batch_page_size(&PathBuf::from(&path), start_page, end_page, false, false, &preset)
}


/// Global odd parity within page range — extract
#[tauri::command]
fn extract_odd_pages_in_range(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_batch_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, true, false)
}


/// Global even parity within page range — extract
#[tauri::command]
fn extract_even_pages_in_range(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_batch_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, false, false)
}


/// Global odd parity within page range — page_numbers
#[tauri::command]
fn add_page_numbers_odd_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_batch_page_numbers(&PathBuf::from(&path), start_page, end_page, true, false, prefix)
}


/// Global even parity within page range — page_numbers
#[tauri::command]
fn add_page_numbers_even_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_batch_page_numbers(&PathBuf::from(&path), start_page, end_page, false, false, prefix)
}


/// Global odd parity within page range — watermark
#[tauri::command]
fn add_text_watermark_odd_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_watermark(&PathBuf::from(&path), start_page, end_page, true, false, &text)
}


/// Global even parity within page range — watermark
#[tauri::command]
fn add_text_watermark_even_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_watermark(&PathBuf::from(&path), start_page, end_page, false, false, &text)
}


/// Global odd parity within page range — header
#[tauri::command]
fn add_page_header_odd_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_header(&PathBuf::from(&path), start_page, end_page, true, false, &text)
}


/// Global even parity within page range — header
#[tauri::command]
fn add_page_header_even_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_header(&PathBuf::from(&path), start_page, end_page, false, false, &text)
}


/// Global odd parity within page range — footer
#[tauri::command]
fn add_page_footer_odd_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_footer(&PathBuf::from(&path), start_page, end_page, true, false, &text)
}


/// Global even parity within page range — footer
#[tauri::command]
fn add_page_footer_even_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_footer(&PathBuf::from(&path), start_page, end_page, false, false, &text)
}


/// Global odd parity within page range — border
#[tauri::command]
fn add_page_border_odd_pages_in_range(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_batch_border(&PathBuf::from(&path), start_page, end_page, true, false, inset)
}


/// Global even parity within page range — border
#[tauri::command]
fn add_page_border_even_pages_in_range(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_batch_border(&PathBuf::from(&path), start_page, end_page, false, false, inset)
}


/// Global odd parity within page range — export_pdf
#[tauri::command]
fn export_odd_pages_in_range_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false)
}


/// Global even parity within page range — export_pdf
#[tauri::command]
fn export_even_pages_in_range_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false)
}


/// Global odd parity within page range — export_png
#[tauri::command]
fn export_odd_pages_in_range_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false, "png", render_page_png)
}


/// Global even parity within page range — export_png
#[tauri::command]
fn export_even_pages_in_range_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false, "png", render_page_png)
}


/// Global odd parity within page range — export_jpeg
#[tauri::command]
fn export_odd_pages_in_range_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false, "jpeg", render_page_jpeg)
}


/// Global even parity within page range — export_jpeg
#[tauri::command]
fn export_even_pages_in_range_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false, "jpeg", render_page_jpeg)
}


/// Global odd parity within page range — export_webp
#[tauri::command]
fn export_odd_pages_in_range_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false, "webp", render_page_webp)
}


/// Global even parity within page range — export_webp
#[tauri::command]
fn export_even_pages_in_range_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false, "webp", render_page_webp)
}


/// Global odd parity within page range — export_bmp
#[tauri::command]
fn export_odd_pages_in_range_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false, "bmp", render_page_bmp)
}


/// Global even parity within page range — export_bmp
#[tauri::command]
fn export_even_pages_in_range_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false, "bmp", render_page_bmp)
}


/// Global odd parity within page range — export_tiff
#[tauri::command]
fn export_odd_pages_in_range_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false, "tiff", render_page_tiff)
}


/// Global even parity within page range — export_tiff
#[tauri::command]
fn export_even_pages_in_range_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false, "tiff", render_page_tiff)
}


/// Global odd parity within page range — export_gif
#[tauri::command]
fn export_odd_pages_in_range_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false, "gif", render_page_gif)
}


/// Global even parity within page range — export_gif
#[tauri::command]
fn export_even_pages_in_range_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false, "gif", render_page_gif)
}


/// Global odd parity within page range — export_ppm
#[tauri::command]
fn export_odd_pages_in_range_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false, "ppm", render_page_ppm)
}


/// Global even parity within page range — export_ppm
#[tauri::command]
fn export_even_pages_in_range_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false, "ppm", render_page_ppm)
}


/// Global odd parity within page range — export_tga
#[tauri::command]
fn export_odd_pages_in_range_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false, "tga", render_page_tga)
}


/// Global even parity within page range — export_tga
#[tauri::command]
fn export_even_pages_in_range_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false, "tga", render_page_tga)
}


/// Global odd parity within page range — export_ico
#[tauri::command]
fn export_odd_pages_in_range_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, false, "ico", render_page_ico)
}


/// Global even parity within page range — export_ico
#[tauri::command]
fn export_even_pages_in_range_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, false, "ico", render_page_ico)
}


/// Local odd parity within page range — rotate_cw
#[tauri::command]
fn rotate_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, true, true, 90)
}


/// Local even parity within page range — rotate_cw
#[tauri::command]
fn rotate_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, false, true, 90)
}


/// Local odd parity within page range — rotate_ccw
#[tauri::command]
fn rotate_range_local_odd_pages_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, true, true, -90)
}


/// Local even parity within page range — rotate_ccw
#[tauri::command]
fn rotate_range_local_even_pages_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, false, true, -90)
}


/// Local odd parity within page range — rotate_180
#[tauri::command]
fn rotate_180_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, true, true, 180)
}


/// Local even parity within page range — rotate_180
#[tauri::command]
fn rotate_180_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_rotate(&PathBuf::from(&path), start_page, end_page, false, true, 180)
}


/// Local odd parity within page range — reset_rot
#[tauri::command]
fn reset_rotation_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_reset_rotation(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity within page range — reset_rot
#[tauri::command]
fn reset_rotation_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_reset_rotation(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity within page range — delete
#[tauri::command]
fn delete_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_delete(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity within page range — delete
#[tauri::command]
fn delete_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_delete(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity within page range — keep
#[tauri::command]
fn keep_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_keep(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity within page range — keep
#[tauri::command]
fn keep_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_keep(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity within page range — dup_append
#[tauri::command]
fn duplicate_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_append(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity within page range — dup_append
#[tauri::command]
fn duplicate_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_append(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity within page range — dup_before
#[tauri::command]
fn duplicate_range_local_odd_pages_before(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_before(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity within page range — dup_before
#[tauri::command]
fn duplicate_range_local_even_pages_before(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_before(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity within page range — flatten
#[tauri::command]
fn flatten_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_flatten(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity within page range — flatten
#[tauri::command]
fn flatten_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_flatten(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Export odd pages as ICO
#[tauri::command]
fn export_odd_pages_ico(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_ico_doc(&PathBuf::from(&path), &PathBuf::from(&output_dir), true)
}


/// Export even pages as ICO
#[tauri::command]
fn export_even_pages_ico(path: String, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_ico_doc(&PathBuf::from(&path), &PathBuf::from(&output_dir), false)
}
