// Auto-generated by scripts/gen-parity-batch5.py - do not edit.
fn parity_mod4_dup_before(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    let indices = parity_mod4_indices(path, start_page, end_page, remainder)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in indices.iter().rev() {
        insert_pdf(path_str.clone(), path_str.clone(), idx, idx, idx)?;
    }
    Ok(indices.len() as u32)
}

fn parity_mod4_dup_to_start(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    let indices = parity_mod4_indices(path, start_page, end_page, remainder)?;
    let path_str = path.to_string_lossy().into_owned();
    for (offset, &idx) in indices.iter().rev().enumerate() {
        let offset = offset as u32;
        let source = idx + offset;
        insert_pdf(path_str.clone(), path_str.clone(), offset, source, source)?;
    }
    Ok(indices.len() as u32)
}

fn parity_mod4_dup_to_end(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    let indices = parity_mod4_indices(path, start_page, end_page, remainder)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in indices.iter().rev() {
        let new_idx = duplicate_page(path_str.clone(), idx)?;
        move_page_to_last(path_str.clone(), new_idx)?;
    }
    Ok(indices.len() as u32)
}

#[allow(clippy::too_many_arguments)]
fn parity_mod4_expand(path: &Path, start_page: u32, end_page: u32, remainder: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut expanded = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_expand_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        expanded += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(expanded)
}

#[allow(clippy::too_many_arguments)]
fn parity_mod4_shrink(path: &Path, start_page: u32, end_page: u32, remainder: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut shrunk = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_shrink_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        shrunk += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(shrunk)
}

fn parity_mod4_clear_crop(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut cleared = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        if doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"CropBox").is_some() {
            cleared += 1;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cleared)
}

fn parity_mod4_blank(path: &Path, start_page: u32, end_page: u32, remainder: u32, after: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod4_match(*i as u32, start_page, end_page, remainder))
        .collect();
    for &idx in indices.iter().rev() {
        let page_id = create_blank_page(&mut doc, pages_ref);
        let at = if after { idx + 1 } else { idx };
        kids.insert(at, Object::Reference(page_id));
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(indices.len() as u32)
}

fn parity_mod4_bookmark(path: &Path, start_page: u32, end_page: u32, remainder: u32, prefix: Option<String>) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let prefix = prefix.unwrap_or_else(|| "Page ".to_string());
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut count = 0u32;
    for (page_num, page_id) in doc.get_pages() {
        let page_index = page_num - 1;
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let title = format!("{prefix}{page_num}");
        append_outline_item(&mut doc, &title, page_id)?;
        count += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(count)
}

fn parity_mod4_page_size(path: &Path, start_page: u32, end_page: u32, remainder: u32, preset: &str) -> Result<u32, String> {
    let (w, h) = page_size_preset_dims(preset)?;
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut resized = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let page = doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?;
        page.set(
            "MediaBox",
            Object::Array(vec![Object::Integer(0), Object::Integer(0), Object::Real(w as f32), Object::Real(h as f32)]),
        );
        page.remove(b"CropBox");
        resized += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(resized)
}

fn parity_mod4_page_numbers(path: &Path, start_page: u32, end_page: u32, remainder: u32, prefix: Option<String>) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let prefix = prefix.unwrap_or_default();
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 1100.0)?;
        let label = format!("{prefix}{}", page_index + 1);
        let ops = build_page_number_ops(&font_name, &label, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_mod4_watermark(path: &Path, start_page: u32, end_page: u32, remainder: u32, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Watermark text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (cx, cy) = viewer_point_to_pdf(&doc, page_id, 400.0, 566.0)?;
        let ops = build_watermark_ops(&font_name, trimmed, cx, cy);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_mod4_header(path: &Path, start_page: u32, end_page: u32, remainder: u32, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Header text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 40.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_mod4_footer(path: &Path, start_page: u32, end_page: u32, remainder: u32, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Footer text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 1100.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_mod4_border(path: &Path, start_page: u32, end_page: u32, remainder: u32, inset: f64) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut drawn = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let ops = build_page_border_ops(&doc, page_id, inset)?;
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        drawn += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(drawn)
}



/// Mod-4 remainder 0 in range - dup_before
#[tauri::command]
fn duplicate_mod4_0_pages_in_range_before_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_before(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - dup_before
#[tauri::command]
fn duplicate_mod4_1_pages_in_range_before_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_before(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - dup_before
#[tauri::command]
fn duplicate_mod4_2_pages_in_range_before_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_before(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - dup_before
#[tauri::command]
fn duplicate_mod4_3_pages_in_range_before_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_before(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - dup_to_start
#[tauri::command]
fn duplicate_mod4_0_pages_in_range_to_start_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_to_start(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - dup_to_start
#[tauri::command]
fn duplicate_mod4_1_pages_in_range_to_start_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_to_start(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - dup_to_start
#[tauri::command]
fn duplicate_mod4_2_pages_in_range_to_start_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_to_start(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - dup_to_start
#[tauri::command]
fn duplicate_mod4_3_pages_in_range_to_start_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_to_start(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - dup_to_end
#[tauri::command]
fn duplicate_mod4_0_pages_in_range_to_end_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_to_end(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - dup_to_end
#[tauri::command]
fn duplicate_mod4_1_pages_in_range_to_end_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_to_end(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - dup_to_end
#[tauri::command]
fn duplicate_mod4_2_pages_in_range_to_end_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_to_end(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - dup_to_end
#[tauri::command]
fn duplicate_mod4_3_pages_in_range_to_end_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_to_end(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - expand
#[tauri::command]
fn expand_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_expand(&PathBuf::from(&path), start_page, end_page, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 1 in range - expand
#[tauri::command]
fn expand_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_expand(&PathBuf::from(&path), start_page, end_page, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 2 in range - expand
#[tauri::command]
fn expand_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_expand(&PathBuf::from(&path), start_page, end_page, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 3 in range - expand
#[tauri::command]
fn expand_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_expand(&PathBuf::from(&path), start_page, end_page, 3, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 0 in range - shrink
#[tauri::command]
fn shrink_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_shrink(&PathBuf::from(&path), start_page, end_page, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 1 in range - shrink
#[tauri::command]
fn shrink_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_shrink(&PathBuf::from(&path), start_page, end_page, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 2 in range - shrink
#[tauri::command]
fn shrink_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_shrink(&PathBuf::from(&path), start_page, end_page, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 3 in range - shrink
#[tauri::command]
fn shrink_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_shrink(&PathBuf::from(&path), start_page, end_page, 3, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 0 in range - clear_crop
#[tauri::command]
fn clear_crop_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_clear_crop(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - clear_crop
#[tauri::command]
fn clear_crop_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_clear_crop(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - clear_crop
#[tauri::command]
fn clear_crop_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_clear_crop(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - clear_crop
#[tauri::command]
fn clear_crop_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_clear_crop(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - blank_before
#[tauri::command]
fn insert_blank_before_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_blank(&PathBuf::from(&path), start_page, end_page, 0, false)
}


/// Mod-4 remainder 1 in range - blank_before
#[tauri::command]
fn insert_blank_before_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_blank(&PathBuf::from(&path), start_page, end_page, 1, false)
}


/// Mod-4 remainder 2 in range - blank_before
#[tauri::command]
fn insert_blank_before_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_blank(&PathBuf::from(&path), start_page, end_page, 2, false)
}


/// Mod-4 remainder 3 in range - blank_before
#[tauri::command]
fn insert_blank_before_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_blank(&PathBuf::from(&path), start_page, end_page, 3, false)
}


/// Mod-4 remainder 0 in range - blank_after
#[tauri::command]
fn insert_blank_after_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_blank(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Mod-4 remainder 1 in range - blank_after
#[tauri::command]
fn insert_blank_after_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_blank(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Mod-4 remainder 2 in range - blank_after
#[tauri::command]
fn insert_blank_after_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_blank(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// Mod-4 remainder 3 in range - blank_after
#[tauri::command]
fn insert_blank_after_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_blank(&PathBuf::from(&path), start_page, end_page, 3, true)
}


/// Mod-4 remainder 0 in range - bookmark
#[tauri::command]
fn bookmark_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_mod4_bookmark(&PathBuf::from(&path), start_page, end_page, 0, prefix)
}


/// Mod-4 remainder 1 in range - bookmark
#[tauri::command]
fn bookmark_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_mod4_bookmark(&PathBuf::from(&path), start_page, end_page, 1, prefix)
}


/// Mod-4 remainder 2 in range - bookmark
#[tauri::command]
fn bookmark_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_mod4_bookmark(&PathBuf::from(&path), start_page, end_page, 2, prefix)
}


/// Mod-4 remainder 3 in range - bookmark
#[tauri::command]
fn bookmark_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_mod4_bookmark(&PathBuf::from(&path), start_page, end_page, 3, prefix)
}


/// Mod-4 remainder 0 in range - page_size
#[tauri::command]
fn set_page_size_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_mod4_page_size(&PathBuf::from(&path), start_page, end_page, 0, &preset)
}


/// Mod-4 remainder 1 in range - page_size
#[tauri::command]
fn set_page_size_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_mod4_page_size(&PathBuf::from(&path), start_page, end_page, 1, &preset)
}


/// Mod-4 remainder 2 in range - page_size
#[tauri::command]
fn set_page_size_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_mod4_page_size(&PathBuf::from(&path), start_page, end_page, 2, &preset)
}


/// Mod-4 remainder 3 in range - page_size
#[tauri::command]
fn set_page_size_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_mod4_page_size(&PathBuf::from(&path), start_page, end_page, 3, &preset)
}


/// Mod-4 remainder 0 in range - page_numbers
#[tauri::command]
fn add_page_numbers_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_mod4_page_numbers(&PathBuf::from(&path), start_page, end_page, 0, prefix)
}


/// Mod-4 remainder 1 in range - page_numbers
#[tauri::command]
fn add_page_numbers_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_mod4_page_numbers(&PathBuf::from(&path), start_page, end_page, 1, prefix)
}


/// Mod-4 remainder 2 in range - page_numbers
#[tauri::command]
fn add_page_numbers_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_mod4_page_numbers(&PathBuf::from(&path), start_page, end_page, 2, prefix)
}


/// Mod-4 remainder 3 in range - page_numbers
#[tauri::command]
fn add_page_numbers_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_mod4_page_numbers(&PathBuf::from(&path), start_page, end_page, 3, prefix)
}


/// Mod-4 remainder 0 in range - watermark
#[tauri::command]
fn add_text_watermark_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_watermark(&PathBuf::from(&path), start_page, end_page, 0, &text)
}


/// Mod-4 remainder 1 in range - watermark
#[tauri::command]
fn add_text_watermark_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_watermark(&PathBuf::from(&path), start_page, end_page, 1, &text)
}


/// Mod-4 remainder 2 in range - watermark
#[tauri::command]
fn add_text_watermark_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_watermark(&PathBuf::from(&path), start_page, end_page, 2, &text)
}


/// Mod-4 remainder 3 in range - watermark
#[tauri::command]
fn add_text_watermark_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_watermark(&PathBuf::from(&path), start_page, end_page, 3, &text)
}


/// Mod-4 remainder 0 in range - header
#[tauri::command]
fn add_page_header_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_header(&PathBuf::from(&path), start_page, end_page, 0, &text)
}


/// Mod-4 remainder 1 in range - header
#[tauri::command]
fn add_page_header_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_header(&PathBuf::from(&path), start_page, end_page, 1, &text)
}


/// Mod-4 remainder 2 in range - header
#[tauri::command]
fn add_page_header_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_header(&PathBuf::from(&path), start_page, end_page, 2, &text)
}


/// Mod-4 remainder 3 in range - header
#[tauri::command]
fn add_page_header_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_header(&PathBuf::from(&path), start_page, end_page, 3, &text)
}


/// Mod-4 remainder 0 in range - footer
#[tauri::command]
fn add_page_footer_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_footer(&PathBuf::from(&path), start_page, end_page, 0, &text)
}


/// Mod-4 remainder 1 in range - footer
#[tauri::command]
fn add_page_footer_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_footer(&PathBuf::from(&path), start_page, end_page, 1, &text)
}


/// Mod-4 remainder 2 in range - footer
#[tauri::command]
fn add_page_footer_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_footer(&PathBuf::from(&path), start_page, end_page, 2, &text)
}


/// Mod-4 remainder 3 in range - footer
#[tauri::command]
fn add_page_footer_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_mod4_footer(&PathBuf::from(&path), start_page, end_page, 3, &text)
}


/// Mod-4 remainder 0 in range - border
#[tauri::command]
fn add_page_border_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_mod4_border(&PathBuf::from(&path), start_page, end_page, 0, inset)
}


/// Mod-4 remainder 1 in range - border
#[tauri::command]
fn add_page_border_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_mod4_border(&PathBuf::from(&path), start_page, end_page, 1, inset)
}


/// Mod-4 remainder 2 in range - border
#[tauri::command]
fn add_page_border_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_mod4_border(&PathBuf::from(&path), start_page, end_page, 2, inset)
}


/// Mod-4 remainder 3 in range - border
#[tauri::command]
fn add_page_border_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_mod4_border(&PathBuf::from(&path), start_page, end_page, 3, inset)
}


/// Mod-4 remainder 0 in range - export_webp
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "webp", render_page_webp)
}


/// Mod-4 remainder 1 in range - export_webp
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "webp", render_page_webp)
}


/// Mod-4 remainder 2 in range - export_webp
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "webp", render_page_webp)
}


/// Mod-4 remainder 3 in range - export_webp
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3, "webp", render_page_webp)
}


/// Mod-4 remainder 0 in range - export_bmp
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "bmp", render_page_bmp)
}


/// Mod-4 remainder 1 in range - export_bmp
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "bmp", render_page_bmp)
}


/// Mod-4 remainder 2 in range - export_bmp
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "bmp", render_page_bmp)
}


/// Mod-4 remainder 3 in range - export_bmp
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3, "bmp", render_page_bmp)
}


/// Mod-4 remainder 0 in range - export_tiff
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "tiff", render_page_tiff)
}


/// Mod-4 remainder 1 in range - export_tiff
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "tiff", render_page_tiff)
}


/// Mod-4 remainder 2 in range - export_tiff
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "tiff", render_page_tiff)
}


/// Mod-4 remainder 3 in range - export_tiff
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3, "tiff", render_page_tiff)
}


/// Mod-4 remainder 0 in range - export_gif
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "gif", render_page_gif)
}


/// Mod-4 remainder 1 in range - export_gif
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "gif", render_page_gif)
}


/// Mod-4 remainder 2 in range - export_gif
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "gif", render_page_gif)
}


/// Mod-4 remainder 3 in range - export_gif
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3, "gif", render_page_gif)
}


/// Mod-4 remainder 0 in range - export_ppm
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "ppm", render_page_ppm)
}


/// Mod-4 remainder 1 in range - export_ppm
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "ppm", render_page_ppm)
}


/// Mod-4 remainder 2 in range - export_ppm
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "ppm", render_page_ppm)
}


/// Mod-4 remainder 3 in range - export_ppm
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3, "ppm", render_page_ppm)
}


/// Mod-4 remainder 0 in range - export_tga
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "tga", render_page_tga)
}


/// Mod-4 remainder 1 in range - export_tga
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "tga", render_page_tga)
}


/// Mod-4 remainder 2 in range - export_tga
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "tga", render_page_tga)
}


/// Mod-4 remainder 3 in range - export_tga
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3, "tga", render_page_tga)
}


/// Mod-4 remainder 0 in range - export_ico
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "ico", render_page_ico)
}


/// Mod-4 remainder 1 in range - export_ico
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "ico", render_page_ico)
}


/// Mod-4 remainder 2 in range - export_ico
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "ico", render_page_ico)
}


/// Mod-4 remainder 3 in range - export_ico
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3, "ico", render_page_ico)
}
