// Auto-generated by scripts/gen-parity-batch2.py - do not edit.
fn parity_mod3_match(page_index: u32, start_page: u32, end_page: u32, remainder: u32) -> bool {
    if page_index < start_page || page_index > end_page {
        return false;
    }
    (page_index - start_page) % 3 == remainder
}

fn parity_mod3_indices(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<Vec<u32>, String> {
    validate_page_range(path, start_page, end_page)?;
    Ok((start_page..=end_page)
        .filter(|i| parity_mod3_match(*i, start_page, end_page, remainder))
        .collect())
}

fn parity_mod3_rotate(path: &Path, start_page: u32, end_page: u32, remainder: u32, delta: i64) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut rotated = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod3_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let current = page_rotation(&doc, page_id);
        set_page_rotation(&mut doc, page_id, current + delta)?;
        rotated += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(rotated)
}

fn parity_mod3_reset_rotation(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut reset = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod3_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        set_page_rotation(&mut doc, page_id, 0)?;
        reset += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(reset)
}

fn parity_mod3_delete(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let mut to_delete: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod3_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if to_delete.is_empty() {
        return Ok(0);
    }
    if kids.len() - to_delete.len() < 1 {
        return Err("Cannot delete every page in the document".to_string());
    }
    to_delete.sort_by(|a, b| b.cmp(a));
    let deleted = to_delete.len() as u32;
    for idx in to_delete {
        kids.remove(idx);
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_mod3_keep(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (kids, _) = get_pages_kids(&doc)?;
    let kept: Vec<Object> = kids
        .iter()
        .enumerate()
        .filter(|(i, _)| {
            let idx = *i as u32;
            if idx < start_page || idx > end_page {
                return true;
            }
            parity_mod3_match(idx, start_page, end_page, remainder)
        })
        .map(|(_, kid)| kid.clone())
        .collect();
    if kept.is_empty() {
        return Err("No pages would remain after keep filter".to_string());
    }
    if kept.len() == kids.len() {
        return Err("Nothing to delete - all pages in range match the keep filter".to_string());
    }
    let deleted = (kids.len() - kept.len()) as u32;
    set_pages_kids(&mut doc, pages_ref, kept)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_mod3_dup_append(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    let indices = parity_mod3_indices(path, start_page, end_page, remainder)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in &indices {
        duplicate_page(path_str.clone(), idx)?;
    }
    Ok(indices.len() as u32)
}




fn parity_mod3_flatten(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut removed = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod3_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let count = doc
            .get_dictionary(page_id)
            .ok()
            .and_then(|d| d.get(b"Annots").ok())
            .and_then(|o| o.as_array().ok())
            .map(|a| a.len() as u32)
            .unwrap_or(0);
        if count > 0 {
            doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"Annots");
            removed += count;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(removed)
}

fn parity_mod3_reverse(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod3_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut parity_kids: Vec<Object> = parity_indices.iter().map(|i| kids[*i].clone()).collect();
    parity_kids.reverse();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = parity_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}




#[allow(clippy::too_many_arguments)]
fn parity_mod3_crop(path: &Path, start_page: u32, end_page: u32, remainder: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut cropped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod3_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_crop_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        cropped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cropped)
}







fn parity_mod3_extract(path: &Path, output_path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<String, String> {
    if path == output_path {
        return Err("Output path must differ from the source PDF".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let doc = Document::load(path).map_err(|e| e.to_string())?;
    let (all_kids, pages_ref) = get_pages_kids(&doc)?;
    let subset: Vec<Object> = all_kids
        .iter()
        .enumerate()
        .filter(|(i, _)| parity_mod3_match(*i as u32, start_page, end_page, remainder))
        .map(|(_, kid)| kid.clone())
        .collect();
    if subset.is_empty() {
        return Err("No pages match the extract filter in range".to_string());
    }
    let mut out = Document::with_version(doc.version.clone());
    set_pages_kids(&mut out, pages_ref, subset)?;
    out.save(output_path).map_err(|e| e.to_string())?;
    Ok(output_path.to_string_lossy().into_owned())
}






fn parity_mod3_export_pdf(path: &Path, output_dir: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let path_str = path.to_string_lossy().into_owned();
    let mut written = Vec::new();
    for page_index in start_page..=end_page {
        if !parity_mod3_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let file_name = format!("page-{:03}.pdf", page_index + 1);
        let output_path = output_dir.join(file_name);
        let out = extract_pdf_pages(path_str.clone(), output_path.to_string_lossy().into_owned(), page_index, page_index)?;
        written.push(out);
    }
    Ok(written)
}

#[allow(clippy::too_many_arguments)]
fn parity_mod3_export_rendered(path: &Path, output_dir: &Path, start_page: u32, end_page: u32, remainder: u32, ext: &str, render: ParityPageRenderFn) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let mut written = Vec::new();
    for page_index in start_page..=end_page {
        if !parity_mod3_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let bytes = render(path, page_index, EXPORT_PNG_W, EXPORT_PNG_H)?;
        let file_name = format!("page-{:03}.{ext}", page_index + 1);
        let output_path = output_dir.join(file_name);
        write_png_output(&output_path, &bytes)?;
        written.push(output_path.to_string_lossy().into_owned());
    }
    Ok(written)
}



/// Local odd parity in range - reverse
#[tauri::command]
fn reverse_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_reverse(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity in range - reverse
#[tauri::command]
fn reverse_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_reverse(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity in range - move_odd_start
#[tauri::command]
fn move_odd_range_local_pages_to_start(path: String, start_page: u32, end_page: u32) -> Result<(), String> {
    parity_batch_move_seg(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity in range - move_even_start
#[tauri::command]
fn move_even_range_local_pages_to_start(path: String, start_page: u32, end_page: u32) -> Result<(), String> {
    parity_batch_move_seg(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity in range - move_odd_end
#[tauri::command]
fn move_odd_range_local_pages_to_end(path: String, start_page: u32, end_page: u32) -> Result<(), String> {
    parity_batch_move_seg(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local even parity in range - move_even_end
#[tauri::command]
fn move_even_range_local_pages_to_end(path: String, start_page: u32, end_page: u32) -> Result<(), String> {
    parity_batch_move_seg(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local odd parity in range - sort_rot
#[tauri::command]
fn sort_range_local_odd_pages_by_rotation(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_rotation(&PathBuf::from(&path), start_page, end_page, true, true, false)
}


/// Local even parity in range - sort_rot
#[tauri::command]
fn sort_range_local_even_pages_by_rotation(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_rotation(&PathBuf::from(&path), start_page, end_page, false, true, false)
}


/// Local odd parity in range - sort_size
#[tauri::command]
fn sort_range_local_odd_pages_by_size(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_size(&PathBuf::from(&path), start_page, end_page, true, true, false)
}


/// Local even parity in range - sort_size
#[tauri::command]
fn sort_range_local_even_pages_by_size(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_size(&PathBuf::from(&path), start_page, end_page, false, true, false)
}


/// Local odd parity in range - dup_to_start
#[tauri::command]
fn duplicate_range_local_odd_pages_to_start(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_to_start(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity in range - dup_to_start
#[tauri::command]
fn duplicate_range_local_even_pages_to_start(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_to_start(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity in range - dup_to_end
#[tauri::command]
fn duplicate_range_local_odd_pages_to_end(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_to_end(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity in range - dup_to_end
#[tauri::command]
fn duplicate_range_local_even_pages_to_end(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_dup_to_end(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity in range - crop
#[tauri::command]
fn crop_range_local_odd_pages(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_crop(&PathBuf::from(&path), start_page, end_page, true, true, margin_top, margin_right, margin_bottom, margin_left)
}


/// Local even parity in range - crop
#[tauri::command]
fn crop_range_local_even_pages(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_crop(&PathBuf::from(&path), start_page, end_page, false, true, margin_top, margin_right, margin_bottom, margin_left)
}


/// Local odd parity in range - expand
#[tauri::command]
fn expand_range_local_odd_pages(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_expand(&PathBuf::from(&path), start_page, end_page, true, true, margin_top, margin_right, margin_bottom, margin_left)
}


/// Local even parity in range - expand
#[tauri::command]
fn expand_range_local_even_pages(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_expand(&PathBuf::from(&path), start_page, end_page, false, true, margin_top, margin_right, margin_bottom, margin_left)
}


/// Local odd parity in range - shrink
#[tauri::command]
fn shrink_range_local_odd_pages(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_shrink(&PathBuf::from(&path), start_page, end_page, true, true, margin_top, margin_right, margin_bottom, margin_left)
}


/// Local even parity in range - shrink
#[tauri::command]
fn shrink_range_local_even_pages(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_batch_shrink(&PathBuf::from(&path), start_page, end_page, false, true, margin_top, margin_right, margin_bottom, margin_left)
}


/// Local odd parity in range - clear_crop
#[tauri::command]
fn clear_crop_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_clear_crop(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Local even parity in range - clear_crop
#[tauri::command]
fn clear_crop_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_clear_crop(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Local odd parity in range - blank_before
#[tauri::command]
fn insert_blank_before_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_blank(&PathBuf::from(&path), start_page, end_page, true, true, false)
}


/// Local even parity in range - blank_before
#[tauri::command]
fn insert_blank_before_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_blank(&PathBuf::from(&path), start_page, end_page, false, true, false)
}


/// Local odd parity in range - blank_after
#[tauri::command]
fn insert_blank_after_range_local_odd_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_blank(&PathBuf::from(&path), start_page, end_page, true, true, true)
}


/// Local even parity in range - blank_after
#[tauri::command]
fn insert_blank_after_range_local_even_pages(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_blank(&PathBuf::from(&path), start_page, end_page, false, true, true)
}


/// Local odd parity in range - bookmark
#[tauri::command]
fn bookmark_range_local_odd_pages(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_batch_bookmark(&PathBuf::from(&path), start_page, end_page, true, true, prefix)
}


/// Local even parity in range - bookmark
#[tauri::command]
fn bookmark_range_local_even_pages(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_batch_bookmark(&PathBuf::from(&path), start_page, end_page, false, true, prefix)
}


/// Local odd parity in range - page_size
#[tauri::command]
fn set_page_size_range_local_odd_pages(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_batch_page_size(&PathBuf::from(&path), start_page, end_page, true, true, &preset)
}


/// Local even parity in range - page_size
#[tauri::command]
fn set_page_size_range_local_even_pages(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_batch_page_size(&PathBuf::from(&path), start_page, end_page, false, true, &preset)
}


/// Local odd parity in range - extract
#[tauri::command]
fn extract_range_local_odd_pages(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_batch_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, true, true)
}


/// Local even parity in range - extract
#[tauri::command]
fn extract_range_local_even_pages(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_batch_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, false, true)
}


/// Local odd parity in range - page_numbers
#[tauri::command]
fn add_page_numbers_range_local_odd_pages(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_batch_page_numbers(&PathBuf::from(&path), start_page, end_page, true, true, prefix)
}


/// Local even parity in range - page_numbers
#[tauri::command]
fn add_page_numbers_range_local_even_pages(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_batch_page_numbers(&PathBuf::from(&path), start_page, end_page, false, true, prefix)
}


/// Local odd parity in range - watermark
#[tauri::command]
fn add_text_watermark_range_local_odd_pages(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_watermark(&PathBuf::from(&path), start_page, end_page, true, true, &text)
}


/// Local even parity in range - watermark
#[tauri::command]
fn add_text_watermark_range_local_even_pages(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_watermark(&PathBuf::from(&path), start_page, end_page, false, true, &text)
}


/// Local odd parity in range - header
#[tauri::command]
fn add_page_header_range_local_odd_pages(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_header(&PathBuf::from(&path), start_page, end_page, true, true, &text)
}


/// Local even parity in range - header
#[tauri::command]
fn add_page_header_range_local_even_pages(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_header(&PathBuf::from(&path), start_page, end_page, false, true, &text)
}


/// Local odd parity in range - footer
#[tauri::command]
fn add_page_footer_range_local_odd_pages(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_footer(&PathBuf::from(&path), start_page, end_page, true, true, &text)
}


/// Local even parity in range - footer
#[tauri::command]
fn add_page_footer_range_local_even_pages(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_batch_footer(&PathBuf::from(&path), start_page, end_page, false, true, &text)
}


/// Local odd parity in range - border
#[tauri::command]
fn add_page_border_range_local_odd_pages(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_batch_border(&PathBuf::from(&path), start_page, end_page, true, true, inset)
}


/// Local even parity in range - border
#[tauri::command]
fn add_page_border_range_local_even_pages(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_batch_border(&PathBuf::from(&path), start_page, end_page, false, true, inset)
}


/// Local odd parity in range - export_pdf
#[tauri::command]
fn export_range_local_odd_pages_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, true)
}


/// Local even parity in range - export_pdf
#[tauri::command]
fn export_range_local_even_pages_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, true)
}


/// Local odd parity in range - export_png
#[tauri::command]
fn export_range_local_odd_pages_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, true, "png", render_page_png)
}


/// Local even parity in range - export_png
#[tauri::command]
fn export_range_local_even_pages_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, true, "png", render_page_png)
}


/// Local odd parity in range - export_jpeg
#[tauri::command]
fn export_range_local_odd_pages_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, true, "jpeg", render_page_jpeg)
}


/// Local even parity in range - export_jpeg
#[tauri::command]
fn export_range_local_even_pages_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, true, "jpeg", render_page_jpeg)
}


/// Local odd parity in range - export_webp
#[tauri::command]
fn export_range_local_odd_pages_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, true, "webp", render_page_webp)
}


/// Local even parity in range - export_webp
#[tauri::command]
fn export_range_local_even_pages_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, true, "webp", render_page_webp)
}


/// Local odd parity in range - export_bmp
#[tauri::command]
fn export_range_local_odd_pages_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, true, "bmp", render_page_bmp)
}


/// Local even parity in range - export_bmp
#[tauri::command]
fn export_range_local_even_pages_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, true, "bmp", render_page_bmp)
}


/// Local odd parity in range - export_tiff
#[tauri::command]
fn export_range_local_odd_pages_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, true, "tiff", render_page_tiff)
}


/// Local even parity in range - export_tiff
#[tauri::command]
fn export_range_local_even_pages_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, true, "tiff", render_page_tiff)
}


/// Local odd parity in range - export_gif
#[tauri::command]
fn export_range_local_odd_pages_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, true, "gif", render_page_gif)
}


/// Local even parity in range - export_gif
#[tauri::command]
fn export_range_local_even_pages_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, true, "gif", render_page_gif)
}


/// Local odd parity in range - export_ppm
#[tauri::command]
fn export_range_local_odd_pages_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, true, "ppm", render_page_ppm)
}


/// Local even parity in range - export_ppm
#[tauri::command]
fn export_range_local_even_pages_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, true, "ppm", render_page_ppm)
}


/// Local odd parity in range - export_tga
#[tauri::command]
fn export_range_local_odd_pages_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, true, "tga", render_page_tga)
}


/// Local even parity in range - export_tga
#[tauri::command]
fn export_range_local_even_pages_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_batch_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, true, "tga", render_page_tga)
}


/// Mod-3 remainder 0 in range - rotate_cw
#[tauri::command]
fn rotate_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_rotate(&PathBuf::from(&path), start_page, end_page, 0, 90)
}


/// Mod-3 remainder 1 in range - rotate_cw
#[tauri::command]
fn rotate_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_rotate(&PathBuf::from(&path), start_page, end_page, 1, 90)
}


/// Mod-3 remainder 2 in range - rotate_cw
#[tauri::command]
fn rotate_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_rotate(&PathBuf::from(&path), start_page, end_page, 2, 90)
}


/// Mod-3 remainder 0 in range - rotate_ccw
#[tauri::command]
fn rotate_mod3_0_pages_in_range_mod3_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_rotate(&PathBuf::from(&path), start_page, end_page, 0, -90)
}


/// Mod-3 remainder 1 in range - rotate_ccw
#[tauri::command]
fn rotate_mod3_1_pages_in_range_mod3_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_rotate(&PathBuf::from(&path), start_page, end_page, 1, -90)
}


/// Mod-3 remainder 2 in range - rotate_ccw
#[tauri::command]
fn rotate_mod3_2_pages_in_range_mod3_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_rotate(&PathBuf::from(&path), start_page, end_page, 2, -90)
}


/// Mod-3 remainder 0 in range - rotate_180
#[tauri::command]
fn rotate_180_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_rotate(&PathBuf::from(&path), start_page, end_page, 0, 180)
}


/// Mod-3 remainder 1 in range - rotate_180
#[tauri::command]
fn rotate_180_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_rotate(&PathBuf::from(&path), start_page, end_page, 1, 180)
}


/// Mod-3 remainder 2 in range - rotate_180
#[tauri::command]
fn rotate_180_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_rotate(&PathBuf::from(&path), start_page, end_page, 2, 180)
}


/// Mod-3 remainder 0 in range - reset_rot
#[tauri::command]
fn reset_rotation_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_reset_rotation(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-3 remainder 1 in range - reset_rot
#[tauri::command]
fn reset_rotation_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_reset_rotation(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-3 remainder 2 in range - reset_rot
#[tauri::command]
fn reset_rotation_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_reset_rotation(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-3 remainder 0 in range - delete
#[tauri::command]
fn delete_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_delete(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-3 remainder 1 in range - delete
#[tauri::command]
fn delete_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_delete(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-3 remainder 2 in range - delete
#[tauri::command]
fn delete_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_delete(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-3 remainder 0 in range - keep
#[tauri::command]
fn keep_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_keep(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-3 remainder 1 in range - keep
#[tauri::command]
fn keep_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_keep(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-3 remainder 2 in range - keep
#[tauri::command]
fn keep_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_keep(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-3 remainder 0 in range - dup_append
#[tauri::command]
fn duplicate_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_dup_append(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-3 remainder 1 in range - dup_append
#[tauri::command]
fn duplicate_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_dup_append(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-3 remainder 2 in range - dup_append
#[tauri::command]
fn duplicate_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_dup_append(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-3 remainder 0 in range - flatten
#[tauri::command]
fn flatten_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_flatten(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-3 remainder 1 in range - flatten
#[tauri::command]
fn flatten_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_flatten(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-3 remainder 2 in range - flatten
#[tauri::command]
fn flatten_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_flatten(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-3 remainder 0 in range - reverse
#[tauri::command]
fn reverse_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_reverse(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-3 remainder 1 in range - reverse
#[tauri::command]
fn reverse_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_reverse(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-3 remainder 2 in range - reverse
#[tauri::command]
fn reverse_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_reverse(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-3 remainder 0 in range - crop
#[tauri::command]
fn crop_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod3_crop(&PathBuf::from(&path), start_page, end_page, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-3 remainder 1 in range - crop
#[tauri::command]
fn crop_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod3_crop(&PathBuf::from(&path), start_page, end_page, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-3 remainder 2 in range - crop
#[tauri::command]
fn crop_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod3_crop(&PathBuf::from(&path), start_page, end_page, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-3 remainder 0 in range - extract
#[tauri::command]
fn extract_mod3_0_pages_in_range_mod3(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_mod3_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 0)
}


/// Mod-3 remainder 1 in range - extract
#[tauri::command]
fn extract_mod3_1_pages_in_range_mod3(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_mod3_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 1)
}


/// Mod-3 remainder 2 in range - extract
#[tauri::command]
fn extract_mod3_2_pages_in_range_mod3(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_mod3_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 2)
}


/// Mod-3 remainder 0 in range - export_pdf
#[tauri::command]
fn export_mod3_0_pages_in_range_mod3_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod3_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0)
}


/// Mod-3 remainder 1 in range - export_pdf
#[tauri::command]
fn export_mod3_1_pages_in_range_mod3_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod3_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1)
}


/// Mod-3 remainder 2 in range - export_pdf
#[tauri::command]
fn export_mod3_2_pages_in_range_mod3_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod3_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2)
}


/// Mod-3 remainder 0 in range - export_png
#[tauri::command]
fn export_mod3_0_pages_in_range_mod3_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod3_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "png", render_page_png)
}


/// Mod-3 remainder 1 in range - export_png
#[tauri::command]
fn export_mod3_1_pages_in_range_mod3_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod3_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "png", render_page_png)
}


/// Mod-3 remainder 2 in range - export_png
#[tauri::command]
fn export_mod3_2_pages_in_range_mod3_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod3_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "png", render_page_png)
}


/// Mod-3 remainder 0 in range - export_jpeg
#[tauri::command]
fn export_mod3_0_pages_in_range_mod3_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod3_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "jpeg", render_page_jpeg)
}
