// Auto-generated by scripts/gen-parity-batch4.py - do not edit.
fn parity_half_dup_before(path: &Path, start_page: u32, end_page: u32, first_half: bool) -> Result<u32, String> {
    let indices = parity_half_indices(path, start_page, end_page, first_half)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in indices.iter().rev() {
        insert_pdf(path_str.clone(), path_str.clone(), idx, idx, idx)?;
    }
    Ok(indices.len() as u32)
}

fn parity_half_dup_to_start(path: &Path, start_page: u32, end_page: u32, first_half: bool) -> Result<u32, String> {
    let indices = parity_half_indices(path, start_page, end_page, first_half)?;
    let path_str = path.to_string_lossy().into_owned();
    for (offset, &idx) in indices.iter().rev().enumerate() {
        let offset = offset as u32;
        let source = idx + offset;
        insert_pdf(path_str.clone(), path_str.clone(), offset, source, source)?;
    }
    Ok(indices.len() as u32)
}

fn parity_half_dup_to_end(path: &Path, start_page: u32, end_page: u32, first_half: bool) -> Result<u32, String> {
    let indices = parity_half_indices(path, start_page, end_page, first_half)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in indices.iter().rev() {
        let new_idx = duplicate_page(path_str.clone(), idx)?;
        move_page_to_last(path_str.clone(), new_idx)?;
    }
    Ok(indices.len() as u32)
}

#[allow(clippy::too_many_arguments)]
fn parity_half_expand(path: &Path, start_page: u32, end_page: u32, first_half: bool, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut expanded = 0u32;
    for page_index in start_page..=end_page {
        if !parity_half_match(page_index, start_page, end_page, first_half) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_expand_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        expanded += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(expanded)
}

#[allow(clippy::too_many_arguments)]
fn parity_half_shrink(path: &Path, start_page: u32, end_page: u32, first_half: bool, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut shrunk = 0u32;
    for page_index in start_page..=end_page {
        if !parity_half_match(page_index, start_page, end_page, first_half) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_shrink_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        shrunk += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(shrunk)
}

fn parity_half_clear_crop(path: &Path, start_page: u32, end_page: u32, first_half: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut cleared = 0u32;
    for page_index in start_page..=end_page {
        if !parity_half_match(page_index, start_page, end_page, first_half) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        if doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"CropBox").is_some() {
            cleared += 1;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cleared)
}

fn parity_half_blank(path: &Path, start_page: u32, end_page: u32, first_half: bool, after: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_half_match(*i as u32, start_page, end_page, first_half))
        .collect();
    for &idx in indices.iter().rev() {
        let page_id = create_blank_page(&mut doc, pages_ref);
        let at = if after { idx + 1 } else { idx };
        kids.insert(at, Object::Reference(page_id));
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(indices.len() as u32)
}

fn parity_half_bookmark(path: &Path, start_page: u32, end_page: u32, first_half: bool, prefix: Option<String>) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let prefix = prefix.unwrap_or_else(|| "Page ".to_string());
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut count = 0u32;
    for (page_num, page_id) in doc.get_pages() {
        let page_index = page_num - 1;
        if !parity_half_match(page_index, start_page, end_page, first_half) {
            continue;
        }
        let title = format!("{prefix}{page_num}");
        append_outline_item(&mut doc, &title, page_id)?;
        count += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(count)
}

fn parity_half_page_size(path: &Path, start_page: u32, end_page: u32, first_half: bool, preset: &str) -> Result<u32, String> {
    let (w, h) = page_size_preset_dims(preset)?;
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut resized = 0u32;
    for page_index in start_page..=end_page {
        if !parity_half_match(page_index, start_page, end_page, first_half) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let page = doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?;
        page.set(
            "MediaBox",
            Object::Array(vec![Object::Integer(0), Object::Integer(0), Object::Real(w as f32), Object::Real(h as f32)]),
        );
        page.remove(b"CropBox");
        resized += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(resized)
}

fn parity_half_header(path: &Path, start_page: u32, end_page: u32, first_half: bool, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Header text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_half_match(page_index, start_page, end_page, first_half) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 40.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_half_footer(path: &Path, start_page: u32, end_page: u32, first_half: bool, text: &str) -> Result<u32, String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return Err("Footer text cannot be empty".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut stamped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_half_match(page_index, start_page, end_page, first_half) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let font_name = ensure_helvetica_font(&mut doc, page_id)?;
        let (px, py) = viewer_point_to_pdf(&doc, page_id, 380.0, 1100.0)?;
        let ops = build_page_number_ops(&font_name, trimmed, px, py, 12.0);
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        stamped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(stamped)
}

fn parity_half_border(path: &Path, start_page: u32, end_page: u32, first_half: bool, inset: f64) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut drawn = 0u32;
    for page_index in start_page..=end_page {
        if !parity_half_match(page_index, start_page, end_page, first_half) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let ops = build_page_border_ops(&doc, page_id, inset)?;
        append_page_content(&mut doc, page_id, ops.as_bytes())?;
        drawn += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(drawn)
}

fn parity_half_sort_rotation(path: &Path, start_page: u32, end_page: u32, first_half: bool, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_half_match(*i as u32, start_page, end_page, first_half))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, i64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let rot = kid.as_reference().ok().map(|id| page_rotation(&doc, id).rem_euclid(360)).unwrap_or(0);
            (*i, rot, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.cmp(&b.1);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_half_sort_size(path: &Path, start_page: u32, end_page: u32, first_half: bool, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_half_match(*i as u32, start_page, end_page, first_half))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, f64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let area = kid
                .as_reference()
                .ok()
                .and_then(|id| page_media_box(&doc, id).ok())
                .map(|m| (m[2] - m[0]) * (m[3] - m[1]))
                .unwrap_or(0.0);
            (*i, area, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}


fn parity_mod4_match(page_index: u32, start_page: u32, end_page: u32, remainder: u32) -> bool {
    if page_index < start_page || page_index > end_page {
        return false;
    }
    (page_index - start_page) % 4 == remainder
}


fn parity_mod4_indices(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<Vec<u32>, String> {
    validate_page_range(path, start_page, end_page)?;
    Ok((start_page..=end_page)
        .filter(|i| parity_mod4_match(*i, start_page, end_page, remainder))
        .collect())
}

fn parity_mod4_rotate(path: &Path, start_page: u32, end_page: u32, remainder: u32, delta: i64) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut rotated = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let current = page_rotation(&doc, page_id);
        set_page_rotation(&mut doc, page_id, current + delta)?;
        rotated += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(rotated)
}

fn parity_mod4_reset_rotation(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut reset = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        set_page_rotation(&mut doc, page_id, 0)?;
        reset += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(reset)
}

fn parity_mod4_delete(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let mut to_delete: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod4_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if to_delete.is_empty() {
        return Ok(0);
    }
    if kids.len() - to_delete.len() < 1 {
        return Err("Cannot delete every page in the document".to_string());
    }
    to_delete.sort_by(|a, b| b.cmp(a));
    let deleted = to_delete.len() as u32;
    for idx in to_delete {
        kids.remove(idx);
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_mod4_keep(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (kids, _) = get_pages_kids(&doc)?;
    let kept: Vec<Object> = kids
        .iter()
        .enumerate()
        .filter(|(i, _)| {
            let idx = *i as u32;
            if idx < start_page || idx > end_page {
                return true;
            }
            parity_mod4_match(idx, start_page, end_page, remainder)
        })
        .map(|(_, kid)| kid.clone())
        .collect();
    if kept.is_empty() {
        return Err("No pages would remain after keep filter".to_string());
    }
    if kept.len() == kids.len() {
        return Err("Nothing to delete - all pages in range match the keep filter".to_string());
    }
    let deleted = (kids.len() - kept.len()) as u32;
    set_pages_kids(&mut doc, pages_ref, kept)?;
    doc.prune_objects();
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(deleted)
}

fn parity_mod4_dup_append(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    let indices = parity_mod4_indices(path, start_page, end_page, remainder)?;
    let path_str = path.to_string_lossy().into_owned();
    for &idx in &indices {
        duplicate_page(path_str.clone(), idx)?;
    }
    Ok(indices.len() as u32)
}

fn parity_mod4_flatten(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut removed = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        let count = doc
            .get_dictionary(page_id)
            .ok()
            .and_then(|d| d.get(b"Annots").ok())
            .and_then(|o| o.as_array().ok())
            .map(|a| a.len() as u32)
            .unwrap_or(0);
        if count > 0 {
            doc.get_dictionary_mut(page_id).map_err(|e| e.to_string())?.remove(b"Annots");
            removed += count;
        }
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(removed)
}

fn parity_mod4_reverse(path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod4_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut parity_kids: Vec<Object> = parity_indices.iter().map(|i| kids[*i].clone()).collect();
    parity_kids.reverse();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = parity_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

#[allow(clippy::too_many_arguments)]
fn parity_mod4_crop(path: &Path, start_page: u32, end_page: u32, remainder: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    if margin_top < 0.0 || margin_right < 0.0 || margin_bottom < 0.0 || margin_left < 0.0 {
        return Err("Margins must be non-negative".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let mut cropped = 0u32;
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let page_id = *doc.get_pages().get(&(page_index + 1)).ok_or("Page not found".to_string())?;
        apply_crop_margins(&mut doc, page_id, margin_top, margin_right, margin_bottom, margin_left)?;
        cropped += 1;
    }
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(cropped)
}

fn parity_mod4_extract(path: &Path, output_path: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<String, String> {
    if path == output_path {
        return Err("Output path must differ from the source PDF".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    let doc = Document::load(path).map_err(|e| e.to_string())?;
    let (all_kids, pages_ref) = get_pages_kids(&doc)?;
    let subset: Vec<Object> = all_kids
        .iter()
        .enumerate()
        .filter(|(i, _)| parity_mod4_match(*i as u32, start_page, end_page, remainder))
        .map(|(_, kid)| kid.clone())
        .collect();
    if subset.is_empty() {
        return Err("No pages match the extract filter in range".to_string());
    }
    let mut out = Document::with_version(doc.version.clone());
    set_pages_kids(&mut out, pages_ref, subset)?;
    out.save(output_path).map_err(|e| e.to_string())?;
    Ok(output_path.to_string_lossy().into_owned())
}

fn parity_mod4_export_pdf(path: &Path, output_dir: &Path, start_page: u32, end_page: u32, remainder: u32) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let path_str = path.to_string_lossy().into_owned();
    let mut written = Vec::new();
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let file_name = format!("page-{:03}.pdf", page_index + 1);
        let output_path = output_dir.join(file_name);
        let out = extract_pdf_pages(path_str.clone(), output_path.to_string_lossy().into_owned(), page_index, page_index)?;
        written.push(out);
    }
    Ok(written)
}

#[allow(clippy::too_many_arguments)]
fn parity_mod4_export_rendered(path: &Path, output_dir: &Path, start_page: u32, end_page: u32, remainder: u32, ext: &str, render: ParityPageRenderFn) -> Result<Vec<String>, String> {
    if !path.is_file() {
        return Err("File not found".to_string());
    }
    validate_page_range(path, start_page, end_page)?;
    fs::create_dir_all(output_dir).map_err(|e| e.to_string())?;
    let mut written = Vec::new();
    for page_index in start_page..=end_page {
        if !parity_mod4_match(page_index, start_page, end_page, remainder) {
            continue;
        }
        let bytes = render(path, page_index, EXPORT_PNG_W, EXPORT_PNG_H)?;
        let file_name = format!("page-{:03}.{ext}", page_index + 1);
        let output_path = output_dir.join(file_name);
        write_png_output(&output_path, &bytes)?;
        written.push(output_path.to_string_lossy().into_owned());
    }
    Ok(written)
}

/// First half of page range - dup_before
#[tauri::command]
fn duplicate_first_half_pages_in_range_before(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_dup_before(&PathBuf::from(&path), start_page, end_page, true)
}


/// Second half of page range - dup_before
#[tauri::command]
fn duplicate_second_half_pages_in_range_before(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_dup_before(&PathBuf::from(&path), start_page, end_page, false)
}


/// First half of page range - dup_to_start
#[tauri::command]
fn duplicate_first_half_pages_in_range_to_start(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_dup_to_start(&PathBuf::from(&path), start_page, end_page, true)
}


/// Second half of page range - dup_to_start
#[tauri::command]
fn duplicate_second_half_pages_in_range_to_start(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_dup_to_start(&PathBuf::from(&path), start_page, end_page, false)
}


/// First half of page range - dup_to_end
#[tauri::command]
fn duplicate_first_half_pages_in_range_to_end(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_dup_to_end(&PathBuf::from(&path), start_page, end_page, true)
}


/// Second half of page range - dup_to_end
#[tauri::command]
fn duplicate_second_half_pages_in_range_to_end(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_dup_to_end(&PathBuf::from(&path), start_page, end_page, false)
}


/// First half of page range - expand
#[tauri::command]
fn expand_first_half_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_half_expand(&PathBuf::from(&path), start_page, end_page, true, margin_top, margin_right, margin_bottom, margin_left)
}


/// Second half of page range - expand
#[tauri::command]
fn expand_second_half_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_half_expand(&PathBuf::from(&path), start_page, end_page, false, margin_top, margin_right, margin_bottom, margin_left)
}


/// First half of page range - shrink
#[tauri::command]
fn shrink_first_half_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_half_shrink(&PathBuf::from(&path), start_page, end_page, true, margin_top, margin_right, margin_bottom, margin_left)
}


/// Second half of page range - shrink
#[tauri::command]
fn shrink_second_half_pages_in_range(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_half_shrink(&PathBuf::from(&path), start_page, end_page, false, margin_top, margin_right, margin_bottom, margin_left)
}


/// First half of page range - clear_crop
#[tauri::command]
fn clear_crop_first_half_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_clear_crop(&PathBuf::from(&path), start_page, end_page, true)
}


/// Second half of page range - clear_crop
#[tauri::command]
fn clear_crop_second_half_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_clear_crop(&PathBuf::from(&path), start_page, end_page, false)
}


/// First half of page range - blank_before
#[tauri::command]
fn insert_blank_before_first_half_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_blank(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Second half of page range - blank_before
#[tauri::command]
fn insert_blank_before_second_half_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_blank(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// First half of page range - blank_after
#[tauri::command]
fn insert_blank_after_first_half_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_blank(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Second half of page range - blank_after
#[tauri::command]
fn insert_blank_after_second_half_pages_in_range(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_blank(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// First half of page range - bookmark
#[tauri::command]
fn bookmark_first_half_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_half_bookmark(&PathBuf::from(&path), start_page, end_page, true, prefix)
}


/// Second half of page range - bookmark
#[tauri::command]
fn bookmark_second_half_pages_in_range(path: String, start_page: u32, end_page: u32, prefix: Option<String>) -> Result<u32, String> {
    parity_half_bookmark(&PathBuf::from(&path), start_page, end_page, false, prefix)
}


/// First half of page range - page_size
#[tauri::command]
fn set_page_size_first_half_pages_in_range(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_half_page_size(&PathBuf::from(&path), start_page, end_page, true, &preset)
}


/// Second half of page range - page_size
#[tauri::command]
fn set_page_size_second_half_pages_in_range(path: String, start_page: u32, end_page: u32, preset: String) -> Result<u32, String> {
    parity_half_page_size(&PathBuf::from(&path), start_page, end_page, false, &preset)
}


/// First half of page range - header
#[tauri::command]
fn add_page_header_first_half_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_half_header(&PathBuf::from(&path), start_page, end_page, true, &text)
}


/// Second half of page range - header
#[tauri::command]
fn add_page_header_second_half_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_half_header(&PathBuf::from(&path), start_page, end_page, false, &text)
}


/// First half of page range - footer
#[tauri::command]
fn add_page_footer_first_half_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_half_footer(&PathBuf::from(&path), start_page, end_page, true, &text)
}


/// Second half of page range - footer
#[tauri::command]
fn add_page_footer_second_half_pages_in_range(path: String, start_page: u32, end_page: u32, text: String) -> Result<u32, String> {
    parity_half_footer(&PathBuf::from(&path), start_page, end_page, false, &text)
}


/// First half of page range - border
#[tauri::command]
fn add_page_border_first_half_pages_in_range(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_half_border(&PathBuf::from(&path), start_page, end_page, true, inset)
}


/// Second half of page range - border
#[tauri::command]
fn add_page_border_second_half_pages_in_range(path: String, start_page: u32, end_page: u32, inset: f64) -> Result<u32, String> {
    parity_half_border(&PathBuf::from(&path), start_page, end_page, false, inset)
}


/// First half of page range - export_webp
#[tauri::command]
fn export_first_half_pages_in_range_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, "webp", render_page_webp)
}


/// Second half of page range - export_webp
#[tauri::command]
fn export_second_half_pages_in_range_webp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, "webp", render_page_webp)
}


/// First half of page range - export_bmp
#[tauri::command]
fn export_first_half_pages_in_range_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, "bmp", render_page_bmp)
}


/// Second half of page range - export_bmp
#[tauri::command]
fn export_second_half_pages_in_range_bmp(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, "bmp", render_page_bmp)
}


/// First half of page range - export_tiff
#[tauri::command]
fn export_first_half_pages_in_range_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, "tiff", render_page_tiff)
}


/// Second half of page range - export_tiff
#[tauri::command]
fn export_second_half_pages_in_range_tiff(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, "tiff", render_page_tiff)
}


/// First half of page range - export_gif
#[tauri::command]
fn export_first_half_pages_in_range_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, "gif", render_page_gif)
}


/// Second half of page range - export_gif
#[tauri::command]
fn export_second_half_pages_in_range_gif(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, "gif", render_page_gif)
}


/// First half of page range - export_ppm
#[tauri::command]
fn export_first_half_pages_in_range_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, "ppm", render_page_ppm)
}


/// Second half of page range - export_ppm
#[tauri::command]
fn export_second_half_pages_in_range_ppm(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, "ppm", render_page_ppm)
}


/// First half of page range - export_tga
#[tauri::command]
fn export_first_half_pages_in_range_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, "tga", render_page_tga)
}


/// Second half of page range - export_tga
#[tauri::command]
fn export_second_half_pages_in_range_tga(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, "tga", render_page_tga)
}


/// First half of page range - export_ico
#[tauri::command]
fn export_first_half_pages_in_range_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, true, "ico", render_page_ico)
}


/// Second half of page range - export_ico
#[tauri::command]
fn export_second_half_pages_in_range_ico(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_half_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, false, "ico", render_page_ico)
}


/// First half of page range - sort_rot
#[tauri::command]
fn sort_first_half_pages_in_range_by_rotation(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_sort_rotation(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Second half of page range - sort_rot
#[tauri::command]
fn sort_second_half_pages_in_range_by_rotation(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_sort_rotation(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// First half of page range - sort_size
#[tauri::command]
fn sort_first_half_pages_in_range_by_size(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_sort_size(&PathBuf::from(&path), start_page, end_page, true, false)
}


/// Second half of page range - sort_size
#[tauri::command]
fn sort_second_half_pages_in_range_by_size(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_sort_size(&PathBuf::from(&path), start_page, end_page, false, false)
}


/// Mod-4 remainder 0 in range - rotate_cw
#[tauri::command]
fn rotate_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 0, 90)
}


/// Mod-4 remainder 1 in range - rotate_cw
#[tauri::command]
fn rotate_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 1, 90)
}


/// Mod-4 remainder 2 in range - rotate_cw
#[tauri::command]
fn rotate_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 2, 90)
}


/// Mod-4 remainder 3 in range - rotate_cw
#[tauri::command]
fn rotate_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 3, 90)
}


/// Mod-4 remainder 0 in range - rotate_ccw
#[tauri::command]
fn rotate_mod4_0_pages_in_range_mod4_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 0, -90)
}


/// Mod-4 remainder 1 in range - rotate_ccw
#[tauri::command]
fn rotate_mod4_1_pages_in_range_mod4_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 1, -90)
}


/// Mod-4 remainder 2 in range - rotate_ccw
#[tauri::command]
fn rotate_mod4_2_pages_in_range_mod4_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 2, -90)
}


/// Mod-4 remainder 3 in range - rotate_ccw
#[tauri::command]
fn rotate_mod4_3_pages_in_range_mod4_ccw(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 3, -90)
}


/// Mod-4 remainder 0 in range - rotate_180
#[tauri::command]
fn rotate_180_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 0, 180)
}


/// Mod-4 remainder 1 in range - rotate_180
#[tauri::command]
fn rotate_180_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 1, 180)
}


/// Mod-4 remainder 2 in range - rotate_180
#[tauri::command]
fn rotate_180_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 2, 180)
}


/// Mod-4 remainder 3 in range - rotate_180
#[tauri::command]
fn rotate_180_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_rotate(&PathBuf::from(&path), start_page, end_page, 3, 180)
}


/// Mod-4 remainder 0 in range - reset_rot
#[tauri::command]
fn reset_rotation_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_reset_rotation(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - reset_rot
#[tauri::command]
fn reset_rotation_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_reset_rotation(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - reset_rot
#[tauri::command]
fn reset_rotation_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_reset_rotation(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - reset_rot
#[tauri::command]
fn reset_rotation_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_reset_rotation(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - delete
#[tauri::command]
fn delete_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_delete(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - delete
#[tauri::command]
fn delete_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_delete(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - delete
#[tauri::command]
fn delete_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_delete(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - delete
#[tauri::command]
fn delete_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_delete(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - keep
#[tauri::command]
fn keep_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_keep(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - keep
#[tauri::command]
fn keep_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_keep(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - keep
#[tauri::command]
fn keep_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_keep(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - keep
#[tauri::command]
fn keep_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_keep(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - dup_append
#[tauri::command]
fn duplicate_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_append(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - dup_append
#[tauri::command]
fn duplicate_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_append(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - dup_append
#[tauri::command]
fn duplicate_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_append(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - dup_append
#[tauri::command]
fn duplicate_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_dup_append(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - flatten
#[tauri::command]
fn flatten_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_flatten(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - flatten
#[tauri::command]
fn flatten_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_flatten(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - flatten
#[tauri::command]
fn flatten_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_flatten(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - flatten
#[tauri::command]
fn flatten_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_flatten(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - reverse
#[tauri::command]
fn reverse_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_reverse(&PathBuf::from(&path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - reverse
#[tauri::command]
fn reverse_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_reverse(&PathBuf::from(&path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - reverse
#[tauri::command]
fn reverse_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_reverse(&PathBuf::from(&path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - reverse
#[tauri::command]
fn reverse_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_reverse(&PathBuf::from(&path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - crop
#[tauri::command]
fn crop_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_crop(&PathBuf::from(&path), start_page, end_page, 0, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 1 in range - crop
#[tauri::command]
fn crop_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_crop(&PathBuf::from(&path), start_page, end_page, 1, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 2 in range - crop
#[tauri::command]
fn crop_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_crop(&PathBuf::from(&path), start_page, end_page, 2, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 3 in range - crop
#[tauri::command]
fn crop_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, margin_top: f64, margin_right: f64, margin_bottom: f64, margin_left: f64) -> Result<u32, String> {
    parity_mod4_crop(&PathBuf::from(&path), start_page, end_page, 3, margin_top, margin_right, margin_bottom, margin_left)
}


/// Mod-4 remainder 0 in range - extract
#[tauri::command]
fn extract_mod4_0_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_mod4_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - extract
#[tauri::command]
fn extract_mod4_1_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_mod4_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - extract
#[tauri::command]
fn extract_mod4_2_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_mod4_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - extract
#[tauri::command]
fn extract_mod4_3_pages_in_range_mod4(path: String, start_page: u32, end_page: u32, output_path: String) -> Result<String, String> {
    parity_mod4_extract(&PathBuf::from(&path), &PathBuf::from(&output_path), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - export_pdf
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0)
}


/// Mod-4 remainder 1 in range - export_pdf
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1)
}


/// Mod-4 remainder 2 in range - export_pdf
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2)
}


/// Mod-4 remainder 3 in range - export_pdf
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_as_pdf(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_pdf(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3)
}


/// Mod-4 remainder 0 in range - export_png
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "png", render_page_png)
}


/// Mod-4 remainder 1 in range - export_png
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "png", render_page_png)
}


/// Mod-4 remainder 2 in range - export_png
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "png", render_page_png)
}


/// Mod-4 remainder 3 in range - export_png
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_png(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3, "png", render_page_png)
}


/// Mod-4 remainder 0 in range - export_jpeg
#[tauri::command]
fn export_mod4_0_pages_in_range_mod4_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 0, "jpeg", render_page_jpeg)
}


/// Mod-4 remainder 1 in range - export_jpeg
#[tauri::command]
fn export_mod4_1_pages_in_range_mod4_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 1, "jpeg", render_page_jpeg)
}


/// Mod-4 remainder 2 in range - export_jpeg
#[tauri::command]
fn export_mod4_2_pages_in_range_mod4_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 2, "jpeg", render_page_jpeg)
}


/// Mod-4 remainder 3 in range - export_jpeg
#[tauri::command]
fn export_mod4_3_pages_in_range_mod4_jpeg(path: String, start_page: u32, end_page: u32, output_dir: String) -> Result<Vec<String>, String> {
    parity_mod4_export_rendered(&PathBuf::from(&path), &PathBuf::from(&output_dir), start_page, end_page, 3, "jpeg", render_page_jpeg)
}
