// Auto-generated by scripts/gen-parity-batch8.py - do not edit.
// --- mod-3 sort helpers ---
fn parity_mod3_sort_rotation(path: &Path, start_page: u32, end_page: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod3_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, i64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let rot = kid.as_reference().ok().map(|id| page_rotation(&doc, id).rem_euclid(360)).unwrap_or(0);
            (*i, rot, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.cmp(&b.1);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_mod3_sort_size(path: &Path, start_page: u32, end_page: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod3_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, f64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let area = kid
                .as_reference()
                .ok()
                .and_then(|id| page_media_box(&doc, id).ok())
                .map(|m| (m[2] - m[0]) * (m[3] - m[1]))
                .unwrap_or(0.0);
            (*i, area, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}


// --- mod-4 sort helpers ---
fn parity_mod4_sort_rotation(path: &Path, start_page: u32, end_page: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod4_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, i64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let rot = kid.as_reference().ok().map(|id| page_rotation(&doc, id).rem_euclid(360)).unwrap_or(0);
            (*i, rot, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.cmp(&b.1);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_mod4_sort_size(path: &Path, start_page: u32, end_page: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod4_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, f64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let area = kid
                .as_reference()
                .ok()
                .and_then(|id| page_media_box(&doc, id).ok())
                .map(|m| (m[2] - m[0]) * (m[3] - m[1]))
                .unwrap_or(0.0);
            (*i, area, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}


// --- mod-5 sort helpers ---
fn parity_mod5_sort_rotation(path: &Path, start_page: u32, end_page: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod5_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, i64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let rot = kid.as_reference().ok().map(|id| page_rotation(&doc, id).rem_euclid(360)).unwrap_or(0);
            (*i, rot, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.cmp(&b.1);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_mod5_sort_size(path: &Path, start_page: u32, end_page: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod5_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, f64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let area = kid
                .as_reference()
                .ok()
                .and_then(|id| page_media_box(&doc, id).ok())
                .map(|m| (m[2] - m[0]) * (m[3] - m[1]))
                .unwrap_or(0.0);
            (*i, area, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}


// --- mod-6 sort helpers ---
fn parity_mod6_sort_rotation(path: &Path, start_page: u32, end_page: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod6_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, i64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let rot = kid.as_reference().ok().map(|id| page_rotation(&doc, id).rem_euclid(360)).unwrap_or(0);
            (*i, rot, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.cmp(&b.1);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}

fn parity_mod6_sort_size(path: &Path, start_page: u32, end_page: u32, remainder: u32, descending: bool) -> Result<u32, String> {
    validate_page_range(path, start_page, end_page)?;
    let mut doc = Document::load(path).map_err(|e| e.to_string())?;
    let pages_ref = flatten_pages(&mut doc)?;
    let (mut kids, _) = get_pages_kids(&doc)?;
    let parity_indices: Vec<usize> = (start_page as usize..=end_page as usize)
        .filter(|i| parity_mod6_match(*i as u32, start_page, end_page, remainder))
        .collect();
    if parity_indices.len() < 2 {
        return Ok(parity_indices.len() as u32);
    }
    let mut indexed: Vec<(usize, f64, Object)> = parity_indices
        .iter()
        .map(|i| {
            let kid = kids[*i].clone();
            let area = kid
                .as_reference()
                .ok()
                .and_then(|id| page_media_box(&doc, id).ok())
                .map(|m| (m[2] - m[0]) * (m[3] - m[1]))
                .unwrap_or(0.0);
            (*i, area, kid)
        })
        .collect();
    indexed.sort_by(|a, b| {
        let ord = a.1.partial_cmp(&b.1).unwrap_or(std::cmp::Ordering::Equal);
        if descending { ord.reverse() } else { ord }
    });
    let sorted_kids: Vec<Object> = indexed.into_iter().map(|(_, _, kid)| kid).collect();
    for (pos, idx) in parity_indices.iter().enumerate() {
        kids[*idx] = sorted_kids[pos].clone();
    }
    set_pages_kids(&mut doc, pages_ref, kids)?;
    doc.save(path).map_err(|e| e.to_string())?;
    Ok(parity_indices.len() as u32)
}



/// Sort global odd by rotation descending in range
#[tauri::command]
fn sort_odd_pages_in_range_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_rotation(&PathBuf::from(&path), start_page, end_page, true, false, true)
}


/// Sort global even by rotation descending in range
#[tauri::command]
fn sort_even_pages_in_range_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_rotation(&PathBuf::from(&path), start_page, end_page, false, false, true)
}


/// Sort local odd by rotation descending in range
#[tauri::command]
fn sort_range_local_odd_pages_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_rotation(&PathBuf::from(&path), start_page, end_page, true, true, true)
}


/// Sort local even by rotation descending in range
#[tauri::command]
fn sort_range_local_even_pages_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_rotation(&PathBuf::from(&path), start_page, end_page, false, true, true)
}


/// Sort first half by rotation descending in range
#[tauri::command]
fn sort_first_half_pages_in_range_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_sort_rotation(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Sort second half by rotation descending in range
#[tauri::command]
fn sort_second_half_pages_in_range_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_sort_rotation(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Sort global odd by page size descending in range
#[tauri::command]
fn sort_odd_pages_in_range_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_size(&PathBuf::from(&path), start_page, end_page, true, false, true)
}


/// Sort global even by page size descending in range
#[tauri::command]
fn sort_even_pages_in_range_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_size(&PathBuf::from(&path), start_page, end_page, false, false, true)
}


/// Sort local odd by page size descending in range
#[tauri::command]
fn sort_range_local_odd_pages_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_size(&PathBuf::from(&path), start_page, end_page, true, true, true)
}


/// Sort local even by page size descending in range
#[tauri::command]
fn sort_range_local_even_pages_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_batch_sort_size(&PathBuf::from(&path), start_page, end_page, false, true, true)
}


/// Sort first half by page size descending in range
#[tauri::command]
fn sort_first_half_pages_in_range_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_sort_size(&PathBuf::from(&path), start_page, end_page, true, true)
}


/// Sort second half by page size descending in range
#[tauri::command]
fn sort_second_half_pages_in_range_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_half_sort_size(&PathBuf::from(&path), start_page, end_page, false, true)
}


/// Sort mod-3 remainder 0 by rotation descending in range
#[tauri::command]
fn sort_mod3_0_pages_in_range_mod3_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_sort_rotation(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Sort mod-3 remainder 0 by page size descending in range
#[tauri::command]
fn sort_mod3_0_pages_in_range_mod3_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_sort_size(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Sort mod-3 remainder 1 by rotation descending in range
#[tauri::command]
fn sort_mod3_1_pages_in_range_mod3_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_sort_rotation(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Sort mod-3 remainder 1 by page size descending in range
#[tauri::command]
fn sort_mod3_1_pages_in_range_mod3_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_sort_size(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Sort mod-3 remainder 2 by rotation descending in range
#[tauri::command]
fn sort_mod3_2_pages_in_range_mod3_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_sort_rotation(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// Sort mod-3 remainder 2 by page size descending in range
#[tauri::command]
fn sort_mod3_2_pages_in_range_mod3_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod3_sort_size(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// Sort mod-4 remainder 0 by rotation descending in range
#[tauri::command]
fn sort_mod4_0_pages_in_range_mod4_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_sort_rotation(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Sort mod-4 remainder 0 by page size descending in range
#[tauri::command]
fn sort_mod4_0_pages_in_range_mod4_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_sort_size(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Sort mod-4 remainder 1 by rotation descending in range
#[tauri::command]
fn sort_mod4_1_pages_in_range_mod4_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_sort_rotation(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Sort mod-4 remainder 1 by page size descending in range
#[tauri::command]
fn sort_mod4_1_pages_in_range_mod4_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_sort_size(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Sort mod-4 remainder 2 by rotation descending in range
#[tauri::command]
fn sort_mod4_2_pages_in_range_mod4_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_sort_rotation(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// Sort mod-4 remainder 2 by page size descending in range
#[tauri::command]
fn sort_mod4_2_pages_in_range_mod4_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_sort_size(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// Sort mod-4 remainder 3 by rotation descending in range
#[tauri::command]
fn sort_mod4_3_pages_in_range_mod4_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_sort_rotation(&PathBuf::from(&path), start_page, end_page, 3, true)
}


/// Sort mod-4 remainder 3 by page size descending in range
#[tauri::command]
fn sort_mod4_3_pages_in_range_mod4_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod4_sort_size(&PathBuf::from(&path), start_page, end_page, 3, true)
}


/// Sort mod-5 remainder 0 by rotation descending in range
#[tauri::command]
fn sort_mod5_0_pages_in_range_mod5_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_rotation(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Sort mod-5 remainder 0 by page size descending in range
#[tauri::command]
fn sort_mod5_0_pages_in_range_mod5_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_size(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Sort mod-5 remainder 1 by rotation descending in range
#[tauri::command]
fn sort_mod5_1_pages_in_range_mod5_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_rotation(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Sort mod-5 remainder 1 by page size descending in range
#[tauri::command]
fn sort_mod5_1_pages_in_range_mod5_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_size(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Sort mod-5 remainder 2 by rotation descending in range
#[tauri::command]
fn sort_mod5_2_pages_in_range_mod5_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_rotation(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// Sort mod-5 remainder 2 by page size descending in range
#[tauri::command]
fn sort_mod5_2_pages_in_range_mod5_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_size(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// Sort mod-5 remainder 3 by rotation descending in range
#[tauri::command]
fn sort_mod5_3_pages_in_range_mod5_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_rotation(&PathBuf::from(&path), start_page, end_page, 3, true)
}


/// Sort mod-5 remainder 3 by page size descending in range
#[tauri::command]
fn sort_mod5_3_pages_in_range_mod5_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_size(&PathBuf::from(&path), start_page, end_page, 3, true)
}


/// Sort mod-5 remainder 4 by rotation descending in range
#[tauri::command]
fn sort_mod5_4_pages_in_range_mod5_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_rotation(&PathBuf::from(&path), start_page, end_page, 4, true)
}


/// Sort mod-5 remainder 4 by page size descending in range
#[tauri::command]
fn sort_mod5_4_pages_in_range_mod5_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod5_sort_size(&PathBuf::from(&path), start_page, end_page, 4, true)
}


/// Sort mod-6 remainder 0 by rotation descending in range
#[tauri::command]
fn sort_mod6_0_pages_in_range_mod6_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_rotation(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Sort mod-6 remainder 0 by page size descending in range
#[tauri::command]
fn sort_mod6_0_pages_in_range_mod6_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_size(&PathBuf::from(&path), start_page, end_page, 0, true)
}


/// Sort mod-6 remainder 1 by rotation descending in range
#[tauri::command]
fn sort_mod6_1_pages_in_range_mod6_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_rotation(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Sort mod-6 remainder 1 by page size descending in range
#[tauri::command]
fn sort_mod6_1_pages_in_range_mod6_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_size(&PathBuf::from(&path), start_page, end_page, 1, true)
}


/// Sort mod-6 remainder 2 by rotation descending in range
#[tauri::command]
fn sort_mod6_2_pages_in_range_mod6_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_rotation(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// Sort mod-6 remainder 2 by page size descending in range
#[tauri::command]
fn sort_mod6_2_pages_in_range_mod6_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_size(&PathBuf::from(&path), start_page, end_page, 2, true)
}


/// Sort mod-6 remainder 3 by rotation descending in range
#[tauri::command]
fn sort_mod6_3_pages_in_range_mod6_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_rotation(&PathBuf::from(&path), start_page, end_page, 3, true)
}


/// Sort mod-6 remainder 3 by page size descending in range
#[tauri::command]
fn sort_mod6_3_pages_in_range_mod6_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_size(&PathBuf::from(&path), start_page, end_page, 3, true)
}


/// Sort mod-6 remainder 4 by rotation descending in range
#[tauri::command]
fn sort_mod6_4_pages_in_range_mod6_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_rotation(&PathBuf::from(&path), start_page, end_page, 4, true)
}


/// Sort mod-6 remainder 4 by page size descending in range
#[tauri::command]
fn sort_mod6_4_pages_in_range_mod6_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_size(&PathBuf::from(&path), start_page, end_page, 4, true)
}


/// Sort mod-6 remainder 5 by rotation descending in range
#[tauri::command]
fn sort_mod6_5_pages_in_range_mod6_by_rotation_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_rotation(&PathBuf::from(&path), start_page, end_page, 5, true)
}


/// Sort mod-6 remainder 5 by page size descending in range
#[tauri::command]
fn sort_mod6_5_pages_in_range_mod6_by_size_desc(path: String, start_page: u32, end_page: u32) -> Result<u32, String> {
    parity_mod6_sort_size(&PathBuf::from(&path), start_page, end_page, 5, true)
}
