import { useState, useRef } from 'react';
import { AppShell } from './chrome/AppShell';
import { buildAppMenusFromSource } from './menu/buildAppMenusFromSource';
import { useAppBootstrap } from './app/useAppBootstrap';
import { usePdfSearch } from './pdf/usePdfSearch';
import { usePdfBrowser } from './pdf/usePdfBrowser';
import { usePrintJobs } from './pdf/usePrintJobs';
import { useUndoHistory } from './pdf/useUndoHistory';
import { usePdfDocument } from './pdf/usePdfDocument';
import { buildAppModalsSource } from './modals/buildAppModalsSource';
import { buildAppShellSource } from './chrome/buildAppShellSource';
import { useAppModalState } from './app/useAppModalState';
import { useDocumentPanelsState } from './app/useDocumentPanelsState';
import { useSecurityFormState } from './app/useSecurityFormState';
import { useAnnotationDraftState } from './app/useAnnotationDraftState';
import { useHelpChromeState } from './app/useHelpChromeState';
import { useUnsavedGuard } from './app/useUnsavedGuard';
import { useModalDismiss } from './app/useModalDismiss';
import { buildModalDismissSource } from './app/buildModalDismissSource';
import { useAppKeyboardBinding } from './app/useAppKeyboardBinding';
import { useAppRefs } from './app/useAppRefs';
import { useRememberBrowserDirectory } from './app/useRememberBrowserDirectory';
import { usePanelLoaders } from './app/usePanelLoaders';
import { useClosePdf } from './app/usePdfLifecycle';
import { usePdfRecents } from './app/usePdfRecents';
import { usePdfOpen } from './app/usePdfOpen';
import { useThumbnailReorder } from './app/useThumbnailReorder';
import { useAppPdfActions } from './app/useAppPdfActions';
import { usePageZoom } from './viewer/usePageZoom';
import { useDrawingGesture } from './viewer/useDrawingGesture';
import { useSourcePdfPageCounts } from './app/useSourcePdfPageCounts';
import { usePageEditsLoader } from './app/usePageEditsLoader';
import { useWindowTitle } from './app/useWindowTitle';
import { useTesseractReminder } from './app/useTesseractReminder';
import { useWindowCloseGuard } from './app/useWindowCloseGuard';
import { usePageZoomInputSync } from './app/usePageZoomInputSync';
import { useAppLoading } from './app/useAppLoading';
import { useAppPageRanges } from './app/useAppPageRanges';
import { buildModeToolbarExtras } from './viewer/buildModeToolbarExtras';
import { useWheelNavigation } from './viewer/useWheelNavigation';
import { type MarkdownOcrNotice, type ViewMode } from './app/types';
import { fileNameFromPath } from './app/utils';

function App() {
  const [filePath, setFilePath] = useState<string>(''); // working-copy path; all backend ops target this
  const [originalPath, setOriginalPath] = useState<string>(''); // user's real file (display / recents / Save target)
  const [isDirty, setIsDirty] = useState<boolean>(false);
  const isDirtyRef = useRef(false);
  const modal = useAppModalState();
  const {
    showSaveAsModal, setShowSaveAsModal,
    saveAsPath, setSaveAsPath,
    showMarkdownSaveAsModal, setShowMarkdownSaveAsModal,
    markdownSaveAsPath, setMarkdownSaveAsPath,
    nativeDialogs, setNativeDialogs,
    showSummaryModal, setShowSummaryModal,
    pdfSummary, setPdfSummary,
    showOpenModal, setShowOpenModal,
    openFilePath, setOpenFilePath,
    recentPdfs, setRecentPdfs,
    lastBrowserDir, setLastBrowserDir,
    showDeleteModal, setShowDeleteModal,
    deletePageInput, setDeletePageInput,
    showSplitModal, setShowSplitModal,
    splitRanges, setSplitRanges,
    showExtractModal, setShowExtractModal,
    extractOutputPath, setExtractOutputPath,
    showExportPngModal, setShowExportPngModal,
    pngExportOutputPath, setPngExportOutputPath,
    imageExportFormat, setImageExportFormat,
    showDeleteRangeModal, setShowDeleteRangeModal,
    showPageNumbersModal, setShowPageNumbersModal,
    pageNumbersPrefix, setPageNumbersPrefix,
    showWatermarkModal, setShowWatermarkModal,
    watermarkText, setWatermarkText,
    showCropModal, setShowCropModal,
    cropMarginTop, setCropMarginTop,
    cropMarginRight, setCropMarginRight,
    cropMarginBottom, setCropMarginBottom,
    cropMarginLeft, setCropMarginLeft,
    showFlattenModal, setShowFlattenModal,
    showAddBookmarkModal, setShowAddBookmarkModal,
    bookmarkTitle, setBookmarkTitle,
    showRenameBookmarkModal, setShowRenameBookmarkModal,
    renameBookmarkIndex, setRenameBookmarkIndex,
    renameBookmarkTitle, setRenameBookmarkTitle,
    showDuplicateRangeModal, setShowDuplicateRangeModal,
    cropApplyAll, setCropApplyAll,
    pageSizes, setPageSizes,
    showPageHeaderModal, setShowPageHeaderModal,
    pageHeaderText, setPageHeaderText,
    showInsertImagePageModal, setShowInsertImagePageModal,
    insertImagePagePath, setInsertImagePagePath,
    insertImageAtIndex, setInsertImageAtIndex,
    showExportPagePdfModal, setShowExportPagePdfModal,
    exportPagePdfPath, setExportPagePdfPath,
    showExportPagesPdfModal, setShowExportPagesPdfModal,
    exportPagesPdfOutputDir, setExportPagesPdfOutputDir,
    showPageFooterModal, setShowPageFooterModal,
    pageFooterText, setPageFooterText,
    showSwapPagesModal, setShowSwapPagesModal,
    swapPageA, setSwapPageA,
    swapPageB, setSwapPageB,
    showReplacePageModal, setShowReplacePageModal,
    replaceSourcePath, setReplaceSourcePath,
    replaceSourcePage, setReplaceSourcePage,
    replaceSourcePageCount, setReplaceSourcePageCount,
    showInterleaveModal, setShowInterleaveModal,
    interleaveFilePath, setInterleaveFilePath,
    interleaveSourcePageCount, setInterleaveSourcePageCount,
    showPageSizeModal, setShowPageSizeModal,
    pageSizePreset, setPageSizePreset,
    showRotateRangeModal, setShowRotateRangeModal,
    showKeepRangeModal, setShowKeepRangeModal,
    showMoveRangeModal, setShowMoveRangeModal,
    moveRangeToIndex, setMoveRangeToIndex,
    showPrependModal, setShowPrependModal,
    prependFilePath, setPrependFilePath,
    prependSourcePageCount, setPrependSourcePageCount,
    showSplitEveryModal, setShowSplitEveryModal,
    splitEveryN, setSplitEveryN,
    showPageBorderModal, setShowPageBorderModal,
    pageBorderInset, setPageBorderInset,
    showBookmarkAllModal, setShowBookmarkAllModal,
    bookmarkAllPrefix, setBookmarkAllPrefix,
    showExpandMarginsModal, setShowExpandMarginsModal,
    expandMarginTop, setExpandMarginTop,
    expandMarginRight, setExpandMarginRight,
    expandMarginBottom, setExpandMarginBottom,
    expandMarginLeft, setExpandMarginLeft,
    showShrinkMarginsModal, setShowShrinkMarginsModal,
    shrinkMarginTop, setShrinkMarginTop,
    shrinkMarginRight, setShrinkMarginRight,
    shrinkMarginBottom, setShrinkMarginBottom,
    shrinkMarginLeft, setShrinkMarginLeft,
    showDeleteNthModal, setShowDeleteNthModal,
    deleteNthValue, setDeleteNthValue,
    showExtractOddModal, setShowExtractOddModal,
    extractOddOutputPath, setExtractOddOutputPath,
    showExtractEvenModal, setShowExtractEvenModal,
    extractEvenOutputPath, setExtractEvenOutputPath,
    showSplitAtModal, setShowSplitAtModal,
    splitAtPage, setSplitAtPage,
    showReverseRangeModal, setShowReverseRangeModal,
    showInsertBlankPagesModal, setShowInsertBlankPagesModal,
    insertBlankCount, setInsertBlankCount,
    insertBlankAtIndex, setInsertBlankAtIndex,
    showCropRangeModal, setShowCropRangeModal,
    showParityRangeModal, setShowParityRangeModal,
    parityRangeCommand, setParityRangeCommand,
    parityRangeOutputPath, setParityRangeOutputPath,
    showInsertModal, setShowInsertModal,
    insertFilePath, setInsertFilePath,
    insertAtPage, setInsertAtPage,
    insertSourcePageCount, setInsertSourcePageCount,
    showMergeModal, setShowMergeModal,
    mergeFilePath, setMergeFilePath,
    mergeSourcePageCount, setMergeSourcePageCount,
  } = modal;

  const security = useSecurityFormState();
  const {
    showProtectModal, setShowProtectModal,
    showPasswordModal, setShowPasswordModal,
    pendingEncryptedPath, setPendingEncryptedPath,
    protectUserPassword, setProtectUserPassword,
    protectUserPasswordConfirm, setProtectUserPasswordConfirm,
    protectOwnerPassword, setProtectOwnerPassword,
    showSignModal, setShowSignModal,
    signCertPath, setSignCertPath,
    signCertPassword, setSignCertPassword,
    signReason, setSignReason,
    signLocation, setSignLocation,
    showMetadataModal, setShowMetadataModal,
    metadataTitle, setMetadataTitle,
    metadataAuthor, setMetadataAuthor,
    metadataSubject, setMetadataSubject,
    metadataKeywords, setMetadataKeywords,
    metadataCreator, setMetadataCreator,
    metadataProducer, setMetadataProducer,
    metadataCreationDate, setMetadataCreationDate,
    metadataModDate, setMetadataModDate,
    pdfPasswordDraft, setPdfPasswordDraft,
    showDecryptModal, setShowDecryptModal,
    decryptPassword, setDecryptPassword,
  } = security;

  const panels = useDocumentPanelsState();
  const {
    showSignaturesPanel, setShowSignaturesPanel,
    pdfSignatures, setPdfSignatures,
    signatureVerification, setSignatureVerification,
    showBookmarksPanel, setShowBookmarksPanel,
    pdfBookmarks, setPdfBookmarks,
    showFormsPanel, setShowFormsPanel,
    formFields, setFormFields,
    formDrafts, setFormDrafts,
  } = panels;

  const {
    filePathRef,
    handleMarkdownViewRef,
    loadPdfBookmarksRef,
    loadPageSizesRef,
    cancelDrawingRef,
    keyboardActionsRef,
    imgRef,
    handleSaveRef,
  } = useAppRefs();
  const [pageCount, setPageCount] = useState<number | null>(null);
  const [currentPage, setCurrentPage] = useState<number>(0);
  const [draggedIndex, setDraggedIndex] = useState<number | null>(null);
  const [loading, setLoading] = useState(false);
  const [zoom, setZoom] = useState(1);
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null);
  const [viewMode, setViewMode] = useState<ViewMode>('pdf');
  const [markdownText, setMarkdownText] = useState('');
  const [markdownPath, setMarkdownPath] = useState('');
  const [pdfRevision, setPdfRevision] = useState(0);
  const [markdownRevision, setMarkdownRevision] = useState<number | null>(null);
  const [markdownOcrNotice, setMarkdownOcrNotice] = useState<MarkdownOcrNotice | null>(null);
  const [ocrAvailable, setOcrAvailable] = useState<boolean | null>(null);
  const {
    showCommandPalette, setShowCommandPalette,
    showShortcutsHelp, setShowShortcutsHelp,
    showLicenses, setShowLicenses,
    showCredits, setShowCredits,
    showAbout, setShowAbout,
    showTesseractModal, setShowTesseractModal,
    tesseractInstallGuide, setTesseractInstallGuide,
    tesseractDoNotRemind, setTesseractDoNotRemind,
    tesseractReminderSource, setTesseractReminderSource,
  } = useHelpChromeState();

  // Editable page/zoom field values (kept in sync with the canonical state).
  const [pageInput, setPageInput] = useState('1');
  const [zoomInput, setZoomInput] = useState('100');

  const annotation = useAnnotationDraftState();
  const {
    highlightMode, setHighlightMode,
    noteMode, setNoteMode,
    drawMode, setDrawMode,
    shapeMode, setShapeMode,
    shapeKind, setShapeKind,
    stampMode, setStampMode,
    stampKind, setStampKind,
    stampPreset, setStampPreset,
    redactMode, setRedactMode,
    imageInsertMode, setImageInsertMode,
    textEditMode, setTextEditMode,
    vectorEditMode, setVectorEditMode,
    showPageTextModal, setShowPageTextModal,
    showPageEditsModal, setShowPageEditsModal,
    pendingTextPos, setPendingTextPos,
    pageTextDraft, setPageTextDraft,
    pageTextFontSize, setPageTextFontSize,
    editingTextIndex, setEditingTextIndex,
    pageTextEdits, setPageTextEdits,
    pageVectorEdits, setPageVectorEdits,
    showImageInsertModal, setShowImageInsertModal,
    imageSourcePath, setImageSourcePath,
    imageSourceDraft, setImageSourceDraft,
    formAddMode, setFormAddMode,
    showAddFormFieldModal, setShowAddFormFieldModal,
    newFormFieldKind, setNewFormFieldKind,
    newFormFieldName, setNewFormFieldName,
    newFormFieldOptions, setNewFormFieldOptions,
    newFormRadioGroup, setNewFormRadioGroup,
    newFormRadioOption, setNewFormRadioOption,
    newFormCheckboxChecked, setNewFormCheckboxChecked,
    showNoteModal, setShowNoteModal,
    noteDraft, setNoteDraft,
    pendingNotePos, setPendingNotePos,
  } = annotation;
  const {
    highlightStart,
    setHighlightStart,
    highlightRect,
    setHighlightRect,
    inkDrawing,
    setInkDrawing,
    inkDraft,
    setInkDraft,
    shapeLineEnd,
    setShapeLineEnd,
    drawing,
    setDrawing,
    cancelDrawing,
  } = useDrawingGesture();
  // When a source PDF is chosen for Insert, load *its* page count so the From/To
  // range reflects the source document (not the currently open one) and defaults
  // to inserting the whole file.
  const { showToast, withLoading } = useAppLoading({ setToast, setLoading });

  const { loadFormFields, loadPdfBookmarks, loadPdfSignatures, loadPageSizes } = usePanelLoaders({
    filePath,
    setFormFields,
    setFormDrafts,
    setPdfBookmarks,
    setPdfSignatures,
    setSignatureVerification,
    setPageSizes,
  });
  loadPdfBookmarksRef.current = (path) => { void loadPdfBookmarks(path); };
  loadPageSizesRef.current = (path) => { void loadPageSizes(path); };

  const { loadPageEdits } = usePageEditsLoader({ setPageTextEdits, setPageVectorEdits });

  const {
    pageNumbersRange,
    watermarkRange,
    flattenRange,
    pageHeaderRange,
    pageFooterRange,
    pageSizeRange,
    pageBorderRange,
    expandMarginsRange,
    shrinkMarginsRange,
    pngExportRange,
    exportPagesPdfRange,
    duplicateRange,
    deleteRange,
    extractRange,
    interleaveRange,
    rotateRange,
    keepRange,
    moveRange,
    prependRange,
    reverseRange,
    cropRange,
    parityRange,
    insertRange,
    mergeRange,
  } = useAppPageRanges({ pageCount, currentPage, showToast });

  useSourcePdfPageCounts({
    insertFilePath,
    mergeFilePath,
    insertRange,
    mergeRange,
    setInsertSourcePageCount,
    setMergeSourcePageCount,
  });

  const {
    shouldShowTesseractReminder,
    closeTesseractReminderModal,
    showLaunchTesseractReminder,
    openTesseractGuide,
  } = useTesseractReminder({
    ocrAvailable,
    tesseractReminderSource,
    setTesseractReminderSource,
    tesseractDoNotRemind,
    setTesseractDoNotRemind,
    setShowTesseractModal,
    handleMarkdownViewRef,
  });

  useAppBootstrap({
    onNativeDialogs: setNativeDialogs,
    onOcrAvailable: setOcrAvailable,
    onTesseractInstallGuide: setTesseractInstallGuide,
    onShowTesseractReminder: showLaunchTesseractReminder,
  });

  const { windowTitle } = useWindowTitle({ filePath, originalPath, isDirty, isDirtyRef, filePathRef });

  const rememberBrowserDirectory = useRememberBrowserDirectory({ setLastBrowserDir });

  const {
    showUnsavedModal,
    setShowUnsavedModal,
    pendingNavRef,
    guardUnsaved,
    resolveUnsaved,
  } = useUnsavedGuard({
    isDirty,
    setIsDirty,
    onSave: () => handleSaveRef.current(),
  });

  useWindowCloseGuard({ isDirtyRef, pendingNavRef, setShowUnsavedModal });

  const { rememberOpenedPdf } = usePdfRecents({ rememberBrowserDirectory, setRecentPdfs });

  const {
    imageSrc,
    thumbnails,
    annotations,
    setAnnotations,
    loadThumbnails,
    renderPage,
    goToPage,
    reloadOpenPdf,
    refreshAfterWorkingChange,
    revokeViewerAssets,
  } = usePdfDocument({
    filePath,
    pageCount,
    currentPage,
    viewMode,
    setPageCount,
    setCurrentPage,
    setPageInput,
    setViewMode,
    setPdfRevision,
    setMarkdownRevision,
    withLoading,
    loadPageEdits,
    loadPdfBookmarks: (path) => loadPdfBookmarksRef.current(path),
    loadPageSizes: (path) => loadPageSizesRef.current(path),
    cancelDrawing: () => cancelDrawingRef.current(),
  });

  const {
    canUndo,
    canRedo,
    markPdfEdited,
    resetHistoryForOpen,
    markSaved,
    discardHistory,
    undo: undoHistory,
    redo: redoHistory,
  } = useUndoHistory({
    filePathRef,
    showToast,
    withLoading,
    onRestore: refreshAfterWorkingChange,
    setPdfRevision,
    setViewMode,
    setIsDirty,
  });

  const undo = () => undoHistory(filePath);
  const redo = () => redoHistory(filePath);

  usePageZoomInputSync({ currentPage, setPageInput, zoom, setZoomInput });

  const {
    loadPdfFromPath,
    openPdf,
    handleOpenPdfPath,
    handleOpenEncryptedPdf,
    handleOpenRecentPdf,
  } = usePdfOpen({
    filePath,
    originalPath,
    openFilePath,
    pendingEncryptedPath,
    pdfPasswordDraft,
    withLoading,
    resetHistoryForOpen,
    renderPage,
    loadThumbnails,
    loadFormFields,
    rememberOpenedPdf,
    cancelDrawing,
    guardUnsaved,
    showToast,
    setOriginalPath,
    setFilePath,
    setViewMode,
    setMarkdownText,
    setMarkdownPath,
    setMarkdownOcrNotice,
    setPdfRevision,
    setMarkdownRevision,
    setPageCount,
    setCurrentPage,
    setZoom,
    setOpenFilePath,
    setShowOpenModal,
    setPendingEncryptedPath,
    setPdfPasswordDraft,
    setShowPasswordModal,
  });

  const {
    showBrowserModal,
    setShowBrowserModal,
    browserListing,
    browserPathInput,
    setBrowserPathInput,
    loadPdfBrowser,
    openPdfBrowser,
    commitBrowserPath,
    handleBrowserEntryClick,
  } = usePdfBrowser({
    lastBrowserDir,
    originalPath,
    openFilePath,
    insertFilePath,
    replaceSourcePath,
    interleaveFilePath,
    prependFilePath,
    mergeFilePath,
    withLoading,
    loadPdfFromPath,
    rememberBrowserDirectory,
    interleaveRange,
    prependRange,
    setOpenFilePath,
    setInsertFilePath,
    setReplaceSourcePath,
    setReplaceSourcePageCount,
    setReplaceSourcePage,
    setInterleaveFilePath,
    setInterleaveSourcePageCount,
    setPrependFilePath,
    setPrependSourcePageCount,
    setMergeFilePath,
    setShowOpenModal,
  });

  const {
    showSearchModal,
    searchQuery,
    setSearchQuery,
    searchMatchCase,
    setSearchMatchCase,
    searchWholeWord,
    setSearchWholeWord,
    searchResults,
    searchResultIndex,
    activeSearchRect,
    searchInputRef,
    openSearchModal,
    closeSearchModal,
    runPdfSearch,
    stepSearchMatch,
  } = usePdfSearch({
    filePath,
    withLoading,
    renderPage,
    setViewMode,
    setCurrentPage,
    setPageInput,
    showToast,
  });

  const { printPages, handlePrint, clearPrintPages } = usePrintJobs({ filePath, pageCount, withLoading });

  const { closePdf } = useClosePdf({
    filePath,
    discardHistory,
    cancelDrawing,
    revokeViewerAssets,
    clearPrintPages,
    showToast,
    setFilePath,
    setOriginalPath,
    setIsDirty,
    setPageCount,
    setCurrentPage,
    setPageInput,
    setZoom,
    setViewMode,
    setMarkdownText,
    setMarkdownPath,
    setMarkdownOcrNotice,
    setPdfRevision,
    setMarkdownRevision,
    setHighlightMode,
    setImageInsertMode,
    setFormAddMode,
    setImageSourcePath,
    setShowImageInsertModal,
    setShowFormsPanel,
    setShowSignaturesPanel,
    setShowBookmarksPanel,
    setPdfBookmarks,
    setPageSizes,
    setPdfSignatures,
    setSignatureVerification,
    setShowSignModal,
    setShowMetadataModal,
    setFormFields,
    setFormDrafts,
    setShowAddFormFieldModal,
    setNewFormFieldName,
    setNewFormFieldKind,
    setNewFormFieldOptions,
    setNewFormRadioGroup,
    setNewFormRadioOption,
    setNewFormCheckboxChecked,
    setShowDeleteModal,
  });

  const { scrollRef, handleWheel, handleImageLoad } = useWheelNavigation({
    pageCount,
    viewMode,
    currentPage,
    goToPage,
  });

  const { handleDragStart, handleDragOver, handleDrop } = useThumbnailReorder({
    filePath,
    draggedIndex,
    withLoading,
    markPdfEdited,
    loadThumbnails,
    renderPage,
    setDraggedIndex,
    setCurrentPage,
  });

  const {
    defaultExtractOutputPath,
    defaultImageExportOutput,
    handleSave,
    openSaveAs,
    handleRotatePage,
    handleDuplicatePage,
    handleDuplicatePageBefore,
    handleDuplicatePageToEnd,
    handleDeletePage,
    handleSplitPdf,
    handleExtractPdf,
    handleInsertPdf,
    handleMergePdf,
    openMergeModal,
    handleOptimizePdf,
    handleExportPng,
    openExportPngModal,
    closePasswordModal,
    submitTextNote,
    applyFormField,
    openAddBookmarkModal,
    handleAddBookmark,
    openRenameBookmarkModal,
    handleRenameBookmark,
    handleRemoveBookmark,
    openBookmarkAllModal,
    handleBookmarkAllPages,
    handleBookmarkOddPages,
    handleBookmarkEvenPages,
    openDeleteModal,
    openInsertModal,
    openSplitModal,
    openExtractModal,
    handleRotatePageCcw,
    handleResetPageRotation,
    handleResetAllRotations,
    handleReversePages,
    handleRotateAllPages,
    handleAddBlankPage,
    handleAddBlankPageBefore,
    handleRotatePage180,
    handleRotateAllPagesCcw,
    handleMovePageToFirst,
    handleMovePageToLast,
    handleClearAllCrops,
    handleClearAllBookmarks,
    handleMovePageUp,
    handleMovePageDown,
    openDuplicateRangeModal,
    handleDuplicatePageRange,
    handleDuplicatePageRangeToEnd,
    handleDuplicatePageRangeToStart,
    handleDuplicatePageRangeBefore,
    openPageHeaderModal,
    handleAddPageHeader,
    handleAddPageHeaderOddPages,
    handleAddPageHeaderEvenPages,
    openPageFooterModal,
    handleAddPageFooter,
    handleAddPageFooterOddPages,
    handleAddPageFooterEvenPages,
    openSwapPagesModal,
    handleSwapPages,
    openReplacePageModal,
    handleReplaceSourcePathChange,
    handleReplacePage,
    openInterleaveModal,
    handleInterleaveSourcePathChange,
    handleInterleavePdf,
    handleSplitOddEven,
    handleDuplicateAllPages,
    openPageSizeModal,
    handleSetPageSize,
    handleSetPageSizeOddPages,
    handleSetPageSizeEvenPages,
    openExportPagesPdfModal,
    handleExportPagesPdf,
    handleExportOddPagesAsPdf,
    handleExportEvenPagesAsPdf,
    openExportPagePdfModal,
    handleExportPagePdf,
    openParityRangeModal,
    handleParityRangeAction,
    handleExportOddPagesImage,
    handleExportEvenPagesImage,
    openRotateRangeModal,
    handleRotatePageRange,
    handleResetRotationRange,
    handleRotatePage180Range,
    openReverseRangeModal,
    handleReversePageRange,
    openInsertBlankPagesModal,
    handleInsertBlankPages,
    openCropRangeModal,
    handleCropPageRange,
    handleFlattenAllAnnotations,
    handleClearPdfMetadata,
    handleSortPagesBySize,
    openKeepRangeModal,
    handleKeepPageRange,
    openMoveRangeModal,
    handleMovePageRange,
    handleMovePageRangeToStart,
    handleMovePageRangeToEnd,
    openDeleteRangeModal,
    handleDeletePageRange,
    handleRotateOddPages,
    handleRotateEvenPages,
    handleRotateOddPagesCcw,
    handleRotateEvenPagesCcw,
    handleResetRotationOddPages,
    handleResetRotationEvenPages,
    handleKeepOddPages,
    handleKeepEvenPages,
    handleDeleteOddPages,
    handleDeleteEvenPages,
    handleRotate180OddPages,
    handleRotate180EvenPages,
    handleDuplicateOddPages,
    handleDuplicateEvenPages,
    handleInsertBlankBetweenPages,
    handleFlattenOddPages,
    handleFlattenEvenPages,
    handleRotateAllPages180,
    handleCropOddPages,
    handleCropEvenPages,
    handleExpandOddPages,
    handleExpandEvenPages,
    handleShrinkOddPages,
    handleShrinkEvenPages,
    handleReverseOddPages,
    handleReverseEvenPages,
    handleMoveOddPagesToStart,
    handleMoveEvenPagesToStart,
    handleMoveOddPagesToEnd,
    handleMoveEvenPagesToEnd,
    handleClearCropOddPages,
    handleClearCropEvenPages,
    handleDuplicateOddPagesBefore,
    handleDuplicateEvenPagesBefore,
    handleSortOddPagesByRotation,
    handleSortEvenPagesByRotation,
    handleSortOddPagesBySize,
    handleSortEvenPagesBySize,
    handleSortPagesByRotation,
    openSplitAtModal,
    handleSplitPdfAtPage,
    openDeleteNthModal,
    handleDeleteEveryNthPage,
    openExtractOddModal,
    handleExtractOddPages,
    openExtractEvenModal,
    handleExtractEvenPages,
    openPrependModal,
    handlePrependSourcePathChange,
    handlePrependPdf,
    openSplitEveryModal,
    handleSplitEveryN,
    openPageBorderModal,
    handleAddPageBorder,
    handleAddPageBorderOddPages,
    handleAddPageBorderEvenPages,
    handleInsertBlankBeforeOddPages,
    handleInsertBlankBeforeEvenPages,
    handleInsertBlankAfterOddPages,
    handleInsertBlankAfterEvenPages,
    handleDuplicateOddPagesToEnd,
    handleDuplicateEvenPagesToEnd,
    handleDuplicateOddPagesToStart,
    handleDuplicateEvenPagesToStart,
    openExpandMarginsModal,
    openShrinkMarginsModal,
    handleShrinkPageMargins,
    handleExpandPageMargins,
    openInsertImagePageModal,
    handleInsertImagePage,
    openPageNumbersModal,
    handleAddPageNumbers,
    handleAddPageNumbersOddPages,
    handleAddPageNumbersEvenPages,
    openWatermarkModal,
    handleAddWatermark,
    handleAddWatermarkOddPages,
    handleAddWatermarkEvenPages,
    openCropModal,
    handleCropPage,
    handleClearPageCrop,
    openFlattenModal,
    handleFlattenAnnotations,
    handlePageClick,
    handlePageMouseMove,
    handleDrawMouseDown,
    handleDrawMouseUp,
    removeRedaction,
    removeStamp,
    removeShape,
    removeInkStroke,
    removeHighlight,
    removeTextNote,
    openImageInsertModal,
    confirmImageSource,
    toggleImageInsertMode,
    exitImageInsertMode,
    openAddFormFieldModal,
    confirmAddFormField,
    exitFormAddMode,
    toggleHighlightMode,
    exitHighlightMode,
    toggleNoteMode,
    toggleDrawMode,
    exitDrawMode,
    toggleShapeMode,
    exitShapeMode,
    toggleStampMode,
    exitStampMode,
    toggleTextEditMode,
    toggleVectorEditMode,
    toggleRedactMode,
    exitRedactMode,
    exitNoteMode,
    toggleFormsPanel,
    submitPageText,
    startEditPageText,
    closePageTextModal,
    exitTextEditMode,
    exitVectorEditMode,
    removePageTextEdit,
    removePageVectorEdit,
    chooseOpenPdfNative,
    chooseInsertPdfNative,
    chooseMergePdfNative,
    handleSaveAs,
    chooseSaveAsNative,
    chooseExtractOutputNative,
    chooseExportPngOutputNative,
    chooseSignCertNative,
    toggleMarkdownView,
    handleMarkdownSaveAs,
    chooseMarkdownSaveAsNative,
    openMarkdownSaveAs,
    handleSummarizePdf,
    handleCopySummary,
    handleSaveSummary,
    openProtectModal,
    openDecryptModal,
    handleRemovePdfPassword,
    openMetadataModal,
    handleSaveMetadata,
    handleProtectPdf,
    openSignModal,
    handleSignPdf,
    toggleSignaturesPanel,
  } = useAppPdfActions({
    bookmarkAllPrefix,
    bookmarkTitle,
    cancelDrawing,
    cancelDrawingRef,
    cropApplyAll,
    cropMarginBottom,
    cropMarginLeft,
    cropMarginRight,
    cropMarginTop,
    cropMargins: {
      marginTop: cropMarginTop,
      marginRight: cropMarginRight,
      marginBottom: cropMarginBottom,
      marginLeft: cropMarginLeft,
    },
    cropRange,
    currentPage,
    decryptPassword,
    deleteNthValue,
    deletePageInput,
    deleteRange,
    duplicateRange,
    drawMode,
    drawing,
    editingTextIndex,
    expandMarginBottom,
    expandMarginLeft,
    expandMarginRight,
    expandMarginTop,
    expandMargins: {
      marginTop: expandMarginTop,
      marginRight: expandMarginRight,
      marginBottom: expandMarginBottom,
      marginLeft: expandMarginLeft,
    },
    expandMarginsRange,
    exportPagePdfPath,
    exportPagesPdfOutputDir,
    exportPagesPdfRange,
    extractEndPage: extractRange.endPage,
    extractEvenOutputPath,
    extractOddOutputPath,
    extractOutputPath,
    extractRange,
    extractStartPage: extractRange.startPage,
    filePath,
    flattenRange,
    formAddMode,
    formDrafts,
    formFields,
    handleMarkdownViewRef,
    handleSaveRef,
    highlightMode,
    highlightStart,
    imageExportFormat,
    imageInsertMode,
    imageSourceDraft,
    imageSourcePath,
    imgRef,
    inkDraft,
    inkDrawing,
    insertAtPage,
    insertBlankAtIndex,
    insertBlankCount,
    insertFilePath,
    insertImageAtIndex,
    insertImagePagePath,
    insertRange,
    interleaveFilePath,
    interleaveRange,
    keepRange,
    lastBrowserDir,
    loadFormFields,
    loadPageSizes,
    loadPdfBookmarks,
    loadPdfFromPath,
    loadPdfSignatures,
    loadThumbnails,
    markPdfEdited,
    markSaved,
    markdownPath,
    markdownRevision,
    markdownSaveAsPath,
    markdownText,
    mergeFilePath,
    mergeRange,
    metadataAuthor,
    metadataCreator,
    metadataKeywords,
    metadataProducer,
    metadataSubject,
    metadataTitle,
    moveRange,
    moveRangeToIndex,
    nativeDialogs,
    newFormCheckboxChecked,
    newFormFieldKind,
    newFormFieldName,
    newFormFieldOptions,
    newFormRadioGroup,
    newFormRadioOption,
    noteDraft,
    noteMode,
    openFilePath,
    originalPath,
    pageBorderInset,
    pageBorderRange,
    pageCount,
    pageFooterRange,
    pageFooterText,
    pageHeaderRange,
    pageHeaderText,
    pageInput,
    pageNumbersPrefix,
    pageNumbersRange,
    pageSizePreset,
    pageSizeRange,
    pageTextDraft,
    pageTextFontSize,
    parityRange,
    parityRangeCommand,
    parityRangeOutputPath,
    pdfRevision,
    pdfSummary,
    pendingNotePos,
    pendingTextPos,
    pngExportEndPage: pngExportRange.endPage,
    pngExportOutputPath,
    pngExportRange,
    pngExportScope: pngExportRange.scope,
    pngExportStartPage: pngExportRange.startPage,
    prependFilePath,
    prependRange,
    protectOwnerPassword,
    protectUserPassword,
    protectUserPasswordConfirm,
    redactMode,
    reloadOpenPdf,
    rememberBrowserDirectory,
    rememberOpenedPdf,
    renameBookmarkIndex,
    renameBookmarkTitle,
    renderPage,
    replaceSourcePage,
    replaceSourcePath,
    reverseRange,
    rotateRange,
    saveAsPath,
    setAnnotations,
    setBookmarkAllPrefix,
    setBookmarkTitle,
    setCropApplyAll,
    setCropMarginBottom,
    setCropMarginLeft,
    setCropMarginRight,
    setCropMarginTop,
    setCurrentPage,
    setDecryptPassword,
    setDeleteNthValue,
    setDeletePageInput,
    setDrawMode,
    setDrawing,
    setEditingTextIndex,
    setExpandMarginBottom,
    setExpandMarginLeft,
    setExpandMarginRight,
    setExpandMarginTop,
    setExportPagePdfPath,
    setExportPagesPdfOutputDir,
    setExtractEvenOutputPath,
    setExtractOddOutputPath,
    setExtractOutputPath,
    setFormAddMode,
    setHighlightMode,
    setHighlightRect,
    setHighlightStart,
    setImageInsertMode,
    setImageSourceDraft,
    setImageSourcePath,
    setInkDraft,
    setInkDrawing,
    setInsertAtPage,
    setInsertBlankAtIndex,
    setInsertBlankCount,
    setInsertFilePath,
    setInsertImageAtIndex,
    setInsertImagePagePath,
    setInterleaveFilePath,
    setInterleaveSourcePageCount,
    setMarkdownOcrNotice,
    setMarkdownPath,
    setMarkdownRevision,
    setMarkdownSaveAsPath,
    setMarkdownText,
    setMergeFilePath,
    setMetadataAuthor,
    setMetadataCreationDate,
    setMetadataCreator,
    setMetadataKeywords,
    setMetadataModDate,
    setMetadataProducer,
    setMetadataSubject,
    setMetadataTitle,
    setMoveRangeToIndex,
    setNewFormCheckboxChecked,
    setNewFormFieldKind,
    setNewFormFieldName,
    setNewFormFieldOptions,
    setNewFormRadioGroup,
    setNewFormRadioOption,
    setNoteDraft,
    setNoteMode,
    setOpenFilePath,
    setOriginalPath,
    setPageBorderInset,
    setPageCount,
    setPageFooterText,
    setPageHeaderText,
    setPageInput,
    setPageNumbersPrefix,
    setPageSizePreset,
    setPageTextDraft,
    setPageTextFontSize,
    setParityRangeCommand,
    setPdfPasswordDraft,
    setPdfRevision,
    setPdfSummary,
    setPendingEncryptedPath,
    setPendingNotePos,
    setPendingTextPos,
    setPngExportOutputPath,
    setPrependFilePath,
    setPrependSourcePageCount,
    setProtectOwnerPassword,
    setProtectUserPassword,
    setProtectUserPasswordConfirm,
    setRedactMode,
    setRenameBookmarkIndex,
    setRenameBookmarkTitle,
    setReplaceSourcePage,
    setReplaceSourcePageCount,
    setReplaceSourcePath,
    setSaveAsPath,
    setShapeLineEnd,
    setShapeMode,
    setShowAddBookmarkModal,
    setShowAddFormFieldModal,
    setShowBookmarkAllModal,
    setShowCropModal,
    setShowCropRangeModal,
    setShowDecryptModal,
    setShowDeleteModal,
    setShowDeleteNthModal,
    setShowDeleteRangeModal,
    setShowDuplicateRangeModal,
    setShowExpandMarginsModal,
    setShowExportPagePdfModal,
    setShowExportPagesPdfModal,
    setShowExportPngModal,
    setShowExtractEvenModal,
    setShowExtractModal,
    setShowExtractOddModal,
    setShowFlattenModal,
    setShowFormsPanel,
    setShowImageInsertModal,
    setShowInsertBlankPagesModal,
    setShowInsertImagePageModal,
    setShowInsertModal,
    setShowInterleaveModal,
    setShowKeepRangeModal,
    setShowMarkdownSaveAsModal,
    setShowMergeModal,
    setShowMetadataModal,
    setShowMoveRangeModal,
    setShowNoteModal,
    setShowOpenModal,
    setShowPageBorderModal,
    setShowPageEditsModal,
    setShowPageFooterModal,
    setShowPageHeaderModal,
    setShowPageNumbersModal,
    setShowPageSizeModal,
    setShowPageTextModal,
    setShowParityRangeModal,
    setShowPasswordModal,
    setShowPrependModal,
    setShowProtectModal,
    setShowRenameBookmarkModal,
    setShowReplacePageModal,
    setShowReverseRangeModal,
    setShowRotateRangeModal,
    setShowSaveAsModal,
    setShowShrinkMarginsModal,
    setShowSignModal,
    setShowSignaturesPanel,
    setShowSplitAtModal,
    setShowSplitEveryModal,
    setShowSplitModal,
    setShowSummaryModal,
    setShowSwapPagesModal,
    setShowTesseractModal,
    setShowWatermarkModal,
    setShrinkMarginBottom,
    setShrinkMarginLeft,
    setShrinkMarginRight,
    setShrinkMarginTop,
    setSignCertPassword,
    setSignCertPath,
    setSignLocation,
    setSignReason,
    setSplitAtPage,
    setSplitEveryN,
    setSplitRanges,
    setStampMode,
    setSwapPageA,
    setSwapPageB,
    setTesseractReminderSource,
    setTextEditMode,
    setVectorEditMode,
    setViewMode,
    setWatermarkText,
    shapeKind,
    shapeMode,
    shouldShowTesseractReminder,
    showToast,
    shrinkMarginBottom,
    shrinkMarginLeft,
    shrinkMarginRight,
    shrinkMarginTop,
    shrinkMargins: {
      marginTop: shrinkMarginTop,
      marginRight: shrinkMarginRight,
      marginBottom: shrinkMarginBottom,
      marginLeft: shrinkMarginLeft,
    },
    shrinkMarginsRange,
    signCertPassword,
    signCertPath,
    signLocation,
    signReason,
    splitAtPage,
    splitEveryN,
    splitRanges,
    stampKind,
    stampMode,
    stampPreset,
    swapPageA,
    swapPageB,
    textEditMode,
    vectorEditMode,
    viewMode,
    watermarkRange,
    watermarkText,
    withLoading,
    zoom,
  });

  const { zoomIn, zoomOut, resetZoom, commitZoom, commitPage } = usePageZoom({
    zoom,
    setZoom,
    zoomInput,
    setZoomInput,
    pageInput,
    setPageInput,
    pageCount,
    currentPage,
    goToPage,
  });

  const { dismissModals, anyModalOpen } = useModalDismiss(buildModalDismissSource({
    showUnsavedModal,
    showSaveAsModal,
    showMarkdownSaveAsModal,
    showProtectModal,
    showSignModal,
    showMetadataModal,
    showPasswordModal,
    showOpenModal,
    showBrowserModal,
    showDeleteModal,
    showSplitModal,
    showExtractModal,
    showExportPngModal,
    showDeleteRangeModal,
    showPageNumbersModal,
    showWatermarkModal,
    showCropModal,
    showFlattenModal,
    showAddBookmarkModal,
    showRenameBookmarkModal,
    showDuplicateRangeModal,
    showPageHeaderModal,
    showPageFooterModal,
    showSwapPagesModal,
    showReplacePageModal,
    showInterleaveModal,
    showPageSizeModal,
    showDecryptModal,
    showRotateRangeModal,
    showKeepRangeModal,
    showMoveRangeModal,
    showPrependModal,
    showSplitEveryModal,
    showPageBorderModal,
    showBookmarkAllModal,
    showExpandMarginsModal,
    showShrinkMarginsModal,
    showDeleteNthModal,
    showExtractOddModal,
    showExtractEvenModal,
    showSplitAtModal,
    showReverseRangeModal,
    showInsertBlankPagesModal,
    showCropRangeModal,
    showParityRangeModal,
    showExportPagesPdfModal,
    showInsertImagePageModal,
    showExportPagePdfModal,
    showInsertModal,
    showMergeModal,
    showSearchModal,
    showNoteModal,
    showImageInsertModal,
    showAddFormFieldModal,
    showSummaryModal,
    showPageTextModal,
    showPageEditsModal,
    showCommandPalette,
    showShortcutsHelp,
    showLicenses,
    showCredits,
    showAbout,
    showTesseractModal,
    closeSearchModal,
    resolveUnsaved,
    setShowSaveAsModal,
    setShowMarkdownSaveAsModal,
    setShowProtectModal,
    setShowSignModal,
    setShowMetadataModal,
    setShowPasswordModal,
    setPendingEncryptedPath,
    setPdfPasswordDraft,
    setShowOpenModal,
    setShowBrowserModal,
    setShowDeleteModal,
    setShowSplitModal,
    setShowExtractModal,
    setShowExportPngModal,
    setShowDeleteRangeModal,
    setShowPageNumbersModal,
    setShowWatermarkModal,
    setShowCropModal,
    setShowFlattenModal,
    setShowAddBookmarkModal,
    setShowRenameBookmarkModal,
    setShowDuplicateRangeModal,
    setShowPageHeaderModal,
    setShowPageFooterModal,
    setShowSwapPagesModal,
    setShowReplacePageModal,
    setShowInterleaveModal,
    setShowPageSizeModal,
    setShowDecryptModal,
    setShowRotateRangeModal,
    setShowKeepRangeModal,
    setShowMoveRangeModal,
    setShowPrependModal,
    setShowSplitEveryModal,
    setShowPageBorderModal,
    setShowBookmarkAllModal,
    setShowExpandMarginsModal,
    setShowReverseRangeModal,
    setShowInsertBlankPagesModal,
    setShowCropRangeModal,
    setShowExportPagesPdfModal,
    setShowInsertImagePageModal,
    setShowExportPagePdfModal,
    setShowInsertModal,
    setInsertFilePath,
    setShowMergeModal,
    setMergeFilePath,
    setShowImageInsertModal,
    setShowAddFormFieldModal,
    setShowSummaryModal,
    setShowPageTextModal,
    setEditingTextIndex,
    setPendingTextPos,
    setShowPageEditsModal,
    setShowCommandPalette,
    setShowShortcutsHelp,
    setShowLicenses,
    setShowCredits,
    setShowAbout,
    setShowTesseractModal,
  }));

  useAppKeyboardBinding(keyboardActionsRef, {
    isDirty,
    canUndo,
    canRedo,
    filePath,
    noteMode,
    drawMode,
    shapeMode,
    stampMode,
    redactMode,
    imageInsertMode,
    textEditMode,
    vectorEditMode,
    formAddMode,
    highlightMode,
    anyModalOpen,
    pageCount,
    currentPage,
    viewMode,
    openPdf,
    setShowCommandPalette,
    dismissModals,
    exitNoteMode,
    exitDrawMode,
    exitShapeMode,
    exitStampMode,
    exitRedactMode,
    exitImageInsertMode,
    exitTextEditMode,
    exitVectorEditMode,
    exitFormAddMode,
    exitHighlightMode,
    goToPage,
    toggleHighlightMode,
    toggleNoteMode,
    toggleDrawMode,
    toggleShapeMode,
    toggleStampMode,
    toggleRedactMode,
    toggleTextEditMode,
    toggleVectorEditMode,
    toggleImageInsertMode,
    toggleFormsPanel,
    openDeleteModal,
    openSaveAs,
    handleSave,
    guardUnsaved,
    closePdf,
    handlePrint,
    handleRotatePage,
    openSearchModal,
    handleDuplicatePage,
    toggleMarkdownView,
    handleOptimizePdf,
    handleSummarizePdf,
    openSignModal,
    openInsertModal,
    openSplitModal,
    openExtractModal,
    openExportPngModal,
    handleAddBlankPage,
    handleReversePages,
    openMergeModal,
    zoomIn,
    zoomOut,
    resetZoom,
    undo,
    redo,
  });

  const appMenus = buildAppMenusFromSource({
    filePath,
    isDirty,
    canUndo,
    canRedo,
    pageCount,
    currentPage,
    viewMode,
    highlightMode,
    noteMode,
    drawMode,
    shapeMode,
    stampMode,
    redactMode,
    imageInsertMode,
    textEditMode,
    vectorEditMode,
    showFormsPanel,
    showBookmarksPanel,
    showSignaturesPanel,
    ocrAvailable,
    guardUnsaved,
    closePdf,
    setViewMode,
    setShowBookmarksPanel,
    setShowPageEditsModal,
    setShowShortcutsHelp,
    setShowLicenses,
    setShowCredits,
    setShowAbout,
    setShowCommandPalette,
    openTesseractGuide,
    openPdf,
    handleSave,
    openSaveAs,
    undo,
    redo,
    handlePrint,
    openSearchModal,
    handleRotatePage,
    handleRotatePageCcw,
    handleResetPageRotation,
    handleRotatePage180,
    handleRotateAllPages,
    handleRotateAllPagesCcw,
    handleRotateAllPages180,
    handleRotateOddPages,
    handleRotateEvenPages,
    handleRotateOddPagesCcw,
    handleRotateEvenPagesCcw,
    handleRotate180OddPages,
    handleRotate180EvenPages,
    handleResetRotationOddPages,
    handleResetRotationEvenPages,
    handleResetAllRotations,
    openRotateRangeModal,
    handleDuplicatePage,
    handleDuplicatePageBefore,
    openDuplicateRangeModal,
    openParityRangeModal,
    openMoveRangeModal,
    openKeepRangeModal,
    handleKeepOddPages,
    handleKeepEvenPages,
    handleDeleteOddPages,
    handleDeleteEvenPages,
    handleAddBlankPage,
    handleAddBlankPageBefore,
    openInsertBlankPagesModal,
    handleInsertBlankBetweenPages,
    handleInsertBlankBeforeOddPages,
    handleInsertBlankBeforeEvenPages,
    handleInsertBlankAfterOddPages,
    handleInsertBlankAfterEvenPages,
    handleMovePageToFirst,
    handleMovePageToLast,
    handleMovePageUp,
    handleMovePageDown,
    openSwapPagesModal,
    handleReversePages,
    openReverseRangeModal,
    handleReverseOddPages,
    handleReverseEvenPages,
    handleMoveOddPagesToStart,
    handleMoveEvenPagesToStart,
    handleMoveOddPagesToEnd,
    handleMoveEvenPagesToEnd,
    handleSplitOddEven,
    handleDuplicateAllPages,
    handleDuplicatePageToEnd,
    handleDuplicateOddPages,
    handleDuplicateEvenPages,
    handleDuplicateOddPagesBefore,
    handleDuplicateEvenPagesBefore,
    handleDuplicateOddPagesToEnd,
    handleDuplicateEvenPagesToEnd,
    handleDuplicateOddPagesToStart,
    handleDuplicateEvenPagesToStart,
    openDeleteModal,
    openDeleteRangeModal,
    openDeleteNthModal,
    openInsertModal,
    openMergeModal,
    openInterleaveModal,
    openPrependModal,
    openReplacePageModal,
    openSplitModal,
    openSplitAtModal,
    openSplitEveryModal,
    openExtractModal,
    openExtractOddModal,
    openExtractEvenModal,
    toggleMarkdownView,
    handleOptimizePdf,
    openExportPngModal,
    openExportPagePdfModal,
    openExportPagesPdfModal,
    openInsertImagePageModal,
    openPageNumbersModal,
    openPageHeaderModal,
    openPageFooterModal,
    openPageSizeModal,
    openWatermarkModal,
    openCropModal,
    openCropRangeModal,
    handleCropOddPages,
    handleCropEvenPages,
    openExpandMarginsModal,
    openShrinkMarginsModal,
    openPageBorderModal,
    openFlattenModal,
    handleFlattenAllAnnotations,
    handleFlattenOddPages,
    handleFlattenEvenPages,
    handleSortPagesBySize,
    handleSortOddPagesBySize,
    handleSortEvenPagesBySize,
    handleSortPagesByRotation,
    handleSortOddPagesByRotation,
    handleSortEvenPagesByRotation,
    openMetadataModal,
    handleSummarizePdf,
    openProtectModal,
    openDecryptModal,
    openSignModal,
    toggleSignaturesPanel,
    toggleRedactMode,
    toggleHighlightMode,
    toggleNoteMode,
    toggleDrawMode,
    toggleShapeMode,
    toggleStampMode,
    toggleImageInsertMode,
    toggleTextEditMode,
    toggleVectorEditMode,
    toggleFormsPanel,
  });

  const modeToolbarExtras = buildModeToolbarExtras({
    filePath,
    imageInsertMode,
    imageSourcePath,
    onOpenImageInsertModal: openImageInsertModal,
    stampMode,
    stampKind,
    stampPreset,
    onStampKindChange: setStampKind,
    onStampPresetChange: setStampPreset,
    shapeMode,
    shapeKind,
    onShapeKindChange: setShapeKind,
  });

  const modalCtx = buildAppModalsSource({
    bookmarkAllPrefix, bookmarkTitle, browserListing, browserPathInput,
    chooseExportPngOutputNative, chooseExtractOutputNative, chooseInsertPdfNative, chooseMarkdownSaveAsNative,
    chooseMergePdfNative, chooseOpenPdfNative, chooseSaveAsNative, chooseSignCertNative,
    closePageTextModal, closePasswordModal, closeSearchModal, closeTesseractReminderModal,
    commitBrowserPath, confirmAddFormField, confirmImageSource, cropApplyAll,
    cropMarginBottom, cropMarginLeft, cropMarginRight, cropMarginTop,
    cropRange, currentPage, decryptPassword, defaultExtractOutputPath,
    expandMarginBottom, expandMarginLeft, expandMarginRight, expandMarginTop,
    defaultImageExportOutput, deleteNthValue, deletePageInput, deleteRange,
    duplicateRange, editingTextIndex, exitNoteMode, expandMarginsRange,
    exportPagePdfPath, exportPagesPdfOutputDir, exportPagesPdfRange, extractEvenOutputPath,
    extractOddOutputPath, extractOutputPath, extractRange, fileNameFromPath,
    flattenRange, handleAddBookmark, handleAddPageBorder, handleAddPageBorderEvenPages,
    handleAddPageBorderOddPages, handleAddPageFooter, handleAddPageFooterEvenPages, handleAddPageFooterOddPages,
    handleAddPageHeader, handleAddPageHeaderEvenPages, handleAddPageHeaderOddPages, handleAddPageNumbers,
    handleAddPageNumbersEvenPages, handleAddPageNumbersOddPages, handleAddWatermark, handleAddWatermarkEvenPages,
    handleAddWatermarkOddPages, handleBookmarkAllPages, handleBookmarkEvenPages, handleBookmarkOddPages,
    handleBrowserEntryClick, handleClearAllCrops, handleClearCropEvenPages, handleClearCropOddPages,
    handleClearPageCrop, handleClearPdfMetadata, handleCopySummary, handleCropEvenPages,
    handleCropOddPages, handleCropPage, handleCropPageRange, handleDeleteEveryNthPage,
    handleDeletePage, handleDeletePageRange, handleDuplicatePageRange, handleDuplicatePageRangeBefore,
    handleDuplicatePageRangeToEnd, handleDuplicatePageRangeToStart, handleExpandEvenPages, handleExpandOddPages,
    handleExpandPageMargins, handleExportEvenPagesAsPdf, handleExportEvenPagesImage, handleExportOddPagesAsPdf,
    handleExportOddPagesImage, handleExportPagePdf, handleExportPagesPdf, handleExportPng,
    handleExtractEvenPages, handleExtractOddPages, handleExtractPdf, handleFlattenAnnotations,
    handleInsertBlankPages, handleInsertImagePage, handleInsertPdf, handleInterleavePdf,
    handleInterleaveSourcePathChange, handleKeepPageRange, handleMarkdownSaveAs, handleMergePdf,
    handleMovePageRange, handleMovePageRangeToEnd, handleMovePageRangeToStart, handleOpenEncryptedPdf,
    handleOpenPdfPath, handleOpenRecentPdf, handleParityRangeAction, handlePrependPdf,
    handlePrependSourcePathChange, handleProtectPdf, handleRemovePdfPassword, handleRenameBookmark,
    handleReplacePage, handleReplaceSourcePathChange, handleResetRotationRange, handleReversePageRange,
    handleRotatePage180Range, handleRotatePageRange, handleSaveAs, handleSaveMetadata,
    handleSaveSummary, handleSetPageSize, handleSetPageSizeEvenPages, handleSetPageSizeOddPages,
    handleShrinkEvenPages, handleShrinkOddPages, handleShrinkPageMargins, handleSignPdf,
    handleSplitEveryN, handleSplitPdf, handleSplitPdfAtPage, handleSwapPages,
    imageExportFormat, imageSourceDraft, insertAtPage, insertBlankAtIndex,
    insertBlankCount, insertFilePath, insertImageAtIndex, insertImagePagePath,
    insertRange, insertSourcePageCount, interleaveFilePath, interleaveRange,
    interleaveSourcePageCount, keepRange, loadPdfBrowser, markdownSaveAsPath,
    mergeFilePath, mergeRange, mergeSourcePageCount, metadataAuthor,
    metadataCreationDate, metadataCreator, metadataKeywords, metadataModDate,
    metadataProducer, metadataSubject, metadataTitle, moveRange,
    moveRangeToIndex, nativeDialogs, newFormCheckboxChecked, newFormFieldKind,
    newFormFieldName, newFormFieldOptions, newFormRadioGroup, newFormRadioOption,
    noteDraft, openFilePath, openPdfBrowser, pageBorderInset,
    pageBorderRange, pageCount, pageFooterRange, pageFooterText,
    pageHeaderRange, pageHeaderText, pageNumbersPrefix, pageNumbersRange,
    pageSizePreset, pageSizeRange, pageTextDraft, pageTextEdits,
    pageTextFontSize, pageVectorEdits, parityRange, parityRangeCommand,
    parityRangeOutputPath, pdfPasswordDraft, pdfSummary, pngExportOutputPath,
    pngExportRange, prependFilePath, prependRange, prependSourcePageCount,
    protectOwnerPassword, protectUserPassword, protectUserPasswordConfirm, recentPdfs,
    removePageTextEdit, removePageVectorEdit, renameBookmarkTitle, replaceSourcePage,
    replaceSourcePageCount, replaceSourcePath, resolveUnsaved, reverseRange,
    rotateRange, runPdfSearch, saveAsPath, searchInputRef,
    searchMatchCase, searchQuery, searchResultIndex, searchResults,
    searchWholeWord, setBookmarkAllPrefix, setBookmarkTitle, setBrowserPathInput,
    setCropApplyAll, setCropMarginBottom, setCropMarginLeft, setCropMarginRight,
    setCropMarginTop, setDecryptPassword, setDeleteNthValue, setDeletePageInput,
    setExpandMarginBottom, setExpandMarginLeft, setExpandMarginRight,
    setExpandMarginTop, setExportPagePdfPath, setExportPagesPdfOutputDir, setExtractEvenOutputPath,
    setExtractOddOutputPath, setExtractOutputPath, setImageExportFormat, setImageSourceDraft,
    setInsertAtPage, setInsertBlankAtIndex, setInsertBlankCount, setInsertFilePath,
    setInsertImageAtIndex, setInsertImagePagePath, setMarkdownSaveAsPath, setMergeFilePath,
    setMetadataAuthor, setMetadataCreator, setMetadataKeywords, setMetadataProducer,
    setMetadataSubject, setMetadataTitle, setMoveRangeToIndex, setNewFormCheckboxChecked,
    setNewFormFieldKind, setNewFormFieldName, setNewFormFieldOptions, setNewFormRadioGroup,
    setNewFormRadioOption, setNoteDraft, setOpenFilePath, setPageBorderInset,
    setPageFooterText, setPageHeaderText, setPageNumbersPrefix, setPageSizePreset,
    setPageTextDraft, setPageTextFontSize, setParityRangeCommand, setParityRangeOutputPath,
    setPdfPasswordDraft, setPngExportOutputPath, setProtectOwnerPassword, setProtectUserPassword,
    setProtectUserPasswordConfirm, setRenameBookmarkTitle, setReplaceSourcePage, setSaveAsPath,
    setSearchMatchCase, setSearchQuery, setSearchWholeWord, setShowAddBookmarkModal,
    setShowAddFormFieldModal, setShowBookmarkAllModal, setShowBrowserModal, setShowCropModal,
    setShowCropRangeModal, setShowDecryptModal, setShowDeleteModal, setShowDeleteNthModal,
    setShowDeleteRangeModal, setShowDuplicateRangeModal, setShowExpandMarginsModal, setShowExportPagePdfModal,
    setShowExportPagesPdfModal, setShowExportPngModal, setShowExtractEvenModal, setShowExtractModal,
    setShowExtractOddModal, setShowFlattenModal, setShowImageInsertModal, setShowInsertBlankPagesModal,
    setShowInsertImagePageModal, setShowInsertModal, setShowInterleaveModal, setShowKeepRangeModal,
    setShowMarkdownSaveAsModal, setShowMergeModal, setShowMetadataModal, setShowMoveRangeModal,
    setShowOpenModal, setShowPageBorderModal, setShowPageEditsModal, setShowPageFooterModal,
    setShowPageHeaderModal, setShowPageNumbersModal, setShowPageSizeModal, setShowParityRangeModal,
    setShowPrependModal, setShowProtectModal, setShowRenameBookmarkModal, setShowReplacePageModal,
    setShowReverseRangeModal, setShowRotateRangeModal, setShowSaveAsModal, setShowShrinkMarginsModal,
    setShowSignModal, setShowSplitAtModal, setShowSplitEveryModal, setShowSplitModal,
    setShowSummaryModal, setShowSwapPagesModal, setShowWatermarkModal, setShrinkMarginBottom,
    setShrinkMarginLeft, setShrinkMarginRight, setShrinkMarginTop, setSignCertPassword,
    setSignCertPath, setSignLocation, setSignReason, setSplitAtPage,
    setSplitEveryN, setSplitRanges, setSwapPageA,
    setSwapPageB, setTesseractDoNotRemind, setWatermarkText, showAddBookmarkModal,
    showAddFormFieldModal, showBookmarkAllModal, showBrowserModal, showCropModal,
    showCropRangeModal, showDecryptModal, showDeleteModal, showDeleteNthModal,
    showDeleteRangeModal, showDuplicateRangeModal, showExpandMarginsModal, showExportPagePdfModal,
    showExportPagesPdfModal, showExportPngModal, showExtractEvenModal, showExtractModal,
    showExtractOddModal, showFlattenModal, showImageInsertModal, showInsertBlankPagesModal,
    showInsertImagePageModal, showInsertModal, showInterleaveModal, showKeepRangeModal,
    showMarkdownSaveAsModal, showMergeModal, showMetadataModal, showMoveRangeModal,
    showNoteModal, showOpenModal, showPageBorderModal, showPageEditsModal,
    showPageFooterModal, showPageHeaderModal, showPageNumbersModal, showPageSizeModal,
    showPageTextModal, showParityRangeModal, showPasswordModal, showPrependModal,
    showProtectModal, showRenameBookmarkModal, showReplacePageModal, showReverseRangeModal,
    showRotateRangeModal, showSaveAsModal, showSearchModal, showShrinkMarginsModal,
    showSignModal, showSplitAtModal, showSplitEveryModal, showSplitModal,
    showSummaryModal, showSwapPagesModal, showTesseractModal, showToast,
    showUnsavedModal, showWatermarkModal, shrinkMarginBottom, shrinkMarginLeft,
    shrinkMarginRight, shrinkMarginTop, shrinkMarginsRange, signCertPassword,
    signCertPath, signLocation, signReason, splitAtPage,
    splitEveryN, splitRanges, startEditPageText, stepSearchMatch,
    submitPageText, submitTextNote, swapPageA, swapPageB,
    tesseractDoNotRemind, tesseractInstallGuide, watermarkRange, watermarkText,
    pageSizes,
  });


  return (
    <AppShell
      {...buildAppShellSource({
        windowTitle,
        toast,
        loading,
        chrome: {
          menus: appMenus,
          showCommandPalette,
          showShortcutsHelp,
          showLicenses,
          showCredits,
          showAbout,
          setShowCommandPalette,
          setShowShortcutsHelp,
          setShowLicenses,
          setShowCredits,
          setShowAbout,
          modeExtras: modeToolbarExtras,
          pageCount,
          viewMode,
          currentPage,
          pageInput,
          pageSizes,
          setPageInput,
          commitPage,
          goToPage,
          zoom,
          zoomInput,
          setZoomInput,
          commitZoom,
          zoomIn,
          zoomOut,
          resetZoom,
        },
        viewer: {
          filePath,
          thumbnails,
          currentPage,
          draggedIndex,
          handleDragStart,
          handleDragOver,
          handleDrop,
          goToPage,
          showBookmarksPanel,
          pdfBookmarks,
          openAddBookmarkModal,
          openBookmarkAllModal,
          handleClearAllBookmarks,
          loadPdfBookmarks,
          openRenameBookmarkModal,
          handleRemoveBookmark,
          showSignaturesPanel,
          pdfSignatures,
          signatureVerification,
          loadPdfSignatures,
          showFormsPanel,
          formFields,
          formDrafts,
          setFormDrafts,
          openAddFormFieldModal,
          applyFormField,
          viewMode,
          scrollRef,
          handleWheel,
          openPdf,
          markdownOcrNotice,
          markdownPath,
          markdownText,
          openMarkdownSaveAs,
          zoom,
          imageSrc,
          imgRef,
          handleImageLoad,
          highlightMode,
          noteMode,
          drawMode,
          shapeMode,
          stampMode,
          redactMode,
          imageInsertMode,
          textEditMode,
          vectorEditMode,
          formAddMode,
          handlePageClick,
          handleDrawMouseDown,
          handlePageMouseMove,
          handleDrawMouseUp,
          activeSearchRect,
          annotations,
          shapeKind,
          drawing,
          highlightStart,
          highlightRect,
          shapeLineEnd,
          inkDraft,
          pageTextEdits,
          pageVectorEdits,
          removeHighlight,
          removeRedaction,
          removeStamp,
          removeShape,
          removeInkStroke,
          removeTextNote,
        },
        modalCtx,
        printPages,
      })}
    />
  );
}

export default App;
